using KolayCAR.Broker.API.Models;
using KolayCAR.Broker.Domain.Models;
using KolayCAR.Broker.Domain.Models.Requests;
using KolayCAR.Broker.Infrastructure.Extensions;
using KolayCAR.Broker.Infrastructure.Helpers;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace KolayCAR.Broker.API.Mappers
{
    public static class ReservationMapper
    {
        public static Reservation Map(this Rez reservation) =>
            reservation != null ? new Reservation
            {
                ReservationId = reservation.Rezid,
                ReservationNumber = reservation.Rezno,
                APIReservationNumber = reservation.Apireservationnumber,
                AgencyReservationReference = reservation.Agencyreservationreference,
                MemberId = reservation.Uyeid ?? 0,
                VendorType = (VendorTypes)reservation.Vendortype,
                AgencyId = reservation.Agencyid ?? 0,
                APIVendorId = reservation.Tedarikciid ?? 0,
                VendorId = reservation.Vendorid,
                VendorPhone = reservation.Vendorphone,
                VendorEmail = reservation.Vendoremail,
                VendorName = reservation.Vendorname,
                APIVendorName = reservation.Apivendorname,
                VehicleId = reservation.Aracid,
                ReservationDate = reservation.Tarih,
                PickupDate = reservation.Alistarihi,
                ReturnDate = reservation.Birakistarihi,
                PickupLocationId = reservation.Alisyerid,
                ReturnLocationId = reservation.Birakisyerid,
                CurrencyType = (CurrencyTypes)(reservation.Dovizid - 1),
                CurrencyCode = ((CurrencyTypes)(reservation.Dovizid - 1)).ToString(),
                LanguageType = (LanguageTypes)(reservation.Dilid - 1),
                RentalDuration = reservation.Kiralamasuresi,
                DailyPrice = Convert.ToSingle(reservation.Gunlukfiyat),
                ExtraPrice = Convert.ToSingle(reservation.Extratutar),
                OneWayFee = Convert.ToSingle(reservation.Tekyontutar),
                TotalPrice = Convert.ToSingle(reservation.Toplamtutar),
                PaidAmount = (PaymentTypes)reservation.Paymenttype != PaymentTypes.CommissionFree ? Convert.ToSingle(reservation.Odenentutar) : Convert.ToSingle(reservation.Toplamtutar),
                CustomerName = reservation.Musteriad,
                CustomerSurname = reservation.Musterisoyad,
                CustomerPhone = reservation.Musteritelefon,
                CustomerMail = reservation.Musterieposta,
                CustomerIdentityNumber = reservation.Musteritcpasaport,
                CustomerAddress = reservation.Musteriadres,
                CustomerTitle = reservation.Musteriunvan,
                CustomerTaxOffice = reservation.Musterivergidaire,
                CustomerTaxNumber = reservation.Musterivergino,
                CustomerArrivalFlightNumber = reservation.Musterigelisucusno,
                CustomerReturnFlightNumber = reservation.Musteridonusucusno,
                CustomerNote = reservation.Musterinot,
                BulletinActive = reservation.Musteriebulten ?? true,
                VehicleName = reservation.Aracadi,
                PickupLocationName = reservation.Alisyeri,
                ReturnLocationName = reservation.Birakisyeri,
                ExtraIds = reservation.Extraidlist,
                IpAddress = reservation.Ip,
                PaymentType = (PaymentTypes)reservation.Paymenttype,
                SkyScannerRedirectId = reservation.Skyscannerredirectid,
                ReservationStatusType = (ReservationStatusTypes)(reservation.Resstatusid * -1 - 1),
                ReservationStatusNote = reservation.Resstatusnote,
                PdfUrl = reservation.Pdf,
                ReservationPostedToAPI = reservation.Servisegonderildi,
                APIReservationSuccessfully = reservation.Apireservationsuccessfully,
                APIDailyPrice = reservation.Apidailyprice.ToFloatNullSafe(),
                APIExtraAmount = reservation.Apiextraamount.ToFloatNullSafe(),
                APIOneWayFee = reservation.Apionewayfee.ToFloatNullSafe(),
                APITotalAmount = reservation.Apitotalamount.ToFloatNullSafe(),
                AgencyCommission = reservation.Agencycommission.ToFloatNullSafe(),
                ProfitMarkup = reservation.Profitmarkup.ToFloatNullSafe(),
                StatusName = reservation.Statusname,
                AgencyName = reservation.Agencyname,
                APIReservationCancel = reservation.Apireservationcancel ?? false,
                ServiceCharge = reservation.Servicecharge.ToFloatNullSafe(),
                ServiceChargeCurrencyType = (CurrencyTypes)(reservation.Servicechargecurrencyid - 1),
                APIVendorPickupAddress = reservation.Apivendoraddress,
                APIVendorReturnAddress = reservation.Apivendorreturnaddress,
                APIVendorPickupPhone = reservation.Apivendorphone,
                APIVendorReturnPhone = reservation.Apivendorreturnphone,
                IsCancelable = reservation.Iscancelable.ToBoolNullSafe(),
                DepositPrice = reservation.Depositprice.ToFloatNullAvailable(),
                VendorMinimumDriverAge = reservation.Vendormindriverage ?? 0,
                VendorMinimumDrivingLicenseAge = reservation.Vendormindrivinglicenseage ?? 0,
                SendReservationMail = reservation.Sendreservationmail ?? false,
                APIMessage = reservation.Apimessage,
                CustomerBirthday = reservation.Customerbirthday,
                DepartureInfo = reservation.Departureinfo,
                VehicleImageUrl = reservation.Vehicleimageurl,
                IsOffice = reservation.Isoffice ?? false,
                FuelType = reservation.Fueltype != null ? (FuelTypes)(reservation.Fueltype - 1) : FuelTypes.None,
                TransmissionType = reservation.Transmissiontype != null ? (TransmissionTypes)(reservation.Transmissiontype - 1) : TransmissionTypes.None,
                VehicleType = reservation.Vehicletype != null ? (VehicleTypes)(reservation.Vehicletype - 1) : VehicleTypes.None,
                VehicleCategoryType = reservation.Vehiclecategorytype != null ? (VehicleCategoryTypes)(reservation.Vehiclecategorytype - 1) : VehicleCategoryTypes.None,
                PassangerQuantityType = reservation.Passangerquantitytype != null ? (PassangerQuantityTypes)(reservation.Passangerquantitytype - 1) : PassangerQuantityTypes.None,
                BaggageQuantityType = reservation.Baggagequantitytype != null ? (BaggageQuantityTypes)(reservation.Baggagequantitytype - 1) : BaggageQuantityTypes.None,
                VendorLogo = reservation.Vendorlogo,
                APIReferenceCode = reservation.Apireferencecode,
                APIReferenceCode2 = reservation.Apireferencecode2,
                APIReferenceCode3 = reservation.Apireferencecode3,
                APICurrencyType = (CurrencyTypes)((reservation.Apicurrencyid ?? 1) - 1),
                APICurrencyCode = ((CurrencyTypes)((reservation.Apicurrencyid ?? 1) - 1)).ToString(),
                AgencyCode = reservation.Agencycode,
                ExchangeRate = reservation.Exchangerate.ToFloatNullSafe(),
                APIExchangeRate = reservation.Apiexchangerate.ToFloatNullSafe(),
                DepositCreditCardRequired = reservation.Depositcreditcardrequired ?? false,
                APIPhoneActive = reservation.Apiphoneactive ?? false,
                PaymentResultMessage = reservation.Paymentresultmessage,
                PaymentResultCode = reservation.Paymentresultcode,
                BankId = reservation.Bankid,
                ProvisionNumber = reservation.Provisionnumber,
                PaymentAmount = reservation.Paymentamount.ToFloatNullAvailable(),
                AlertErrorCode = reservation.Alerterrorcode,
                LogResultNumber = reservation.Logresultnumber,
                LogErrorCode = reservation.Logerrorcode,
                CreditCardDiscountPercent = reservation.Creditcarddiscountpercent ?? 0,
                Score = reservation.Score ?? 0,
                CouponId = reservation.Couponid,
                CouponCode = reservation.Couponcode,
                CouponDiscountAmount = reservation.Coupondiscountamount.ToFloatNullSafe(),
                CouponDiscountValue = reservation.Coupondiscountvalue.ToFloatNullSafe(),
                CouponDiscountType = (CouponDiscountTypes)reservation.Coupondiscounttype.ToIntNullSafe(),
                CouponCurrencyType = (CurrencyTypes)((reservation.Couponcurrencyid ?? 1) - 1),
                APIPaidAmount = reservation.Apipaidamount.ToFloatNullSafe(),
                SpecialDailyPrice = reservation.Specialdailyprice.ToFloatNullAvailable() ?? -1,
                SpecialOneWayFee = reservation.Specialonewayfee.ToFloatNullAvailable() ?? -1,
                BaseRequestCurrencyType = reservation.Baserequestcurrencyid != null ? (CurrencyTypes)(reservation.Baserequestcurrencyid - 1) : (CurrencyTypes)(reservation.Dovizid - 1),
                BaseRequestCurrencyCode = (reservation.Baserequestcurrencyid != null ? (CurrencyTypes)(reservation.Baserequestcurrencyid - 1) : (CurrencyTypes)(reservation.Dovizid - 1)).ToString(),
                SIPPCode = reservation.Sippcode,
                VehicleCode = reservation.Vehiclecode,
                UseOnlyDefaultCurrency = reservation.Useonlydefaultcurrency ?? false,
                ExtraPricePayToDelivery = reservation.Extrapricepaytodelivery ?? false,
                OneWayFeePayToDelivery = reservation.Onewayfeepaytodelivery ?? false,
                IsSpecialWebSiteAgency = reservation.Isspecialwebsiteagency ?? false,
                MemberName = reservation.Membername,
                ReservationToken = !string.IsNullOrEmpty(reservation.Reservationtoken) ? JsonConvert.DeserializeObject<ReservationToken>(reservation.Reservationtoken) : null,
                CommercialAllowance = reservation.Commercialallowance ?? false,
                ReservationSourceId = reservation.Sourceid,
                InstallmentCount = reservation.Installmentcount ?? 0,
                TotalKMLimit = reservation.Totalkmlimit,
                DefaultCustomerMailAddress = reservation.Defaultcustomermailaddress,
                AgencyRentalProfitMarkup = reservation.Agencyrentalprofitmarkup.ToFloatNullSafe(),
                CancellationPenaltyRate = reservation.Cancellationpenaltyrate.ToIntNullSafe(),
                CancellationRefundedAmount = reservation.Cancellationrefundedamount.ToFloatNullSafe(),
                CancellationPenaltyHour = reservation.Cancellationpenaltyhour.ToIntNullSafe(),
                PaymentRefundSuccess = reservation.Paymentrefundsuccess,
                EncryptedReservationId = EncryptionHelper.Encrypt(reservation.Rezid.ToStringNullSafe()),
                RentalWorkingType = reservation.Rentalworkingtype != null ? (VendorWorkingTypes)reservation.Rentalworkingtype : VendorWorkingTypes.ProfitMarkup,
                AdditionalProductWorkingType = reservation.Additionalproductworkingtype != null ? (VendorWorkingTypes)reservation.Additionalproductworkingtype : VendorWorkingTypes.ProfitMarkup,
                OneWayFeeWorkingType = reservation.Onewayfeeworkingtype != null ? (VendorWorkingTypes)reservation.Onewayfeeworkingtype : VendorWorkingTypes.ProfitMarkup,
                ReservationTokenText = reservation.Reservationtokentext,
                AdvancedPaymentWithoutPayment = reservation.Advancedpaymentwithoutpayment ?? false,
                CancellationPenaltyAmount = reservation.Penaltyamount.ToFloatNullSafe(),
                PenaltyStatus = reservation.PenaltyStatus,
                RefundAmount = reservation.RefundAmount.ToDecimalNullSafe(),
                INVOICENUMBER = reservation.INVOICENUMBER.ToStringNullSafe(),
                AGENCYINVOICENUMBER = reservation.AGENCYINVOICENUMBER.ToStringNullSafe(),
                FriendlyReservationNumber = reservation.FriendlyReservationNumber.ToStringNullSafe(),
                ProvizyonNo = reservation.Provizyonno.ToStringNullSafe(),
                Bank = reservation.Bank.ToStringNullSafe(),
                CreditCardBank = reservation.CreditCardBank.ToStringNullSafe(),
                VendorDiscountValue = reservation.VendorDiscountValue.ToFloatNullSafe(),
                Canceller = reservation.Canceller.ToStringNullSafe(),
                AgencyReturnInvoiceNumber = reservation.AgencyReturnInvoiceNumber.ToStringNullSafe(),
                ReturnInvoiceNumber = reservation.ReturnInvoiceNumber.ToStringNullSafe(),
                CreditCardNumber = reservation.CreditCardNumber.ToStringNullSafe(),
                InstallmentCommissionAmount = reservation.InstallmentCommissionAmount.ToDecimalNullSafe(),
                //SurveyComment = reservation.SurveyComment,
                //DetailPageContentUrl = reservation.DetailPageContentUrl
                IsFullCredit = reservation.IsFullCredit.ToBoolNullSafe(),
                CouponName = reservation.CouponName.ToStringNullSafe(),
                PremiumExtraAmount = reservation.PremiumExtraAmount.ToDecimalNullSafe(),
                PaymentCode = reservation.PaymentCode.ToStringNullSafe(),
                VendorFlightPassRequired = reservation.VendorFlightPassRequired.ToBoolNullSafe(),
                ExternalCreditCardInfo = reservation.ExternalCreditCardInfo,
                PickupOfficeWorkingHours = reservation.PickupOfficeWorkingHours,
                ReturnOfficeWorkingHours = reservation.ReturnOfficeWorkingHours,
                ApiDeliveryTypeId = reservation.ApiDeliveryTypeId
            }
            : null;
        public static Reservation Map(this Rez reservation, List<ReservationExtra> reservationExtras)
        {
            return new Reservation
            {
                ReservationId = reservation.Rezid,
                ReservationNumber = reservation.Rezno,
                APIReservationNumber = reservation.Apireservationnumber,
                AgencyReservationReference = reservation.Agencyreservationreference,
                MemberId = reservation.Uyeid ?? 0,
                VendorType = (VendorTypes)reservation.Vendortype,
                AgencyId = reservation.Agencyid ?? 0,
                APIVendorId = reservation.Tedarikciid ?? 0,
                VendorId = reservation.Vendorid,
                VendorPhone = reservation.Vendorphone,
                VendorEmail = reservation.Vendoremail,
                VendorName = reservation.Vendorname,
                APIVendorName = reservation.Apivendorname,
                VehicleId = reservation.Aracid,
                ReservationDate = reservation.Tarih,
                PickupDate = reservation.Alistarihi,
                ReturnDate = reservation.Birakistarihi,
                PickupLocationId = reservation.Alisyerid,
                ReturnLocationId = reservation.Birakisyerid,
                CurrencyType = (CurrencyTypes)(reservation.Dovizid - 1),
                CurrencyCode = ((CurrencyTypes)(reservation.Dovizid - 1)).ToString(),
                LanguageType = (LanguageTypes)(reservation.Dilid - 1),
                RentalDuration = reservation.Kiralamasuresi,
                DailyPrice = Convert.ToSingle(reservation.Gunlukfiyat),
                ExtraPrice = Convert.ToSingle(reservation.Extratutar),
                OneWayFee = Convert.ToSingle(reservation.Tekyontutar),
                TotalPrice = Convert.ToSingle(reservation.Toplamtutar),
                PaidAmount = (PaymentTypes)reservation.Paymenttype != PaymentTypes.CommissionFree ? Convert.ToSingle(reservation.Odenentutar) : Convert.ToSingle(reservation.Toplamtutar),
                CustomerName = reservation.Musteriad,
                CustomerSurname = reservation.Musterisoyad,
                CustomerPhone = reservation.Musteritelefon,
                CustomerMail = reservation.Musterieposta,
                CustomerIdentityNumber = reservation.Musteritcpasaport,
                CustomerAddress = reservation.Musteriadres,
                CustomerTitle = reservation.Musteriunvan,
                CustomerTaxOffice = reservation.Musterivergidaire,
                CustomerTaxNumber = reservation.Musterivergino,
                CustomerArrivalFlightNumber = reservation.Musterigelisucusno,
                CustomerReturnFlightNumber = reservation.Musteridonusucusno,
                CustomerNote = reservation.Musterinot,
                BulletinActive = reservation.Musteriebulten ?? true,
                VehicleName = reservation.Aracadi,
                PickupLocationName = reservation.Alisyeri,
                ReturnLocationName = reservation.Birakisyeri,
                ExtraIds = reservation.Extraidlist,
                IpAddress = reservation.Ip,
                PaymentType = (PaymentTypes)reservation.Paymenttype,
                SkyScannerRedirectId = reservation.Skyscannerredirectid,
                ReservationStatusType = (ReservationStatusTypes)(reservation.Resstatusid * -1 - 1),
                ReservationStatusNote = reservation.Resstatusnote,
                PdfUrl = reservation.Pdf,
                ReservationPostedToAPI = reservation.Servisegonderildi,
                APIReservationSuccessfully = reservation.Apireservationsuccessfully,
                APIDailyPrice = reservation.Apidailyprice.ToFloatNullSafe(),
                APIExtraAmount = reservation.Apiextraamount.ToFloatNullSafe(),
                APIOneWayFee = reservation.Apionewayfee.ToFloatNullSafe(),
                APITotalAmount = reservation.Apitotalamount.ToFloatNullSafe(),
                AgencyCommission = reservation.Agencycommission.ToFloatNullSafe(),
                ProfitMarkup = reservation.Profitmarkup.ToFloatNullSafe(),
                StatusName = reservation.Statusname,
                AgencyName = reservation.Agencyname,
                APIReservationCancel = reservation.Apireservationcancel ?? false,
                ServiceCharge = reservation.Servicecharge.ToFloatNullSafe(),
                ServiceChargeCurrencyType = (CurrencyTypes)(reservation.Servicechargecurrencyid - 1),
                APIVendorPickupAddress = reservation.Apivendoraddress,
                APIVendorReturnAddress = reservation.Apivendorreturnaddress,
                APIVendorPickupPhone = reservation.Apivendorphone,
                APIVendorReturnPhone = reservation.Apivendorreturnphone,
                IsCancelable = reservation.Iscancelable.ToBoolNullSafe(),
                DepositPrice = reservation.Depositprice.ToFloatNullAvailable(),
                VendorMinimumDriverAge = reservation.Vendormindriverage ?? 0,
                VendorMinimumDrivingLicenseAge = reservation.Vendormindrivinglicenseage ?? 0,
                SendReservationMail = reservation.Sendreservationmail ?? false,
                APIMessage = reservation.Apimessage,
                CustomerBirthday = reservation.Customerbirthday,
                DepartureInfo = reservation.Departureinfo,
                VehicleImageUrl = reservation.Vehicleimageurl,
                IsOffice = reservation.Isoffice ?? false,
                FuelType = reservation.Fueltype != null ? (FuelTypes)(reservation.Fueltype - 1) : FuelTypes.None,
                TransmissionType = reservation.Transmissiontype != null ? (TransmissionTypes)(reservation.Transmissiontype - 1) : TransmissionTypes.None,
                VehicleType = reservation.Vehicletype != null ? (VehicleTypes)(reservation.Vehicletype - 1) : VehicleTypes.None,
                VehicleCategoryType = reservation.Vehiclecategorytype != null ? (VehicleCategoryTypes)(reservation.Vehiclecategorytype - 1) : VehicleCategoryTypes.None,
                PassangerQuantityType = reservation.Passangerquantitytype != null ? (PassangerQuantityTypes)(reservation.Passangerquantitytype - 1) : PassangerQuantityTypes.None,
                BaggageQuantityType = reservation.Baggagequantitytype != null ? (BaggageQuantityTypes)(reservation.Baggagequantitytype - 1) : BaggageQuantityTypes.None,
                VendorLogo = reservation.Vendorlogo,
                APIReferenceCode = reservation.Apireferencecode,
                APIReferenceCode2 = reservation.Apireferencecode2,
                APIReferenceCode3 = reservation.Apireferencecode3,
                APICurrencyType = (CurrencyTypes)((reservation.Apicurrencyid ?? 1) - 1),
                APICurrencyCode = ((CurrencyTypes)((reservation.Apicurrencyid ?? 1) - 1)).ToString(),
                AgencyCode = reservation.Agencycode,
                ExchangeRate = reservation.Exchangerate.ToFloatNullSafe(),
                APIExchangeRate = reservation.Apiexchangerate.ToFloatNullSafe(),
                DepositCreditCardRequired = reservation.Depositcreditcardrequired ?? false,
                APIPhoneActive = reservation.Apiphoneactive ?? false,
                PaymentResultMessage = reservation.Paymentresultmessage,
                PaymentResultCode = reservation.Paymentresultcode,
                BankId = reservation.Bankid,
                ProvisionNumber = reservation.Provisionnumber,
                PaymentAmount = reservation.Paymentamount.ToFloatNullAvailable(),
                AlertErrorCode = reservation.Alerterrorcode,
                LogResultNumber = reservation.Logresultnumber,
                LogErrorCode = reservation.Logerrorcode,
                CreditCardDiscountPercent = reservation.Creditcarddiscountpercent ?? 0,
                Score = reservation.Score ?? 0,
                CouponId = reservation.Couponid,
                CouponCode = reservation.Couponcode,
                CouponDiscountAmount = reservation.Coupondiscountamount.ToFloatNullSafe(),
                CouponDiscountValue = reservation.Coupondiscountvalue.ToFloatNullSafe(),
                CouponDiscountType = (CouponDiscountTypes)reservation.Coupondiscounttype.ToIntNullSafe(),
                CouponCurrencyType = (CurrencyTypes)((reservation.Couponcurrencyid ?? 1) - 1),
                APIPaidAmount = reservation.Apipaidamount.ToFloatNullSafe(),
                SpecialDailyPrice = reservation.Specialdailyprice.ToFloatNullAvailable() ?? -1,
                SpecialOneWayFee = reservation.Specialonewayfee.ToFloatNullAvailable() ?? -1,
                BaseRequestCurrencyType = reservation.Baserequestcurrencyid != null ? (CurrencyTypes)(reservation.Baserequestcurrencyid - 1) : (CurrencyTypes)(reservation.Dovizid - 1),
                BaseRequestCurrencyCode = (reservation.Baserequestcurrencyid != null ? (CurrencyTypes)(reservation.Baserequestcurrencyid - 1) : (CurrencyTypes)(reservation.Dovizid - 1)).ToString(),
                SIPPCode = reservation.Sippcode,
                VehicleCode = reservation.Vehiclecode,
                UseOnlyDefaultCurrency = reservation.Useonlydefaultcurrency ?? false,
                ExtraPricePayToDelivery = reservation.Extrapricepaytodelivery ?? false,
                OneWayFeePayToDelivery = reservation.Onewayfeepaytodelivery ?? false,
                IsSpecialWebSiteAgency = reservation.Isspecialwebsiteagency ?? false,
                MemberName = reservation.Membername,
                ReservationToken = !string.IsNullOrEmpty(reservation.Reservationtoken) ? JsonConvert.DeserializeObject<ReservationToken>(reservation.Reservationtoken) : null,
                CommercialAllowance = reservation.Commercialallowance ?? false,
                ReservationSourceId = reservation.Sourceid,
                InstallmentCount = reservation.Installmentcount ?? 0,
                TotalKMLimit = reservation.Totalkmlimit,
                DefaultCustomerMailAddress = reservation.Defaultcustomermailaddress,
                AgencyRentalProfitMarkup = reservation.Agencyrentalprofitmarkup.ToFloatNullSafe(),
                CancellationPenaltyRate = reservation.Cancellationpenaltyrate.ToIntNullSafe(),
                CancellationRefundedAmount = reservation.Cancellationrefundedamount.ToFloatNullSafe(),
                CancellationPenaltyHour = reservation.Cancellationpenaltyhour.ToIntNullSafe(),
                PaymentRefundSuccess = reservation.Paymentrefundsuccess,
                EncryptedReservationId = EncryptionHelper.Encrypt(reservation.Rezid.ToStringNullSafe()),
                RentalWorkingType = reservation.Rentalworkingtype != null ? (VendorWorkingTypes)reservation.Rentalworkingtype : VendorWorkingTypes.ProfitMarkup,
                AdditionalProductWorkingType = reservation.Additionalproductworkingtype != null ? (VendorWorkingTypes)reservation.Additionalproductworkingtype : VendorWorkingTypes.ProfitMarkup,
                OneWayFeeWorkingType = reservation.Onewayfeeworkingtype != null ? (VendorWorkingTypes)reservation.Onewayfeeworkingtype : VendorWorkingTypes.ProfitMarkup,
                ReservationTokenText = reservation.Reservationtokentext,
                AdvancedPaymentWithoutPayment = reservation.Advancedpaymentwithoutpayment ?? false,
                CancellationPenaltyAmount = reservation.Penaltyamount.ToFloatNullSafe(),
                PenaltyStatus = reservation.PenaltyStatus,
                RefundAmount = reservation.RefundAmount.ToDecimalNullSafe(),
                INVOICENUMBER = reservation.INVOICENUMBER.ToStringNullSafe(),
                AGENCYINVOICENUMBER = reservation.AGENCYINVOICENUMBER.ToStringNullSafe(),
                FriendlyReservationNumber = reservation.FriendlyReservationNumber.ToStringNullSafe(),
                ProvizyonNo = reservation.Provizyonno.ToStringNullSafe(),
                Bank = reservation.Bank.ToStringNullSafe(),
                CreditCardBank = reservation.CreditCardBank.ToStringNullSafe(),
                VendorDiscountValue = reservation.VendorDiscountValue.ToFloatNullSafe(),
                Canceller = reservation.Canceller.ToStringNullSafe(),
                AgencyReturnInvoiceNumber = reservation.AgencyReturnInvoiceNumber.ToStringNullSafe(),
                ReturnInvoiceNumber = reservation.ReturnInvoiceNumber.ToStringNullSafe(),
                CreditCardNumber = reservation.CreditCardNumber.ToStringNullSafe(),
                InstallmentCommissionAmount = reservation.InstallmentCommissionAmount.ToDecimalNullSafe(),
                //SurveyComment = reservation.SurveyComment,
                //DetailPageContentUrl = reservation.DetailPageContentUrl
                IsFullCredit = reservation.IsFullCredit.ToBoolNullSafe(),
                CouponName = reservation.CouponName.ToStringNullSafe(),
                PremiumExtraAmount = reservation.PremiumExtraAmount.ToDecimalNullSafe(),
                PaymentCode = reservation.PaymentCode.ToStringNullSafe(),
                VendorFlightPassRequired = reservation.VendorFlightPassRequired.ToBoolNullSafe(),
                ExternalCreditCardInfo = reservation.ExternalCreditCardInfo,
                PickupOfficeWorkingHours = reservation.PickupOfficeWorkingHours,
                ReturnOfficeWorkingHours = reservation.ReturnOfficeWorkingHours,
                ApiDeliveryTypeId = reservation.ApiDeliveryTypeId,
                ReservationExtras = reservationExtras
            };
        }
        public static Reservation Map2(this Reservation reservation) =>
           reservation != null ? new Reservation
           {
               ReservationId = reservation.ReservationId,
               ReservationNumber = reservation.ReservationNumber,
               APIReservationNumber = reservation.APIReservationNumber,
               AgencyReservationReference = reservation.AgencyReservationReference,
               MemberId = reservation.MemberId,
               VendorType = reservation.VendorType,
               AgencyId = reservation.AgencyId,
               APIVendorId = reservation.APIVendorId,
               VendorId = reservation.VendorId,
               VendorPhone = reservation.VendorPhone,
               VendorEmail = reservation.VendorEmail,
               VendorName = reservation.VendorName,
               APIVendorName = reservation.APIVendorName,
               VehicleId = reservation.VehicleId,
               ReservationDate = reservation.ReservationDate,
               PickupDate = reservation.PickupDate,
               ReturnDate = reservation.ReturnDate,
               PickupLocationId = reservation.PickupLocationId,
               ReturnLocationId = reservation.ReturnLocationId,
               CurrencyType = reservation.CurrencyType,
               CurrencyCode = reservation.CurrencyCode,
               LanguageType = reservation.LanguageType,
               RentalDuration = reservation.RentalDuration,
               DailyPrice = reservation.DailyPrice,
               ExtraPrice = reservation.ExtraPrice,
               OneWayFee = reservation.OneWayFee,
               TotalPrice = reservation.TotalPrice,
               PaidAmount = reservation.PaidAmount,
               CustomerName = reservation.CustomerName,
               CustomerSurname = reservation.CustomerSurname,
               CustomerPhone = reservation.CustomerPhone,
               CustomerMail = reservation.CustomerMail,
               CustomerIdentityNumber = reservation.CustomerIdentityNumber,
               CustomerAddress = reservation.CustomerAddress,
               CustomerTitle = reservation.CustomerTitle,
               CustomerTaxOffice = reservation.CustomerTaxOffice,
               CustomerTaxNumber = reservation.CustomerTaxNumber,
               CustomerArrivalFlightNumber = reservation.CustomerArrivalFlightNumber,
               CustomerReturnFlightNumber = reservation.CustomerReturnFlightNumber,
               CustomerNote = reservation.CustomerNote,
               BulletinActive = reservation.BulletinActive,
               VehicleName = reservation.VehicleName,
               PickupLocationName = reservation.PickupLocationName,
               ReturnLocationName = reservation.ReturnLocationName,
               ExtraIds = reservation.ExtraIds,
               IpAddress = reservation.IpAddress,
               PaymentType = reservation.PaymentType,
               SkyScannerRedirectId = reservation.SkyScannerRedirectId,
               ReservationStatusType = reservation.ReservationStatusType,
               ReservationStatusNote = reservation.ReservationStatusNote,
               PdfUrl = reservation.PdfUrl,
               ReservationPostedToAPI = reservation.ReservationPostedToAPI,
               APIReservationSuccessfully = reservation.APIReservationSuccessfully,
               APIDailyPrice = reservation.APIDailyPrice,
               APIExtraAmount = reservation.APIExtraAmount,
               APIOneWayFee = reservation.APIOneWayFee,
               APITotalAmount = reservation.APITotalAmount,
               AgencyCommission = reservation.AgencyCommission,
               ProfitMarkup = reservation.ProfitMarkup,
               StatusName = reservation.StatusName,
               AgencyName = reservation.AgencyName,
               APIReservationCancel = reservation.APIReservationCancel,
               ServiceCharge = reservation.ServiceCharge,
               ServiceChargeCurrencyType = reservation.ServiceChargeCurrencyType,
               APIVendorPickupAddress = reservation.APIVendorPickupAddress,
               APIVendorReturnAddress = reservation.APIVendorReturnAddress,
               APIVendorPickupPhone = reservation.APIVendorPickupPhone,
               APIVendorReturnPhone = reservation.APIVendorReturnPhone,
               IsCancelable = reservation.IsCancelable,
               DepositPrice = reservation.DepositPrice,
               VendorMinimumDriverAge = reservation.VendorMinimumDriverAge,
               VendorMinimumDrivingLicenseAge = reservation.VendorMinimumDrivingLicenseAge,
               SendReservationMail = reservation.SendReservationMail,
               APIMessage = reservation.APIMessage,
               CustomerBirthday = reservation.CustomerBirthday,
               DepartureInfo = reservation.DepartureInfo,
               VehicleImageUrl = reservation.VehicleImageUrl,
               IsOffice = reservation.IsOffice,
               FuelType = reservation.FuelType,
               TransmissionType = reservation.TransmissionType,
               VehicleType = reservation.VehicleType,
               VehicleCategoryType = reservation.VehicleCategoryType,
               PassangerQuantityType = reservation.PassangerQuantityType,
               BaggageQuantityType = reservation.BaggageQuantityType,
               VendorLogo = reservation.VendorLogo,
               APIReferenceCode = reservation.APIReferenceCode,
               APIReferenceCode2 = reservation.APIReferenceCode2,
               APIReferenceCode3 = reservation.APIReferenceCode3,
               APICurrencyType = reservation.APICurrencyType,
               APICurrencyCode = reservation.APICurrencyCode,
               AgencyCode = reservation.AgencyCode,
               ExchangeRate = reservation.ExchangeRate,
               APIExchangeRate = reservation.APIExchangeRate,
               DepositCreditCardRequired = reservation.DepositCreditCardRequired,
               APIPhoneActive = reservation.APIPhoneActive,
               PaymentResultMessage = reservation.PaymentResultMessage,
               PaymentResultCode = reservation.PaymentResultCode,
               BankId = reservation.BankId,
               ProvisionNumber = reservation.ProvisionNumber,
               PaymentAmount = reservation.PaymentAmount,
               AlertErrorCode = reservation.AlertErrorCode,
               LogResultNumber = reservation.LogResultNumber,
               LogErrorCode = reservation.LogErrorCode,
               CreditCardDiscountPercent = reservation.CreditCardDiscountPercent,
               Score = reservation.Score,
               CouponId = reservation.CouponId,
               CouponCode = reservation.CouponCode,
               CouponDiscountAmount = reservation.CouponDiscountAmount,
               CouponDiscountValue = reservation.CouponDiscountValue,
               CouponDiscountType = reservation.CouponDiscountType,
               CouponCurrencyType = reservation.CouponCurrencyType,
               APIPaidAmount = reservation.APIPaidAmount,
               SpecialDailyPrice = reservation.SpecialDailyPrice,
               SpecialOneWayFee = reservation.SpecialOneWayFee,
               BaseRequestCurrencyType = reservation.BaseRequestCurrencyType,
               BaseRequestCurrencyCode = reservation.BaseRequestCurrencyCode,
               SIPPCode = reservation.SIPPCode,
               VehicleCode = reservation.VehicleCode,
               UseOnlyDefaultCurrency = reservation.UseOnlyDefaultCurrency,
               ExtraPricePayToDelivery = reservation.ExtraPricePayToDelivery,
               OneWayFeePayToDelivery = reservation.OneWayFeePayToDelivery,
               IsSpecialWebSiteAgency = reservation.IsSpecialWebSiteAgency,
               MemberName = reservation.MemberName,
               ReservationToken = reservation.ReservationToken,
               CommercialAllowance = reservation.CommercialAllowance,
               ReservationSourceId = reservation.ReservationSourceId,
               InstallmentCount = reservation.InstallmentCount,
               TotalKMLimit = reservation.TotalKMLimit,
               DefaultCustomerMailAddress = reservation.DefaultCustomerMailAddress,
               AgencyRentalProfitMarkup = reservation.AgencyRentalProfitMarkup,
               CancellationPenaltyRate = reservation.CancellationPenaltyRate,
               CancellationRefundedAmount = reservation.CancellationRefundedAmount,
               CancellationPenaltyHour = reservation.CancellationPenaltyHour,
               PaymentRefundSuccess = reservation.PaymentRefundSuccess,
               EncryptedReservationId = reservation.EncryptedReservationId,
               RentalWorkingType = reservation.RentalWorkingType,
               AdditionalProductWorkingType = reservation.AdditionalProductWorkingType,
               OneWayFeeWorkingType = reservation.OneWayFeeWorkingType,
               ReservationTokenText = reservation.ReservationTokenText,
               AdvancedPaymentWithoutPayment = reservation.AdvancedPaymentWithoutPayment,
               CancellationPenaltyAmount = reservation.CancellationPenaltyAmount,
               PenaltyStatus = reservation.PenaltyStatus,
               RefundAmount = reservation.RefundAmount,
               INVOICENUMBER = reservation.INVOICENUMBER,
               AGENCYINVOICENUMBER = reservation.AGENCYINVOICENUMBER,
               FriendlyReservationNumber = reservation.FriendlyReservationNumber,
               ProvizyonNo = reservation.ProvizyonNo,
               Bank = reservation.Bank,
               CreditCardBank = reservation.CreditCardBank,
               VendorDiscountValue = reservation.VendorDiscountValue,
               Canceller = reservation.Canceller,
               AgencyReturnInvoiceNumber = reservation.AgencyReturnInvoiceNumber,
               ReturnInvoiceNumber = reservation.ReturnInvoiceNumber,
               CreditCardNumber = reservation.CreditCardNumber,
               InstallmentCommissionAmount = reservation.InstallmentCommissionAmount,
               DetailPageContentUrl = reservation.DetailPageContentUrl,
               IsFullCredit = reservation.IsFullCredit,
               CouponName = reservation.CouponName,
               PremiumExtraAmount = reservation.PremiumExtraAmount,
               PaymentCode = reservation.PaymentCode,
               VendorFlightPassRequired = reservation.VendorFlightPassRequired,
               Additions = reservation.Additions,
               CityOfPickupLocation = reservation.CityOfPickupLocation,
               CityOfReturnLocation = reservation.CityOfReturnLocation,
               VehicleBrandName = reservation.VehicleBrandName,
               VehicleModelName = reservation.VehicleModelName,
               VehicleDescription = reservation.VehicleDescription,
               ReservationExtras = reservation.ReservationExtras,
               FuelTypeName = reservation.FuelTypeName,
               TransmissionTypeName = reservation.TransmissionTypeName,
               VehicleTypeName = reservation.VehicleTypeName,
               VehicleCategoryTypeName = reservation.VehicleCategoryTypeName,
               ReservationSourceName = reservation.ReservationSourceName,
               VendorScore = reservation.VendorScore,
               CommentCount = reservation.CommentCount,
               ReservationStatusHistories = reservation.ReservationStatusHistories,
               PassangerQuantityTypeName = reservation.PassangerQuantityTypeName,
               BaggageQuantityTypeName = reservation.BaggageQuantityTypeName,
               ExternalCreditCardInfo = reservation.ExternalCreditCardInfo,
               PickupOfficeWorkingHours = reservation.PickupOfficeWorkingHours,
               ReturnOfficeWorkingHours = reservation.ReturnOfficeWorkingHours,
               ApiDeliveryTypeId = reservation.ApiDeliveryTypeId
           }
           : null;
        public static List<Reservation> Map(this List<Rez> reservations)
        {
            var _reservations = new List<Reservation>();

            if (reservations != null && reservations.Count != 0)
                foreach (var reservation in reservations)
                    _reservations.Add(reservation.Map());

            return _reservations;
        }
        public static Reservation ResMap(this Reservation reservations)
        {
            return reservations.Map2();
        }

        public static Rez Map(this Reservation reservation) =>
            reservation != null ? new Rez
            {
                Rezid = reservation.ReservationId,
                Rezno = reservation.ReservationNumber,
                Apireservationnumber = reservation.APIReservationNumber,
                Agencyreservationreference = reservation.AgencyReservationReference,
                Uyeid = reservation.MemberId,
                Vendortype = (int)reservation.VendorType,
                Agencyid = reservation.AgencyId,
                Tedarikciid = reservation.APIVendorId,
                Vendorid = reservation.VendorId,
                Vendorphone = reservation.VendorPhone,
                Vendoremail = reservation.VendorEmail,
                Vendorname = reservation.VendorName,
                Apivendorname = reservation.APIVendorName,
                Aracid = reservation.VehicleId,
                Tarih = reservation.ReservationDate,
                Alistarihi = reservation.PickupDate,
                Birakistarihi = reservation.ReturnDate,
                Alisyerid = reservation.PickupLocationId,
                Dovizid = ((int)reservation.CurrencyType) + 1,
                Dilid = ((int)reservation.LanguageType) + 1,
                Kiralamasuresi = reservation.RentalDuration,
                Gunlukfiyat = reservation.DailyPrice.ToDecimalNullSafe(),
                Extratutar = reservation.ExtraPrice.ToDecimalNullSafe(),
                Tekyontutar = reservation.OneWayFee.ToDecimalNullSafe(),
                Toplamtutar = reservation.TotalPrice.ToDecimalNullSafe(),
                Odenentutar = reservation.PaymentType != PaymentTypes.CommissionFree ? reservation.PaidAmount.ToDecimalNullSafe() : reservation.TotalPrice.ToDecimalNullSafe(),
                Musteriad = reservation.CustomerName,
                Musterisoyad = reservation.CustomerSurname,
                Musteritelefon = reservation.CustomerPhone,
                Musterieposta = reservation.CustomerMail,
                Musteritcpasaport = reservation.CustomerIdentityNumber,
                Musteriadres = reservation.CustomerAddress,
                Musteriunvan = reservation.CustomerTitle,
                Musterivergidaire = reservation.CustomerTaxOffice,
                Musterivergino = reservation.CustomerTaxNumber,
                Musterigelisucusno = reservation.CustomerArrivalFlightNumber,
                Musteridonusucusno = reservation.CustomerReturnFlightNumber,
                Musterinot = reservation.CustomerNote,
                Musteriebulten = reservation.BulletinActive,
                Aracadi = reservation.VehicleName,
                Alisyeri = reservation.PickupLocationName,
                Birakisyeri = reservation.ReturnLocationName,
                Extraidlist = reservation.ExtraIds,
                Ip = reservation.IpAddress,
                Paymenttype = (int)reservation.PaymentType,
                Skyscannerredirectid = reservation.SkyScannerRedirectId,
                Resstatusid = ((int)reservation.ReservationStatusType + 1) * -1,
                Resstatusnote = reservation.ReservationStatusNote,
                Pdf = reservation.PdfUrl,
                Servisegonderildi = reservation.ReservationPostedToAPI,
                Apireservationsuccessfully = reservation.APIReservationSuccessfully,
                Apidailyprice = reservation.APIDailyPrice.ToDecimalNullSafe(),
                Apiextraamount = reservation.APIExtraAmount.ToDecimalNullSafe(),
                Apionewayfee = reservation.APIOneWayFee.ToDecimalNullSafe(),
                Apitotalamount = reservation.APITotalAmount.ToDecimalNullSafe(),
                Agencycommission = reservation.AgencyCommission.ToDecimalNullSafe(),
                Profitmarkup = reservation.ProfitMarkup.ToDecimalNullSafe(),
                Statusname = reservation.StatusName,
                Agencyname = reservation.AgencyName,
                Apireservationcancel = reservation.APIReservationCancel,
                Servicecharge = reservation.ServiceCharge.ToDecimalNullSafe(),
                Servicechargecurrencyid = (int)reservation.ServiceChargeCurrencyType + 1,
                Apivendoraddress = reservation.APIVendorPickupAddress,
                Apivendorreturnaddress = reservation.APIVendorReturnAddress,
                Apivendorphone = reservation.APIVendorPickupPhone,
                Apivendorreturnphone = reservation.APIVendorReturnPhone,
                Iscancelable = reservation.IsCancelable,
                Depositprice = reservation.DepositPrice.ToDecimalNullAvailable(),
                Vendormindriverage = reservation.VendorMinimumDriverAge,
                Vendormindrivinglicenseage = reservation.VendorMinimumDrivingLicenseAge,
                Sendreservationmail = reservation.SendReservationMail,
                Apimessage = reservation.APIMessage,
                Customerbirthday = reservation.CustomerBirthday,
                Departureinfo = reservation.DepartureInfo,
                Vehicleimageurl = reservation.VehicleImageUrl,
                Isoffice = reservation.IsOffice,
                Fueltype = reservation.FuelType != FuelTypes.None ? (int)reservation.FuelType + 1 : -1,
                Transmissiontype = reservation.TransmissionType != TransmissionTypes.None ? (int)reservation.TransmissionType + 1 : -1,
                Vehicletype = reservation.VehicleType != VehicleTypes.None ? (int)reservation.VehicleType + 1 : -1,
                Vehiclecategorytype = reservation.VehicleCategoryType != VehicleCategoryTypes.None ? (int)reservation.VehicleCategoryType + 1 : -1,
                Passangerquantitytype = reservation.PassangerQuantityType != PassangerQuantityTypes.None ? (int)reservation.PassangerQuantityType + 1 : -1,
                Baggagequantitytype = reservation.BaggageQuantityType != BaggageQuantityTypes.None ? (int)reservation.BaggageQuantityType + 1 : -1,
                Vendorlogo = reservation.VendorLogo,
                Apireferencecode = reservation.APIReferenceCode,
                Apireferencecode2 = reservation.APIReferenceCode2,
                Apireferencecode3 = reservation.APIReferenceCode3,
                Apicurrencyid = (int)reservation.APICurrencyType + 1,
                Agencycode = reservation.AgencyCode,
                Exchangerate = reservation.ExchangeRate.ToDecimalNullSafe(),
                Apiexchangerate = reservation.APIExchangeRate.ToDecimalNullSafe(),
                Depositcreditcardrequired = reservation.DepositCreditCardRequired,
                Apiphoneactive = reservation.APIPhoneActive,
                Paymentresultmessage = reservation.PaymentResultMessage,
                Paymentresultcode = reservation.PaymentResultCode,
                Bankid = reservation.BankId,
                Provisionnumber = reservation.ProvisionNumber,
                Paymentamount = reservation.PaymentAmount.ToDecimalNullAvailable(),
                Alerterrorcode = reservation.AlertErrorCode,
                Logresultnumber = reservation.LogResultNumber,
                Logerrorcode = reservation.LogErrorCode,
                Creditcarddiscountpercent = reservation.CreditCardDiscountPercent,
                Score = reservation.Score,
                Couponid = reservation.CouponId,
                Couponcode = reservation.CouponCode,
                Coupondiscountamount = reservation.CouponDiscountAmount.ToDecimalNullSafe(),
                Coupondiscountvalue = reservation.CouponDiscountValue.ToDecimalNullSafe(),
                Coupondiscounttype = (int?)reservation.CouponDiscountType,
                Couponcurrencyid = reservation.CouponCurrencyType != null ? (int)(reservation.CouponCurrencyType + 1) : 1,
                Apipaidamount = reservation.APIPaidAmount.ToDecimalNullSafe(),
                Specialdailyprice = reservation.SpecialDailyPrice.ToDecimalNullSafe() != -1 ? reservation.SpecialDailyPrice.ToDecimalNullSafe() : -1,
                Specialonewayfee = reservation.SpecialOneWayFee.ToDecimalNullSafe() != -1 ? reservation.SpecialOneWayFee.ToDecimalNullSafe() : -1,
                Baserequestcurrencyid = (int)reservation.BaseRequestCurrencyType + 1,
                Sippcode = reservation.SIPPCode,
                Vehiclecode = reservation.VehicleCode,
                Useonlydefaultcurrency = reservation.UseOnlyDefaultCurrency,
                Extrapricepaytodelivery = reservation.ExtraPricePayToDelivery,
                Onewayfeepaytodelivery = reservation.OneWayFeePayToDelivery,
                Isspecialwebsiteagency = reservation.IsSpecialWebSiteAgency,
                Membername = reservation.MemberName,
                Reservationtoken = reservation.ReservationToken != null ? JsonConvert.SerializeObject(reservation.ReservationToken) : string.Empty,
                Commercialallowance = reservation.CommercialAllowance,
                Sourceid = reservation.ReservationSourceId,
                Installmentcount = reservation.InstallmentCount,
                Totalkmlimit = reservation.TotalKMLimit,
                Defaultcustomermailaddress = reservation.DefaultCustomerMailAddress,
                Agencyrentalprofitmarkup = reservation.AgencyRentalProfitMarkup.ToDecimalNullSafe(),
                Cancellationpenaltyrate = reservation.CancellationPenaltyRate,
                Cancellationrefundedamount = reservation.CancellationRefundedAmount.ToDecimalNullAvailable(),
                Cancellationpenaltyhour = reservation.CancellationPenaltyHour,
                Paymentrefundsuccess = reservation.PaymentRefundSuccess,
                Rentalworkingtype = (int)reservation.RentalWorkingType,
                Additionalproductworkingtype = (int)reservation.AdditionalProductWorkingType,
                Onewayfeeworkingtype = (int)reservation.OneWayFeeWorkingType,
                Reservationtokentext = reservation.ReservationTokenText,
                Advancedpaymentwithoutpayment = reservation.AdvancedPaymentWithoutPayment,
                Penaltyamount = reservation.CancellationPenaltyAmount.ToDecimalNullAvailable(),
                FriendlyReservationNumber = reservation.FriendlyReservationNumber.ToStringNullSafe(),
                IsFullCredit = reservation.IsFullCredit.ToBoolNullSafe(),
                ExternalCreditCardInfo = reservation.ExternalCreditCardInfo,
                PickupOfficeWorkingHours = reservation.PickupOfficeWorkingHours,
                ReturnOfficeWorkingHours = reservation.ReturnOfficeWorkingHours,
                ApiDeliveryTypeId = reservation.ApiDeliveryTypeId
            }
            : null;

        public static List<Rez> Map(this List<Reservation> reservations)
        {
            var _reservations = new List<Rez>();

            if (reservations != null && reservations.Count != 0)
                foreach (var reservation in reservations)
                    _reservations.Add(reservation.Map());

            return _reservations;
        }

        public static PostReservationRequest Map(this PostReservationRequestV2 postReservationRequestV2)
        {

            return new PostReservationRequest
            {
                AgencyId = postReservationRequestV2.Agency.AgencyId.ToIntNullSafe(),
                AgencyCode = postReservationRequestV2.Agency.AgencyCode,
                MemberId = postReservationRequestV2.MemberId,
                ExtraList = "",
                ReservationToken = postReservationRequestV2.ReservationToken.TrimNullSafe(),
                CustomerInstutionTypeNumber = postReservationRequestV2.Customer.InstutionTypeNumber ?? 0,
                CustomerName = postReservationRequestV2.Customer.Name.TrimNullSafe(),
                CustomerSurname = postReservationRequestV2.Customer.Surname.TrimNullSafe(),
                CustomerTelephone = postReservationRequestV2.Customer.PhoneNumber.TrimNullSafe(),
                CustomerEmail = postReservationRequestV2.Customer.Email.TrimNullSafe().ToLower(),
                CustomerPersonalNumber = postReservationRequestV2.Customer.PersonalNumber.TrimNullSafe(),
                CustomerNote = postReservationRequestV2.Customer.Note.TrimNullSafe(),
                CustomerExplanation = postReservationRequestV2.Customer.Explanation.TrimNullSafe(),
                CompanyTitle = postReservationRequestV2.Company?.Title.TrimNullSafe(),
                CustomerAddress = postReservationRequestV2.Customer.Address.TrimNullSafe(),
                CompanyTaxOffice = postReservationRequestV2.Company?.TaxOffice.TrimNullSafe(),
                CompanyTaxNumber = postReservationRequestV2.Company?.TaxNumber.TrimNullSafe(),
                FlightNumberArrival = postReservationRequestV2.FlightNumberArrival.TrimNullSafe(),
                FlightNumberDeparture = postReservationRequestV2.FlightNumberDeparture.TrimNullSafe(),
                CustomerIPAddress = postReservationRequestV2.Customer.IPAddress.TrimNullSafe(),
                PaidAmount = postReservationRequestV2.Pricing.PaidAmount.ToFloatNullSafe(),
                UpdateReservationNumber = postReservationRequestV2.UpdateReservationNumber.TrimNullSafe(),
                CreditCardPaymentTypeActive = postReservationRequestV2.Payment.CreditCardPaymentTypeActive ?? false,
                AdvancePaymentTypeActive = postReservationRequestV2.Payment.AdvancePaymentTypeActive ?? false,
                BankId = postReservationRequestV2.Payment.BankId ?? 0,
                BankVendorId = postReservationRequestV2.Payment.BankVendorId ?? 0,
                CreditCardHolder = postReservationRequestV2.Payment.CreditCardHolder.TrimNullSafe(),
                CreditCardNumber = postReservationRequestV2.Payment.CreditCardNumber.TrimNullSafe(),
                ExpiredYear = postReservationRequestV2.Payment.ExpiredYear,
                ExpiredMonth = postReservationRequestV2.Payment.ExpiredMonth,
                SecurityCode = postReservationRequestV2.Payment.SecurityCode.TrimNullSafe(),
                InstallmentCount = postReservationRequestV2.Payment.InstallmentCount ?? 0,
                ThreeDPaymentActive = postReservationRequestV2.Payment.ThreeDPaymentActive ?? false,
                ThreeDStatus = postReservationRequestV2.Payment.ThreeDStatus.TrimNullSafe(),
                ThreeDAuth = postReservationRequestV2.Payment.ThreeDAuth.TrimNullSafe(),
                ThreeDLevel = postReservationRequestV2.Payment.ThreeDLevel.TrimNullSafe(),
                ThreeDTxnId = postReservationRequestV2.Payment.ThreeDTxnId.TrimNullSafe(),
                ThreeDMd = postReservationRequestV2.Payment.ThreeDMd.TrimNullSafe(),
                ThreeDPnOrInfo = postReservationRequestV2.Payment.ThreeDPnOrInfo.TrimNullSafe(),
                SpecialDailyPrice = !string.IsNullOrEmpty(postReservationRequestV2.Pricing.SpecialDailyPrice.ToStringNullSafe()) ? postReservationRequestV2.Pricing.SpecialDailyPrice : -1,
                SpecialOneWayFee = !string.IsNullOrEmpty(postReservationRequestV2.Pricing.SpecialOneWayFee.ToStringNullSafe()) ? postReservationRequestV2.Pricing.SpecialOneWayFee : -1,
                IsCommissionFreePrice = postReservationRequestV2.Pricing.IsCommissionFreePrice ?? false,
                ExtraAmount = postReservationRequestV2.Pricing.ExtraAmount.ToFloatNullSafe(),
                SendReservationMail = postReservationRequestV2.SendReservationMail,
                DepartureInfo = postReservationRequestV2.DepartureInfo.TrimNullSafe(),
                CustomerBirthDay = postReservationRequestV2.Customer.BirthDay,
                VehicleImageURL = postReservationRequestV2.VehicleImageURL.TrimNullSafe(),
                AgencyReservationReference = postReservationRequestV2.AgencyReservationReference.TrimNullSafe(),
                PaymentType = postReservationRequestV2.Payment.PaymentType ?? PaymentTypes.PayToAgency,
                ExtraPricePayToDelivery = postReservationRequestV2.Payment.ExtraPricePayToDelivery,
                OneWayFeePayToDelivery = postReservationRequestV2.Payment.OneWayFeePayToDelivery,
                CouponCode = postReservationRequestV2.CouponCode,
                IsSpecialWebSiteAgency = postReservationRequestV2.IsSpecialWebSiteAgency,
                SkyscannerRedirectID = postReservationRequestV2.SkyscannerRedirectID.TrimNullSafe(),
                CommercialAllowance = postReservationRequestV2.CommercialAllowance,
                ReservationSourceId = postReservationRequestV2.ReservationSourceId,
                AdvancedPaymentWithoutPayment = postReservationRequestV2.Payment.AdvancedPaymentWithoutPayment,
                PaidAmountAfterUsingCouponCode = postReservationRequestV2.Pricing.PaidAmountAfterUsingCouponCode.ToFloatNullSafe(),
                HighAmountDiscountActive = postReservationRequestV2.HighAmountDiscountActive,
                FullCredit = postReservationRequestV2.FullCredit,
                Bank = postReservationRequestV2.Payment.Bank,
                BankAccountCode = postReservationRequestV2.Payment.BankAccountCode,
                BankAccountingCode = postReservationRequestV2.Payment.BankAccountingCode,
                Country = postReservationRequestV2.Country,
                City = postReservationRequestV2.City,
                District = postReservationRequestV2.District,
                CreditCardBank = postReservationRequestV2.Payment.CreditCardBank,
                ProvisionNumber = postReservationRequestV2.Payment.ProvisionNumber,
                OrderNumber = postReservationRequestV2.OrderNumber,
                ContactPermission = postReservationRequestV2.ContactPermission,
                InstallmentCommissionAmount = postReservationRequestV2.Pricing.InstallmentCommissionAmount.ToDecimalNullSafe(),
                LanguageCode = postReservationRequestV2.LanguageCode,
                PaymentCode = postReservationRequestV2.Payment.PaymentCode,
                RequestId = postReservationRequestV2.RequestId,
                ApiExtras = "",
                PostReservationRequestV2 = postReservationRequestV2,
                PickupDate = postReservationRequestV2.PickupDate,
                ReturnDate = postReservationRequestV2.ReturnDate,
                PickupTime = postReservationRequestV2.PickupTime,
                ReturnTime = postReservationRequestV2.ReturnTime,
                IsRetry = postReservationRequestV2.IsRetry,
                SendAgencyReservationNumber = postReservationRequestV2.SendAgencyReservationNumber
            };
        }
    }
}
