-- Pandora2 airport import preview/insert script
-- Generated at: 2026-06-12 16:44:44
-- Source: D:\kolayCAR\Kolaycar.Broker.Api\Scripts\..\airports.txt
--
-- Usage:
-- 1. Run as-is with @DoInsert = 0 and inspect the report result sets.
-- 2. Fill @CountryOverrides or @CityOverrides if needed.
-- 3. Set @DoInsert = 1 only after the preview looks correct.

SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @DoInsert bit = 0;
DECLARE @FallbackCityId int = 1;

DECLARE @LangIds TABLE (
    LangId int NOT NULL PRIMARY KEY
);

INSERT INTO @LangIds (LangId)
VALUES
(1),
(2),
(3);

DECLARE @CountryOverrides TABLE (
    Iata nvarchar(10) NOT NULL PRIMARY KEY,
    CountryCode nvarchar(2) NOT NULL
);

-- Same IATA can appear under multiple countries in Pandora2.
-- Example:
-- INSERT INTO @CountryOverrides (Iata, CountryCode) VALUES (N'GVA', N'CH');

DECLARE @CityOverrides TABLE (
    Iata nvarchar(10) NOT NULL PRIMARY KEY,
    CityId int NOT NULL
);

-- airports.txt has no separate city data.
-- The script first tries to match CITY by COUNTRYID + CITYNAME in LocationName.
-- Use this table for locations where automatic city matching is not correct.
-- Example:
-- INSERT INTO @CityOverrides (Iata, CityId) VALUES (N'AMS', 123);

DECLARE @Airports TABLE (
    SourceOrder int NOT NULL,
    CountryCode nvarchar(2) NOT NULL,
    Iata nvarchar(10) NOT NULL,
    LocationName nvarchar(200) NOT NULL
);

INSERT INTO @Airports (SourceOrder, CountryCode, Iata, LocationName)
VALUES
(1, N'DZ', N'AAE', N'Annaba Airport '),
(2, N'DK', N'AAL', N'Aalborg Airport'),
(3, N'DK', N'AAR', N'Aarhus Airport'),
(4, N'BR', N'AAX', N'Araxa Airport'),
(5, N'ES', N'ABC', N'Albacete Airport'),
(6, N'US', N'ABE', N'Allentown Airport'),
(7, N'US', N'ABI', N'Abilene Airport'),
(8, N'CI', N'ABJ', N'Abidjan Airport'),
(9, N'US', N'ABQ', N'Albuquerque Airport'),
(10, N'US', N'ABR', N'Aberdeen Airport'),
(11, N'SA', N'ABT', N'Al Bahah Domestic Airport'),
(12, N'AU', N'ABX', N'Albury Airport'),
(13, N'US', N'ABY', N'Albany Southwest Georgia Airport'),
(14, N'GB', N'ABZ', N'Aberdeen Airport'),
(15, N'MX', N'ACA', N'Acapulco Airport'),
(16, N'GH', N'ACC', N'Accra Kotoka Airport '),
(17, N'ES', N'ACE', N'Lanzarote Airport'),
(18, N'CH', N'ACH', N'Altenrhein Airport'),
(19, N'US', N'ACK', N'Nantucket Airport'),
(20, N'US', N'ACT', N'Waco Airport'),
(21, N'US', N'ACV', N'McKinleyville Arcata-Eureka Airport'),
(22, N'US', N'ACY', N'Atlantic City Airport'),
(23, N'TR', N'ADB', N'İzmir Adnan Menderes Havalimanı ( ADB )'),
(24, N'ET', N'ADD', N'Addis Ababa International Airport'),
(25, N'JO', N'ADJ', N'Amman Civil Airport'),
(26, N'AU', N'ADL', N'Adelaide Airport'),
(27, N'AR', N'AEP', N'Buenos Aires Jorge Newbery Airport'),
(28, N'RU', N'AER', N'Sochi Adler Airport '),
(29, N'NO', N'AES', N'Aalesund Airport'),
(30, N'US', N'AEX', N'Alexandria Airport'),
(31, N'IS', N'AEY', N'Akureyri Airport'),
(32, N'BR', N'AFL', N'Alta Floresta Airport'),
(33, N'MA', N'AGA', N'Agadir Airport'),
(34, N'FR', N'AGF', N'Agen Airport'),
(35, N'SE', N'AGH', N'Ängelholm Airport'),
(36, N'ES', N'AGP', N'Malaga Airport'),
(37, N'US', N'AGS', N'Augusta Airport'),
(38, N'MX', N'AGU', N'Aguascalientes Airport'),
(39, N'SA', N'AHB', N'Abha Airport'),
(40, N'US', N'AHN', N'Athens Ben Epps Airport'),
(41, N'IT', N'AHO', N'Alghero Airport'),
(42, N'MA', N'AHU', N'Al Hoceima Airport'),
(43, N'FR', N'AJA', N'Ajaccio Airport'),
(44, N'SE', N'AJR', N'Arvidsjaur Airport'),
(45, N'BR', N'AJU', N'Aracaju Airport'),
(46, N'JP', N'AKJ', N'Asahikawa Airport'),
(47, N'NZ', N'AKL', N'Auckland Airport'),
(48, N'KZ', N'ALA', N'Almaty Airport'),
(49, N'US', N'ALB', N'Albany Airport'),
(50, N'ES', N'ALC', N'Alicante Airport'),
(51, N'NO', N'ALF', N'Alta Airport'),
(52, N'DZ', N'ALG', N'Algiers Airport '),
(53, N'AU', N'ALH', N'Albany Airport '),
(54, N'US', N'ALO', N'Waterloo Airport'),
(55, N'US', N'ALS', N'Alamosa Airport'),
(56, N'US', N'ALW', N'Walla Walla Airport'),
(57, N'US', N'AMA', N'Amarillo Airport'),
(58, N'JO', N'AMM', N'Amman Queen Alia Airport'),
(59, N'NL', N'AMS', N'Amsterdam Schiphol Airport'),
(60, N'US', N'ANC', N'Anchorage Airport'),
(61, N'CL', N'ANF', N'Antofagasta Airport'),
(62, N'BE', N'ANR', N'Antwerp Airport'),
(63, N'AG', N'ANU', N'Saint Johns Airport'),
(64, N'NO', N'ANX', N'Andenes Airport'),
(65, N'TR', N'AOE', N'Eskişehir Havalimanı ( AOE )'),
(66, N'IT', N'AOI', N'Ancona Airport'),
(67, N'JP', N'AOJ', N'Aomori Airport'),
(68, N'GR', N'AOK', N'Karpathos Airport'),
(69, N'MY', N'AOR', N'Alor Setar Sultan Abdul Halim Airport'),
(70, N'IT', N'AOT', N'Saint Christophe Aosta Valley Airport'),
(71, N'US', N'APF', N'Naples Airport'),
(72, N'MZ', N'APL', N'Nampula Airport'),
(73, N'BR', N'AQA', N'Araraquara Airport'),
(74, N'SA', N'AQI', N'Al Qaisumah Airport'),
(75, N'JO', N'AQJ', N'Aqaba Airport'),
(76, N'PE', N'AQP', N'Arequipa Airport'),
(77, N'US', N'ARB', N'Ann Arbor Airport'),
(78, N'CL', N'ARI', N'Arica Airport'),
(79, N'TZ', N'ARK', N'Arusha Airport '),
(80, N'AU', N'ARM', N'Armidale Airport'),
(81, N'SE', N'ARN', N'Stockholm Arlanda Airport'),
(82, N'US', N'ART', N'Watertown Airport'),
(83, N'BR', N'ARU', N'Aracatuba Airport'),
(84, N'US', N'ASE', N'Aspen Airport'),
(85, N'JP', N'ASJ', N'Amami Airport'),
(86, N'AU', N'ASP', N'Alice Springs Airport'),
(87, N'TR', N'ASR', N'Kayseri Havalimanı ( ASR )'),
(88, N'PY', N'ASU', N'Asuncion Airport'),
(89, N'GR', N'ATH', N'Athens Airport'),
(90, N'US', N'ATL', N'Atlanta Airport'),
(91, N'BR', N'ATM', N'Altamira Airport'),
(92, N'MR', N'ATR', N'Atar Airport'),
(93, N'MT', N'ATT', N'Attard Downtown'),
(94, N'US', N'ATW', N'Appleton Airport'),
(95, N'AW', N'AUA', N'Oranjestad Airport'),
(96, N'US', N'AUG', N'Augusta Airport'),
(97, N'AE', N'AUH', N'Abu Dhabi Airport'),
(98, N'FR', N'AUR', N'Aurillac Airport'),
(99, N'US', N'AUS', N'Austin Airport'),
(100, N'BR', N'AUX', N'Araguaina Airport'),
(101, N'US', N'AVL', N'Asheville Airport'),
(102, N'FR', N'AVN', N'Avignon Airport'),
(103, N'US', N'AVP', N'Scranton Airport'),
(104, N'AU', N'AVV', N'Avalon Airport'),
(105, N'GR', N'AXD', N'Alexandroupolis Airport'),
(106, N'JP', N'AXT', N'Akita Airport'),
(107, N'AU', N'AYQ', N'Ayers Rock Airport'),
(108, N'TR', N'AYT', N'Antalya Havalimanı ( AYT )'),
(109, N'US', N'AZA', N'Mesa Phoenix-Mesa Gateway Airport'),
(110, N'IR', N'AZD', N'Yazd Airport'),
(111, N'US', N'AZO', N'Kalamazoo Airport'),
(112, N'DO', N'AZS', N'Sanchez International Airport '),
(113, N'BH', N'BAH', N'Manama Bahrain Airport'),
(114, N'CO', N'BAQ', N'Barranquilla Airport'),
(115, N'CL', N'BBA', N'Coyhaique Balmaceda Airport'),
(116, N'BW', N'BBK', N'Kasane Airport'),
(117, N'GP', N'BBR', N'Baillif Aerodrome'),
(118, N'RO', N'BBU', N'Bucharest Baneasa Airport'),
(119, N'RO', N'BCM', N'Bacau Airport'),
(120, N'ES', N'BCN', N'Barcelona Airport'),
(121, N'AU', N'BDB', N'Bundaberg Airport'),
(122, N'US', N'BDL', N'Windsor Locks Bradley Airport'),
(123, N'IT', N'BDS', N'Brindisi Airport'),
(124, N'NO', N'BDU', N'Bardufoss Airport '),
(125, N'RS', N'BEG', N'Belgrade Airport'),
(126, N'BR', N'BEL', N'Belem Airport'),
(127, N'DE', N'BER', N'Berlin Brandenburg Airport'),
(128, N'FR', N'BES', N'Brest Airport'),
(129, N'MZ', N'BEW', N'Beira Airport'),
(130, N'LB', N'BEY', N'Beirut Airport'),
(131, N'US', N'BFF', N'Scottsbluff Airport'),
(132, N'US', N'BFI', N'King County International Airport'),
(133, N'US', N'BFL', N'Bakersfield Airport'),
(134, N'ZA', N'BFN', N'Bloemfontein Airport'),
(135, N'GB', N'BFS', N'Belfast International Airport'),
(136, N'CO', N'BGA', N'Bucaramanga Airport'),
(137, N'CF', N'BGF', N'Bangui Airport '),
(138, N'BB', N'BGI', N'Barbados Airport'),
(139, N'US', N'BGM', N'Binghamton Airport'),
(140, N'NO', N'BGO', N'Bergen Airport'),
(141, N'US', N'BGR', N'Bangor Airport'),
(142, N'IT', N'BGY', N'Bergamo Airport'),
(143, N'US', N'BHB', N'Trenton Bar Harbor Airport'),
(144, N'GB', N'BHD', N'Belfast City Airport'),
(145, N'NZ', N'BHE', N'Blenheim Marlborough Airport'),
(146, N'SA', N'BHH', N'Bisha Domestic Airport'),
(147, N'AR', N'BHI', N'Bahia Blanca Airport'),
(148, N'US', N'BHM', N'Birmingham Airport'),
(149, N'AU', N'BHQ', N'Broken Hill Airport'),
(150, N'AU', N'BHS', N'Bathurst Airport'),
(151, N'GB', N'BHX', N'Birmingham Airport'),
(152, N'FR', N'BIA', N'Bastia Airport'),
(153, N'US', N'BIL', N'Billings Airport'),
(154, N'ES', N'BIO', N'Bilbao Airport'),
(155, N'FR', N'BIQ', N'Biarritz Airport'),
(156, N'US', N'BIS', N'Bismarck Airport'),
(157, N'IS', N'BIU', N'Bildudalur Airport'),
(158, N'US', N'BJI', N'Bemidji Airport'),
(159, N'GM', N'BJL', N'Banjul Airport'),
(160, N'TR', N'BJV', N'Bodrum Muğla-Milas Havalimanı ( BJV )'),
(161, N'MX', N'BJX', N'Leon Guanajuato Airport'),
(162, N'ES', N'BJZ', N'Badajoz Airport'),
(163, N'US', N'BKG', N'Branson Airport'),
(164, N'MY', N'BKI', N'Kota Kinabalu Airport'),
(165, N'TH', N'BKK', N'Bangkok Suvarnabhumi Airport'),
(166, N'US', N'BKW', N'Beaver Raleigh County Memorial Airport'),
(167, N'VE', N'BLA', N'Barcelona Airport'),
(168, N'PA', N'BLB', N'Panama City Pacifico Airport'),
(169, N'US', N'BLF', N'Bluefield Mercer Country Airport'),
(170, N'US', N'BLI', N'Bellingham Airport'),
(171, N'GB', N'BLK', N'Blackpool International Airport '),
(172, N'DK', N'BLL', N'Billund Airport'),
(173, N'IT', N'BLQ', N'Bologna Airport'),
(174, N'SE', N'BMA', N'Stockholm Bromma Airport'),
(175, N'AU', N'BME', N'Broome Airport'),
(176, N'US', N'BMI', N'Bloomington Airport'),
(177, N'US', N'BNA', N'Nashville Airport'),
(178, N'IR', N'BND', N'Bandar Abbas Airport'),
(179, N'AU', N'BNE', N'Brisbane Airport'),
(180, N'NG', N'BNI', N'Benin Airport '),
(181, N'AU', N'BNK', N'Ballina Airport'),
(182, N'US', N'BNW', N'Harrison Boone County Airport'),
(183, N'BA', N'BNX', N'Banja Luka Airport'),
(184, N'FR', N'BOD', N'Bordeaux Airport'),
(185, N'CO', N'BOG', N'Bogota Airport'),
(186, N'GB', N'BOH', N'Bournemouth Airport'),
(187, N'US', N'BOI', N'Boise Airport'),
(188, N'BG', N'BOJ', N'Burgas Airport'),
(189, N'BQ', N'BON', N'Kralendijk Flamingo International Airport'),
(190, N'NO', N'BOO', N'Bodo Airport'),
(191, N'US', N'BOS', N'Boston Logan Airport'),
(192, N'BR', N'BPG', N'Barra do Garcas Airport'),
(193, N'BR', N'BPS', N'Porto Seguro Airport'),
(194, N'AU', N'BQB', N'Busselton Airport '),
(195, N'US', N'BQK', N'Brunswick Airport'),
(196, N'PR', N'BQN', N'Aguadilla Airport'),
(197, N'BR', N'BRA', N'Barreiras Airport'),
(198, N'AR', N'BRC', N'Bariloche Airport'),
(199, N'US', N'BRD', N'Brainerd Airport'),
(200, N'DE', N'BRE', N'Bremen Airport'),
(201, N'IT', N'BRI', N'Bari Airport'),
(202, N'CH', N'BRN', N'Bern Airport'),
(203, N'US', N'BRO', N'Brownsville Airport'),
(204, N'CZ', N'BRQ', N'Brno Airport'),
(205, N'GB', N'BRS', N'Bristol Airport'),
(206, N'BE', N'BRU', N'Brussels Airport'),
(207, N'BR', N'BSB', N'Brasilia Airport'),
(208, N'CH', N'BSL', N'Basel Airport'),
(209, N'US', N'BTM', N'Butte Airport'),
(210, N'US', N'BTR', N'Baton Rouge Airport'),
(211, N'SK', N'BTS', N'Bratislava Airport'),
(212, N'US', N'BTV', N'Burlington Airport'),
(213, N'HU', N'BUD', N'Budapest Airport'),
(214, N'US', N'BUF', N'Buffalo Airport'),
(215, N'ZW', N'BUQ', N'Bulawayo Airport'),
(216, N'US', N'BUR', N'Burbank Airport'),
(217, N'GE', N'BUS', N'Batumi International Airport'),
(218, N'FR', N'BVA', N'Beauvais Airport'),
(219, N'BR', N'BVB', N'Boa Vista Airport'),
(220, N'FR', N'BVE', N'Brive-la-Gaillarde Airport'),
(221, N'BR', N'BVH', N'Vilhena Airport'),
(222, N'US', N'BWI', N'Baltimore Airport'),
(223, N'AU', N'BWT', N'Wynyard Burnie Airport'),
(224, N'AU', N'BXG', N'Bendigo Airport '),
(225, N'BR', N'BYO', N'Bonito Airport'),
(226, N'BZ', N'BZE', N'Belize City International Airport'),
(227, N'PL', N'BZG', N'Bydgoszcz Airport'),
(228, N'US', N'BZN', N'Bozeman Airport'),
(229, N'IT', N'BZO', N'Bolzano Airport'),
(230, N'FR', N'BZR', N'Beziers Airport'),
(231, N'BR', N'CAC', N'Cascavel Airport'),
(232, N'US', N'CAE', N'Columbia Metropolitan Airport'),
(233, N'IT', N'CAG', N'Cagliari Airport'),
(234, N'EG', N'CAI', N'Cairo Airport'),
(235, N'US', N'CAK', N'Akron-Canton Airport'),
(236, N'HT', N'CAP', N'Cap-Haïtien Airport '),
(237, N'BR', N'CAW', N'Campos dos Goytacazes Airport'),
(238, N'GF', N'CAY', N'Cayenne Airport'),
(239, N'AU', N'CAZ', N'Cobar Airport'),
(240, N'BO', N'CBB', N'Cochabamba Airport'),
(241, N'AU', N'CBR', N'Canberra Airport'),
(242, N'US', N'CBX', N'San Diego Cross Border Express Airport '),
(243, N'FR', N'CCF', N'Carcassonne Airport'),
(244, N'CL', N'CCP', N'Concepcion Airport'),
(245, N'US', N'CCR', N'Concord Buchanan Airport'),
(246, N'VE', N'CCS', N'Caracas Airport'),
(247, N'FR', N'CDG', N'Paris Charles de Gaulle Airport'),
(248, N'ES', N'CDT', N'Castellon Airport'),
(249, N'PH', N'CEB', N'Cebu Airport'),
(250, N'AU', N'CED', N'Ceduna Airport'),
(251, N'TH', N'CEI', N'Chiang Rai Airport'),
(252, N'MX', N'CEN', N'Ciudad Obregon Airport'),
(253, N'FR', N'CEQ', N'Cannes Airport'),
(254, N'US', N'CEZ', N'Cortez Airport'),
(255, N'BR', N'CFB', N'Cabo Frio Airport'),
(256, N'FR', N'CFE', N'Clermont-Ferrand Airport'),
(257, N'IE', N'CFN', N'Donegal Airport'),
(258, N'FR', N'CFR', N'Caen Airport'),
(259, N'AU', N'CFS', N'Coffs Harbour Airport'),
(260, N'GR', N'CFU', N'Corfu Airport'),
(261, N'BR', N'CGB', N'Varzea Grande Airport'),
(262, N'BR', N'CGH', N'Sao Paulo Congonhas Airport'),
(263, N'DE', N'CGN', N'Cologne Bonn Airport'),
(264, N'CN', N'CGO', N'Zhengzhou Airport'),
(265, N'BR', N'CGR', N'Campo Grande Airport'),
(266, N'PH', N'CGY', N'Cagayan de Oro Airport'),
(267, N'US', N'CHA', N'Chattanooga Airport'),
(268, N'NZ', N'CHC', N'Christchurch Airport'),
(269, N'US', N'CHO', N'Charlottesville Airport'),
(270, N'GR', N'CHQ', N'Chania Airport'),
(271, N'US', N'CHS', N'Charleston Airport'),
(272, N'PA', N'CHX', N'Changuinola Capitan Manuel Niño Airport '),
(273, N'IT', N'CIA', N'Rome Ciampino Airport'),
(274, N'US', N'CIC', N'Chico Airport'),
(275, N'US', N'CID', N'Cedar Rapids Airport'),
(276, N'PE', N'CIX', N'Chiclayo Airport'),
(277, N'IT', N'CIY', N'Comiso Airport'),
(278, N'CL', N'CJC', N'Calama Airport'),
(279, N'MX', N'CJS', N'Ciudad Juarez Airport'),
(280, N'KR', N'CJU', N'Jeju Airport'),
(281, N'US', N'CKB', N'Bridgeport Airport'),
(282, N'BR', N'CKS', N'Parauapebas Airport'),
(283, N'US', N'CLE', N'Cleveland Airport'),
(284, N'RO', N'CLJ', N'Cluj-Napoca Airport'),
(285, N'US', N'CLL', N'College Station Airport'),
(286, N'CO', N'CLO', N'Cali Airport'),
(287, N'MX', N'CLQ', N'Colima Airport'),
(288, N'US', N'CLT', N'Charlotte Douglas Airport'),
(289, N'BR', N'CLV', N'Caldas Novas Airport'),
(290, N'FR', N'CLY', N'Calvi Saint Catherine Airport'),
(291, N'LK', N'CMB', N'Colombo Bandaranaike Airport'),
(292, N'MX', N'CME', N'Ciudad del Carmen Airport'),
(293, N'FR', N'CMF', N'Chambery Airport'),
(294, N'BR', N'CMG', N'Corumba Airport'),
(295, N'US', N'CMH', N'Columbus Airport'),
(296, N'US', N'CMI', N'Champaign Airport'),
(297, N'MA', N'CMN', N'Casablanca Airport'),
(298, N'US', N'CMX', N'Calumet Houghton Airport'),
(299, N'RO', N'CND', N'Constanta Airport'),
(300, N'BR', N'CNF', N'Belo Horizonte Confins Airport'),
(301, N'AR', N'CNQ', N'Corrientes Camba Punta Airport '),
(302, N'AU', N'CNS', N'Cairns Airport'),
(303, N'TH', N'CNX', N'Chiang Mai Airport'),
(304, N'US', N'CNY', N'Moab Airport'),
(305, N'US', N'COD', N'Cody Airport'),
(306, N'US', N'CON', N'Concord Airport'),
(307, N'BJ', N'COO', N'Cotonou Airport '),
(308, N'AR', N'COR', N'Cordoba Airport'),
(309, N'US', N'COS', N'Colorado Springs Airport'),
(310, N'US', N'COU', N'Columbia Airport'),
(311, N'TR', N'COV', N'Çukurova Havalimanı ( COV )'),
(312, N'AR', N'CPC', N'San Martin de Los Andes Airport'),
(313, N'AU', N'CPD', N'Coober Pedy Airport'),
(314, N'MX', N'CPE', N'Campeche Airport'),
(315, N'DK', N'CPH', N'Copenhagen Airport'),
(316, N'CL', N'CPO', N'Copiapo Airport'),
(317, N'US', N'CPR', N'Casper Airport'),
(318, N'ZA', N'CPT', N'Cape Town International Airport'),
(319, N'BR', N'CPV', N'Campina Grande Airport'),
(320, N'RO', N'CRA', N'Craiova Airport'),
(321, N'AR', N'CRD', N'Comodoro Rivadavia Airport'),
(322, N'PH', N'CRK', N'Angeles Clark Airport'),
(323, N'BE', N'CRL', N'Charleroi Airport'),
(324, N'US', N'CRP', N'Corpus Christi Airport'),
(325, N'IT', N'CRV', N'Crotone Airport '),
(326, N'US', N'CRW', N'Charleston Airport'),
(327, N'US', N'CSG', N'Columbus Airport'),
(328, N'IT', N'CTA', N'Catania Airport'),
(329, N'CO', N'CTG', N'Cartagena Airport'),
(330, N'AU', N'CTL', N'Charleville Airport '),
(331, N'MX', N'CTM', N'Chetumal Airport'),
(332, N'JP', N'CTS', N'Sapporo Chitose Airport'),
(333, N'EC', N'CUE', N'Cuenca Airport'),
(334, N'IT', N'CUF', N'Cuneo Airport'),
(335, N'MX', N'CUL', N'Culiacan Airport'),
(336, N'MX', N'CUN', N'Cancun Airport'),
(337, N'CW', N'CUR', N'Willemstad Curacao Airport'),
(338, N'MX', N'CUU', N'Chihuahua Airport'),
(339, N'US', N'CVG', N'Cincinnati Airport'),
(340, N'AU', N'CVQ', N'Carnarvon Airport '),
(341, N'US', N'CWA', N'Mosinee Airport'),
(342, N'BR', N'CWB', N'Curitiba Airport'),
(343, N'GB', N'CWL', N'Cardiff Airport'),
(344, N'BR', N'CXJ', N'Caxias do Sul Airport'),
(345, N'US', N'CYS', N'Cheyenne Airport'),
(346, N'MX', N'CZM', N'Cozumel Airport'),
(347, N'US', N'DAB', N'Daytona Beach Airport'),
(348, N'US', N'DAL', N'Dallas Love Field Airport'),
(349, N'TZ', N'DAR', N'Dar es Salaam Airport'),
(350, N'PA', N'DAV', N'David Airport'),
(351, N'US', N'DAY', N'Dayton Airport'),
(352, N'AU', N'DBO', N'Dubbo Airport'),
(353, N'HR', N'DBV', N'Dubrovnik Airport'),
(354, N'US', N'DCA', N'Washington DC Reagan Airport'),
(355, N'FR', N'DCM', N'Castres Airport'),
(356, N'US', N'DDC', N'Dodge City Airport'),
(357, N'HU', N'DEB', N'Debrecen Airport'),
(358, N'US', N'DEN', N'Denver Airport'),
(359, N'US', N'DFW', N'Dallas Fort Worth Airport'),
(360, N'AU', N'DGE', N'Mudgee Airport'),
(361, N'MX', N'DGO', N'Durango Guadalupe Victoria Airport'),
(362, N'US', N'DHN', N'Dothan Airport'),
(363, N'US', N'DIK', N'Dickinson Airport'),
(364, N'TN', N'DJE', N'Djerba Airport'),
(365, N'CM', N'DLA', N'Douala Airport '),
(366, N'FR', N'DLE', N'Tavaux Dole–Jura Airport'),
(367, N'US', N'DLH', N'Duluth Airport'),
(368, N'TR', N'DLM', N'Dalaman Havalimanı ( DLM )'),
(369, N'RU', N'DME', N'Moscow Domodedovo Airport'),
(370, N'TH', N'DMK', N'Bangkok Don Mueang Airport'),
(371, N'SA', N'DMM', N'Dammam King Fahd Airport'),
(372, N'UA', N'DNK', N'Dnepropetrovsk Airport'),
(373, N'FR', N'DNR', N'Dinard Saint Malo Airport'),
(374, N'TR', N'DNZ', N'Denizli Çardak Havalimanı ( DNZ )'),
(375, N'QA', N'DOH', N'Doha Airport'),
(376, N'BR', N'DOU', N'Dourados Airport'),
(377, N'AU', N'DPO', N'Devonport Airport'),
(378, N'OM', N'DQM', N'Duqm Airport'),
(379, N'US', N'DRO', N'Durango Airport'),
(380, N'DE', N'DRS', N'Dresden Airport'),
(381, N'AU', N'DRW', N'Darwin Airport'),
(382, N'US', N'DSM', N'Des Moines Airport'),
(383, N'SN', N'DSS', N'Dakar Blaise Diagne Airport'),
(384, N'DE', N'DTM', N'Dortmund Airport'),
(385, N'US', N'DTW', N'Detroit Airport'),
(386, N'IE', N'DUB', N'Dublin Airport'),
(387, N'NZ', N'DUD', N'Dunedin Airport'),
(388, N'ZA', N'DUR', N'Durban King Shaka Airport'),
(389, N'DE', N'DUS', N'Düsseldorf International Airport'),
(390, N'PH', N'DVO', N'Davao Airport'),
(391, N'AE', N'DWC', N'Dubai Al Maktoum International Airport'),
(392, N'AE', N'DXB', N'Dubai International Airport'),
(393, N'YT', N'DZA', N'Pamandzi Dzaoudzi Airport'),
(394, N'ES', N'EAS', N'San Sebastian Airport'),
(395, N'US', N'EAT', N'Wenatchee Airport'),
(396, N'US', N'EAU', N'Eau Claire Chippewa Valley Airport'),
(397, N'IT', N'EBA', N'Marina di Campo Airport'),
(398, N'DK', N'EBJ', N'Esbjerg Airport'),
(399, N'IQ', N'EBL', N'Erbil Airport'),
(400, N'NI', N'ECI', N'Tola Costa Esmeralda Airport'),
(401, N'US', N'ECP', N'Panama City Northwest Florida Beaches Airport'),
(402, N'GB', N'EDI', N'Edinburgh Airport'),
(403, N'GR', N'EFL', N'Kefalonia Airport'),
(404, N'FR', N'EGC', N'Bergerac Airport'),
(405, N'US', N'EGE', N'Gypsum Eagle County Airport'),
(406, N'IS', N'EGS', N'Egilsstadir Airport'),
(407, N'NL', N'EIN', N'Eindhoven Airport'),
(408, N'VG', N'EIS', N'Tortola Terrance B. Lettsome Airport'),
(409, N'US', N'EKO', N'Elko Airport'),
(410, N'US', N'ELD', N'El Dorado Airport'),
(411, N'US', N'ELM', N'Elmira Corning Airport'),
(412, N'US', N'ELP', N'El Paso Airport'),
(413, N'SA', N'ELQ', N'Buraydah Airport'),
(414, N'ZA', N'ELS', N'East London Airport'),
(415, N'GB', N'EMA', N'Nottingham East Midlands Airport'),
(416, N'AU', N'EMD', N'Emerald Airport'),
(417, N'PH', N'ENI', N'El Nido International Airport '),
(418, N'US', N'ENW', N'Kenosha Aiport'),
(419, N'CO', N'EOH', N'Olaya Herrera Airport'),
(420, N'AU', N'EPR', N'Esperance Airport '),
(421, N'AR', N'EQS', N'Esquel Airport '),
(422, N'DE', N'ERF', N'Erfurt Airport'),
(423, N'US', N'ERI', N'Erie Airport'),
(424, N'NA', N'ERS', N'Windhoek Eros Airport'),
(425, N'TR', N'ERZ', N'Erzurum Havalimanı (ERZ)'),
(426, N'TR', N'ESB', N'Ankara Esenboğa Havalimanı ( ESB )'),
(427, N'US', N'ESC', N'Escanaba Airport'),
(428, N'MA', N'ESU', N'Essaouira Airport'),
(429, N'IL', N'ETM', N'Eilat Ramon Airport'),
(430, N'FR', N'ETZ', N'Metz Nancy Airport'),
(431, N'US', N'EUG', N'Eugene Airport'),
(432, N'MA', N'EUN', N'Laayoune Airport'),
(433, N'NO', N'EVE', N'Evenes Harstad Narvik Airport'),
(434, N'SE', N'EVG', N'Sveg Airport'),
(435, N'AM', N'EVN', N'Yerevan Zvartnots Airport'),
(436, N'US', N'EVV', N'Evansville Airport'),
(437, N'US', N'EWN', N'New Bern Airport'),
(438, N'US', N'EWR', N'Newark Airport'),
(439, N'AU', N'EXM', N'Exmouth Learmonth Airport'),
(440, N'GB', N'EXT', N'Exeter Airport'),
(441, N'US', N'EYW', N'Key West Airport'),
(442, N'AR', N'EZE', N'Buenos Aires Ezeiza Airport'),
(443, N'TR', N'EZS', N'Elazığ Havalimanı (EZS)'),
(444, N'FO', N'FAE', N'Sørvágur Vagar Airport '),
(445, N'US', N'FAI', N'Fairbanks Airport'),
(446, N'PT', N'FAO', N'Faro Airport'),
(447, N'US', N'FAR', N'Fargo Airport'),
(448, N'US', N'FAT', N'Fresno Airport'),
(449, N'US', N'FAY', N'Fayetteville Airport'),
(450, N'US', N'FCA', N'Kalispell Glacier Park Airport'),
(451, N'IT', N'FCO', N'Rome Fiumicino Airport'),
(452, N'NO', N'FDE', N'Forde Airport'),
(453, N'MQ', N'FDF', N'Fort de France Airport'),
(454, N'DE', N'FDH', N'Friedrichshafen Airport'),
(455, N'BR', N'FEC', N'Feira de Santana Airport'),
(456, N'MA', N'FEZ', N'Fes Airport'),
(457, N'DE', N'FKB', N'Karlsruhe Baden-Baden Airport'),
(458, N'JP', N'FKS', N'Ishikawa Airport '),
(459, N'US', N'FLD', N'Fond Du Lac Airport'),
(460, N'US', N'FLG', N'Flagstaff Airport'),
(461, N'US', N'FLL', N'Fort Lauderdale Airport'),
(462, N'BR', N'FLN', N'Florianopolis Airport'),
(463, N'US', N'FLO', N'Florence Airport'),
(464, N'IT', N'FLR', N'Florence Airport'),
(465, N'PT', N'FLW', N'Flores Airport'),
(466, N'BR', N'FMA', N'Formosa Airport '),
(467, N'DE', N'FMM', N'Memmingen Airport'),
(468, N'US', N'FMN', N'Farmington Four Corners Airport'),
(469, N'DE', N'FMO', N'Münster Osnabrück Airport'),
(470, N'PT', N'FNC', N'Funchal Airport'),
(471, N'FR', N'FNI', N'Nimes Airport'),
(472, N'US', N'FNL', N'Loveland Airport'),
(473, N'US', N'FNT', N'Flint Airport'),
(474, N'US', N'FOD', N'Fort Dodge Airport'),
(475, N'BR', N'FOR', N'Fortaleza Airport'),
(476, N'BS', N'FPO', N'Freeport Airport'),
(477, N'DE', N'FRA', N'Frankfurt Airport'),
(478, N'IT', N'FRL', N'Forli Airport'),
(479, N'GT', N'FRS', N'Flores Airport'),
(480, N'BW', N'FRW', N'Francistown Airport'),
(481, N'FR', N'FSC', N'Figari Airport'),
(482, N'US', N'FSD', N'Sioux Falls Airport'),
(483, N'US', N'FSM', N'Fort Smith Airport'),
(484, N'JP', N'FSZ', N'Shizuoka Airport'),
(485, N'AR', N'FTE', N'El Calafate Airport'),
(486, N'ES', N'FUE', N'Fuerteventura Airport'),
(487, N'JP', N'FUK', N'Fukuoka Airport'),
(488, N'US', N'FWA', N'Fort Wayne Airport'),
(489, N'JP', N'GAJ', N'Higashine Airport '),
(490, N'GB', N'GBA', N'Cotswold Airport'),
(491, N'AZ', N'GBB', N'Gabala Airport'),
(492, N'BW', N'GBE', N'Gaborone Airport'),
(493, N'US', N'GCC', N'Gillette Airport'),
(494, N'GB', N'GCI', N'Guernsey Airport'),
(495, N'ZA', N'GCJ', N'Midrand Grand Central Airport '),
(496, N'US', N'GCK', N'Garden City Airport'),
(497, N'KY', N'GCM', N'George Town Airport'),
(498, N'MX', N'GDL', N'Guadalajara Airport'),
(499, N'PL', N'GDN', N'Gdansk Airport'),
(500, N'US', N'GEG', N'Spokane Airport'),
(501, N'BR', N'GEL', N'Santo Angelo Airport'),
(502, N'GY', N'GEO', N'Georgetown Cheddi Jagan Airport'),
(503, N'PH', N'GES', N'General Santos Airport'),
(504, N'AU', N'GET', N'Geraldton Airport'),
(505, N'SE', N'GEV', N'Gallivare Airport'),
(506, N'AU', N'GFF', N'Griffith Airport'),
(507, N'US', N'GFK', N'Grand Forks Airport'),
(508, N'AU', N'GFN', N'Grafton Airport'),
(509, N'RO', N'GHV', N'Brasov Airport'),
(510, N'GI', N'GIB', N'Gibraltar Airport'),
(511, N'BR', N'GIG', N'Rio de Janeiro Galeao International Airport'),
(512, N'NZ', N'GIS', N'Gisborne Airport'),
(513, N'SA', N'GIZ', N'Jizan Airport'),
(514, N'US', N'GJT', N'Grand Junction Airport'),
(515, N'GB', N'GLA', N'Glasgow Airport'),
(516, N'AU', N'GLT', N'Gladstone Airport'),
(517, N'KR', N'GMP', N'Seoul Gimpo Airport'),
(518, N'ES', N'GMZ', N'La Gomera Airport'),
(519, N'FR', N'GNB', N'Grenoble Airport'),
(520, N'GD', N'GND', N'Saint George''s Grenada Airport'),
(521, N'US', N'GNV', N'Gainesville Airport'),
(522, N'TR', N'GNY', N'Şanlıurfa Havalimanı ( GNY )'),
(523, N'IT', N'GOA', N'Genoa Airport'),
(524, N'US', N'GON', N'Groton Airport'),
(525, N'SE', N'GOT', N'Gothenburg Landvetter Airport'),
(526, N'GR', N'GPA', N'Patras Araxos Airport'),
(527, N'US', N'GPT', N'Gulfport-Biloxi Airport'),
(528, N'US', N'GRB', N'Green Bay Airport'),
(529, N'US', N'GRI', N'Grand Island Airport'),
(530, N'ZA', N'GRJ', N'George Airport'),
(531, N'US', N'GRK', N'Killeen Fort Hood Regional Airport'),
(532, N'ES', N'GRO', N'Girona Airport'),
(533, N'NL', N'GRQ', N'Groningen Airport'),
(534, N'US', N'GRR', N'Grand Rapids Airport'),
(535, N'BR', N'GRU', N'Sao Paulo Guarulhos Airport'),
(536, N'ES', N'GRX', N'Granada Airport'),
(537, N'AT', N'GRZ', N'Graz Airport'),
(538, N'IR', N'GSM', N'Qeshm Airport'),
(539, N'US', N'GSO', N'Greensboro Greene County Airport'),
(540, N'US', N'GSO', N'Greensboro Piedmont Triad Airport'),
(541, N'US', N'GSP', N'Greenville Spartanburg Airport'),
(542, N'US', N'GTF', N'Great Falls Airport'),
(543, N'US', N'GTR', N'Columbus Golden Triangle Airport'),
(544, N'GT', N'GUA', N'Guatemala City Airport'),
(545, N'US', N'GUC', N'Gunnison Airport'),
(546, N'GU', N'GUM', N'Guam Airport'),
(547, N'CH', N'GVA', N'Geneva Airport'),
(548, N'FR', N'GVA', N'Geneva Airport'),
(549, N'BR', N'GVR', N'Governador Valadares Airport'),
(550, N'DE', N'GWT', N'Sylt Westerland Airport'),
(551, N'AZ', N'GYD', N'Baku Airport'),
(552, N'EC', N'GYE', N'Guayaquil Airport'),
(553, N'MX', N'GYM', N'Heroica Guaymas Gen Jose M Yanez Airport '),
(554, N'BR', N'GYN', N'Goiania Airport'),
(555, N'TR', N'GZT', N'Gaziantep Havalimanı ( GZT )'),
(556, N'SE', N'HAD', N'Halmstad Airport'),
(557, N'DE', N'HAJ', N'Hanover Airport'),
(558, N'CN', N'HAK', N'Haikou Meilan Airport'),
(559, N'DE', N'HAM', N'Hamburg Airport'),
(560, N'SA', N'HAS', N'Hail Airport'),
(561, N'NO', N'HAU', N'Haugesund Airport'),
(562, N'AU', N'HBA', N'Hobart Airport'),
(563, N'EG', N'HBE', N'Alexandria Airport'),
(564, N'DE', N'HDF', N'Heringsdorf Airport'),
(565, N'US', N'HDN', N'Hayden Airport'),
(566, N'ZA', N'HDS', N'Hoedspruit Airport'),
(567, N'TH', N'HDY', N'Hat Yai Airport'),
(568, N'FI', N'HEL', N'Helsinki Airport'),
(569, N'GR', N'HER', N'Heraklion Airport'),
(570, N'IS', N'HFN', N'Hofn Airport'),
(571, N'NO', N'HFT', N'Hammerfest Airport'),
(572, N'US', N'HHH', N'Hilton Head Airport'),
(573, N'DE', N'HHN', N'Frankfurt Hahn Airport'),
(574, N'TH', N'HHQ', N'Hua Hin Airport'),
(575, N'JP', N'HIJ', N'Hiroshima Airport'),
(576, N'US', N'HIO', N'Hillsboro Airport'),
(577, N'JP', N'HKD', N'Hakodate Airport'),
(578, N'NZ', N'HKK', N'Hokitika Airport'),
(579, N'TH', N'HKT', N'Phuket Airport'),
(580, N'ZA', N'HLA', N'Johannesburg Lanseria Airport'),
(581, N'US', N'HLN', N'Helena Airport'),
(582, N'NZ', N'HLZ', N'Hamilton Airport'),
(583, N'MX', N'HMO', N'Hermosillo Airport'),
(584, N'JP', N'HNA', N'Hanamaki Airport'),
(585, N'JP', N'HND', N'Tokyo Haneda Airport'),
(586, N'US', N'HNL', N'Honolulu Airport'),
(587, N'US', N'HOB', N'Hobbs Lea County Airport'),
(588, N'PT', N'HOR', N'Horta Airport'),
(589, N'US', N'HOT', N'Hot Springs Memorial Field Airport'),
(590, N'US', N'HOU', N'Houston Hobby Airport'),
(591, N'NO', N'HOV', N'Hovdebygda Orsta Volda Airport'),
(592, N'US', N'HPN', N'White Plains Westchester County Airport'),
(593, N'ZW', N'HRE', N'Harare Airport'),
(594, N'EG', N'HRG', N'Hurghada Airport'),
(595, N'UA', N'HRK', N'Kharkiv International Airport'),
(596, N'US', N'HRL', N'Harlingen Airport'),
(597, N'JP', N'HSG', N'Saga Airport'),
(598, N'US', N'HSV', N'Huntsville Airport'),
(599, N'US', N'HTO', N'East Hampton Airport'),
(600, N'US', N'HTS', N'Huntington Airport'),
(601, N'TR', N'HTY', N'Hatay Havalimanı ( HTY )'),
(602, N'MX', N'HUX', N'Huatulco Airport'),
(603, N'GB', N'HUY', N'Humberside Airport'),
(604, N'AU', N'HVB', N'Hervey Bay Airport'),
(605, N'US', N'HVN', N'New Haven Airport'),
(606, N'US', N'HYA', N'Barnstable Airport'),
(607, N'US', N'IAD', N'Washington DC Dulles Airport'),
(608, N'US', N'IAG', N'Niagara Falls Airport'),
(609, N'US', N'IAH', N'Houston George Bush Airport'),
(610, N'RO', N'IAS', N'Iasi Airport'),
(611, N'ES', N'IBZ', N'Ibiza Airport'),
(612, N'KR', N'ICN', N'Incheon Airport'),
(613, N'US', N'ICT', N'Wichita Airport'),
(614, N'US', N'IDA', N'Idaho Falls Airport'),
(615, N'PL', N'IEG', N'Zielona Gora Airport'),
(616, N'UA', N'IEV', N'Kiev Zhuliany Airport'),
(617, N'IS', N'IFJ', N'Isafjordur Airport'),
(618, N'IR', N'IFN', N'Isfahan Airport'),
(619, N'UA', N'IFO', N'Ivano-frankivsk Airport '),
(620, N'US', N'IFP', N'Bullhead City Airport'),
(621, N'AR', N'IGR', N'Puerto Iguazu Airport'),
(622, N'BR', N'IGU', N'Foz do Iguacu Airport'),
(623, N'IR', N'IKA', N'Tehran Imam Khomeini Airport'),
(624, N'US', N'ILM', N'Wilmington Airport'),
(625, N'BR', N'IMP', N'Imperatriz Airport'),
(626, N'US', N'IND', N'Indianapolis Airport'),
(627, N'RS', N'INI', N'Nis Airport'),
(628, N'AT', N'INN', N'Innsbruck Airport'),
(629, N'US', N'INT', N'Winston Salem Airport'),
(630, N'GB', N'INV', N'Inverness Airport'),
(631, N'GR', N'IOA', N'Ioannina Airport'),
(632, N'GB', N'IOM', N'Ronaldsway Airport'),
(633, N'BR', N'IOS', N'Ilheus Airport'),
(634, N'MY', N'IPH', N'Ipoh Airport'),
(635, N'US', N'IPL', N'El Centro Imperial County Airport'),
(636, N'BR', N'IPN', N'Ipatinga Airport'),
(637, N'US', N'IPT', N'Montoursville Airport'),
(638, N'CL', N'IQQ', N'Iquique Airport'),
(639, N'AR', N'IRJ', N'La Rioja Airport'),
(640, N'AU', N'ISA', N'Mount Isa Airport'),
(641, N'JP', N'ISG', N'Ishigaki Airport'),
(642, N'US', N'ISN', N'Williston Airport'),
(643, N'US', N'ISP', N'Islip Airport'),
(644, N'TR', N'IST', N'İstanbul Havalimanı ( IST )'),
(645, N'BR', N'ITB', N'Itaituba Airport'),
(646, N'US', N'ITH', N'Ithaca Airport'),
(647, N'JP', N'ITM', N'Osaka International Airport'),
(648, N'US', N'ITO', N'Hilo Airport'),
(649, N'NZ', N'IVC', N'Invercargill Airport'),
(650, N'FI', N'IVL', N'Ivalo Airport'),
(651, N'JP', N'IWJ', N'Masuda Iwami Airport'),
(652, N'JP', N'IWK', N'Yamaguchi Iwakuni Kintaikyo Airport'),
(653, N'US', N'IYK', N'Inyokern Airport'),
(654, N'BR', N'IZA', N'Juiz de Fora Zona da Mata Airport'),
(655, N'JP', N'IZO', N'Izumo Airport'),
(656, N'MX', N'IZT', N'Ixtepec Airport'),
(657, N'US', N'JAC', N'Jackson Hole Airport'),
(658, N'US', N'JAN', N'Jackson Airport'),
(659, N'US', N'JAX', N'Jacksonville Airport'),
(660, N'DO', N'JBQ', N'Santo Domingo La Isabela Airport'),
(661, N'US', N'JBR', N'Jonesboro Airport'),
(662, N'BR', N'JDO', N'Juazeiro do Norte Airport'),
(663, N'SA', N'JED', N'Jeddah King Abdulaziz Airport'),
(664, N'GB', N'JER', N'Jersey Airport'),
(665, N'US', N'JFK', N'New York City JFK Airport'),
(666, N'MY', N'JHB', N'Johor Bahru Senai Airport'),
(667, N'US', N'JHM', N'Lahaina Kapalua Airport'),
(668, N'DJ', N'JIB', N'Djibouti Airport'),
(669, N'GR', N'JIK', N'Ikaria Airport'),
(670, N'BR', N'JJG', N'Jaguaruna Airport'),
(671, N'CN', N'JJN', N'Quanzhou Jinjiang International Airport'),
(672, N'SE', N'JKG', N'Jonkoping Airport'),
(673, N'GR', N'JKH', N'Chios Airport'),
(674, N'US', N'JLN', N'Joplin Airport'),
(675, N'GR', N'JMK', N'Mykonos Airport'),
(676, N'ZA', N'JNB', N'Johannesburg O. R. Tambo Airport'),
(677, N'US', N'JNU', N'Juneau Airport'),
(678, N'GR', N'JNX', N'Naxos Airport'),
(679, N'FI', N'JOE', N'Joensuu Airport'),
(680, N'BR', N'JOI', N'Joinville Airport'),
(681, N'BR', N'JPA', N'Joao Pessoa Airport'),
(682, N'BR', N'JPR', N'Ji-Parana Airport'),
(683, N'TZ', N'JRO', N'Arusha-Moshi Kilimanjaro Airport'),
(684, N'GR', N'JSH', N'Sitia Airport'),
(685, N'GR', N'JSI', N'Skiathos Airport'),
(686, N'US', N'JST', N'Johnstown Airport'),
(687, N'GR', N'JSY', N'Syros Airport'),
(688, N'BR', N'JTC', N'Bauru-Arealva Airport'),
(689, N'GR', N'JTR', N'Santorini Airport'),
(690, N'GR', N'JTY', N'Astypalaia Airport'),
(691, N'AR', N'JUJ', N'San Salvador de Jujuy Airport'),
(692, N'US', N'JXN', N'Jackson Airport'),
(693, N'FI', N'JYV', N'Jyvaskyla Airport'),
(694, N'FI', N'KAJ', N'Kajaani Airport'),
(695, N'FI', N'KAO', N'Kuusamo Airport'),
(696, N'UA', N'KBP', N'Kiev Boryspil Airport'),
(697, N'MY', N'KBR', N'Kota Bharu Airport'),
(698, N'TH', N'KBV', N'Krabi Airport'),
(699, N'MY', N'KCH', N'Kuching International Airport'),
(700, N'JP', N'KCZ', N'Kochi Airport'),
(701, N'IS', N'KEF', N'Keflavik International Airport'),
(702, N'FI', N'KEM', N'Kemi-Tornio Airport'),
(703, N'AU', N'KGC', N'Kingscote Airport'),
(704, N'RU', N'KGD', N'Kaliningrad Khrabrovo Airport '),
(705, N'AU', N'KGI', N'Kalgoorlie Airport'),
(706, N'RW', N'KGL', N'Kigali Airport'),
(707, N'GR', N'KGS', N'Kos Airport'),
(708, N'UA', N'KHE', N'Kherson International Airport '),
(709, N'PK', N'KHI', N'Karachi Jinnah Airport'),
(710, N'SE', N'KID', N'Kristianstad Airport'),
(711, N'JP', N'KIJ', N'Niigata Airport'),
(712, N'ZA', N'KIM', N'Kimberley Airport'),
(713, N'JM', N'KIN', N'Kingston Norman Manley Airport'),
(714, N'IE', N'KIR', N'Kerry Airport'),
(715, N'GR', N'KIT', N'Kithira Airport'),
(716, N'JP', N'KIX', N'Osaka Kansai Airport'),
(717, N'RU', N'KJA', N'Krasnoyarsk Jemeljanowo International Airport '),
(718, N'TH', N'KKC', N'Khon Kaen Airport'),
(719, N'NZ', N'KKE', N'Kerikeri Airport'),
(720, N'JP', N'KKJ', N'Kitakyushu Airport'),
(721, N'NO', N'KKN', N'Kirkenes Airport'),
(722, N'UG', N'KLA', N'Kampala Entebbe Airport'),
(723, N'SE', N'KLR', N'Kalmar Airport'),
(724, N'AT', N'KLU', N'Klagenfurt Airport'),
(725, N'GR', N'KLX', N'Kalamata Airport'),
(726, N'CN', N'KMG', N'Kunming Changshui International Airport'),
(727, N'JP', N'KMI', N'Miyazaki Airport'),
(728, N'JP', N'KMJ', N'Kumamoto Airport'),
(729, N'JP', N'KMQ', N'Komatsu Airport'),
(730, N'AU', N'KNX', N'Kununurra Airport '),
(731, N'US', N'KOA', N'Kona Airport'),
(732, N'GB', N'KOI', N'Kirkwall Airport'),
(733, N'JP', N'KOJ', N'Kagoshima Airport'),
(734, N'FI', N'KOK', N'Kokkola Airport'),
(735, N'SE', N'KRF', N'Kramfors Airport '),
(736, N'PL', N'KRK', N'Krakow Airport'),
(737, N'SE', N'KRN', N'Kiruna Airport'),
(738, N'DK', N'KRP', N'Karup Airport'),
(739, N'NO', N'KRS', N'Kristiansand Airport'),
(740, N'SK', N'KSC', N'Kosice Airport'),
(741, N'SE', N'KSD', N'Karlstad Airport'),
(742, N'NO', N'KSU', N'Kristiansund Airport'),
(743, N'AU', N'KTA', N'Karratha Airport'),
(744, N'FI', N'KTT', N'Kittilä Airport'),
(745, N'PL', N'KTW', N'Katowice Pyrzowice Airport'),
(746, N'MY', N'KUA', N'Kuantan Airport'),
(747, N'CR', N'KUF', N'Samara Airport '),
(748, N'JP', N'KUH', N'Kushiro Airport'),
(749, N'MY', N'KUL', N'Kuala Lumpur International Airport'),
(750, N'JP', N'KUM', N'Yakushima Airport'),
(751, N'LT', N'KUN', N'Kaunas Airport'),
(752, N'FI', N'KUO', N'Kuopio Airport'),
(753, N'GE', N'KUT', N'Kutaisi Airport'),
(754, N'GR', N'KVA', N'Kavala Airport'),
(755, N'AZ', N'KVD', N'Ganja Airport'),
(756, N'RS', N'KVO', N'Kraljevo Morava Airport'),
(757, N'KW', N'KWI', N'Kuwait Airport'),
(758, N'KR', N'KWJ', N'Gwangju Airport'),
(759, N'TR', N'KYA', N'Konya Havalimanı ( KYA )'),
(760, N'TR', N'KZR', N'Kütahya Zafer Havalimanı ( KZR )'),
(761, N'AO', N'LAD', N'Luanda Airport'),
(762, N'BR', N'LAJ', N'Lages Airport'),
(763, N'US', N'LAM', N'Los Alamos Airport'),
(764, N'US', N'LAN', N'Lansing Airport'),
(765, N'MX', N'LAP', N'La Paz Airport'),
(766, N'US', N'LAR', N'Laramie Airport'),
(767, N'US', N'LAS', N'Las Vegas Airport'),
(768, N'US', N'LAW', N'Lawton Airport'),
(769, N'US', N'LAX', N'Los Angeles Airport'),
(770, N'GB', N'LBA', N'Leeds Bradford Airport'),
(771, N'US', N'LBB', N'Lubbock Airport'),
(772, N'US', N'LBE', N'Latrobe Airport'),
(773, N'US', N'LBF', N'North Platte Airport'),
(774, N'FR', N'LBG', N'Paris Le Bourget Airport'),
(775, N'US', N'LBL', N'Liberal Airport'),
(776, N'MY', N'LBU', N'Labuan Airport'),
(777, N'GA', N'LBV', N'Libreville Airport '),
(778, N'CY', N'LCA', N'Larnaca Airport'),
(779, N'HN', N'LCE', N'La Ceiba Goloson International Airport '),
(780, N'ES', N'LCG', N'A Coruna Airport'),
(781, N'US', N'LCH', N'Lake Charles Airport'),
(782, N'PL', N'LCJ', N'Lodz Airport'),
(783, N'GB', N'LCY', N'London City Airport'),
(784, N'BR', N'LDB', N'Londrina Airport'),
(785, N'FR', N'LDE', N'Tarbes Airport'),
(786, N'GB', N'LDY', N'Derry Airport'),
(787, N'AU', N'LEA', N'Learmonth Airport'),
(788, N'US', N'LEB', N'Lebanon Airport'),
(789, N'RU', N'LED', N'Saint Petersburg Pulkovo Airport'),
(790, N'ES', N'LEI', N'Almeria Airport'),
(791, N'DE', N'LEJ', N'Leipzig Halle Airport'),
(792, N'US', N'LEX', N'Lexington Airport'),
(793, N'US', N'LFT', N'Lafayette Airport'),
(794, N'TG', N'LFW', N'Lome Airport'),
(795, N'US', N'LGA', N'New York City LaGuardia Airport'),
(796, N'US', N'LGB', N'Long Beach Airport'),
(797, N'BE', N'LGG', N'Liege Airport'),
(798, N'MY', N'LGK', N'Langkawi International Airport'),
(799, N'GB', N'LGW', N'London Gatwick Airport'),
(800, N'PK', N'LHE', N'Lahore Allama Iqbal Airport'),
(801, N'BR', N'LHN', N'Linhares Airport'),
(802, N'GB', N'LHR', N'London Heathrow Airport'),
(803, N'FR', N'LIG', N'Limoges Airport'),
(804, N'US', N'LIH', N'Lihue Airport'),
(805, N'FR', N'LIL', N'Lille Airport'),
(806, N'PE', N'LIM', N'Lima Airport'),
(807, N'IT', N'LIN', N'Milan Linate Airport'),
(808, N'CR', N'LIR', N'Liberia Airport'),
(809, N'PT', N'LIS', N'Lisbon Airport'),
(810, N'US', N'LIT', N'Little Rock Airport'),
(811, N'SI', N'LJU', N'Ljubljana Airport'),
(812, N'NO', N'LKL', N'Lakselv Airport'),
(813, N'NO', N'LKN', N'Leknes Airport'),
(814, N'SE', N'LLA', N'Lulea Airport'),
(815, N'MW', N'LLW', N'Lilongwe International Airport '),
(816, N'MX', N'LMM', N'Los Mochis Airport'),
(817, N'US', N'LMT', N'Klamath Falls Airport'),
(818, N'US', N'LNK', N'Lincoln Airport'),
(819, N'US', N'LNS', N'Lancaster Airport'),
(820, N'AT', N'LNZ', N'Linz Airport'),
(821, N'PT', N'LOS', N'Lagos Murtala Muhammed Airport '),
(822, N'ES', N'LPA', N'Gran Canaria Las Palmas Airport'),
(823, N'BO', N'LPB', N'La Paz Airport'),
(824, N'SE', N'LPI', N'Linköping Airport'),
(825, N'GB', N'LPL', N'Liverpool Airport'),
(826, N'FI', N'LPP', N'Lappeenranta Airport'),
(827, N'LV', N'LPX', N'Liepaja Airport'),
(828, N'US', N'LRD', N'Laredo Airport'),
(829, N'AU', N'LRE', N'Longreach Airport '),
(830, N'FR', N'LRH', N'La Rochelle Airport'),
(831, N'DO', N'LRM', N'La Romana Airport'),
(832, N'GR', N'LRS', N'Leros Airport'),
(833, N'FR', N'LRT', N'Lorient Airport'),
(834, N'CL', N'LSC', N'La Serena Airport'),
(835, N'US', N'LSE', N'La Crosse Airport'),
(836, N'GB', N'LSI', N'Sumburgh Airport'),
(837, N'AU', N'LST', N'Launceston Airport'),
(838, N'AU', N'LSY', N'Lismore Airport'),
(839, N'GB', N'LTN', N'London Luton Airport'),
(840, N'MX', N'LTO', N'Loreto Airport'),
(841, N'FR', N'LTQ', N'Le Touquet Airport '),
(842, N'FR', N'LTT', N'La Mole Saint-Tropez Airport'),
(843, N'NA', N'LUD', N'Luederitz Airport '),
(844, N'CH', N'LUG', N'Lugano Airport '),
(845, N'ZM', N'LUN', N'Lusaka Airport'),
(846, N'AR', N'LUQ', N'San Luis Airport'),
(847, N'LU', N'LUX', N'Luxembourg Airport'),
(848, N'PL', N'LUZ', N'Lublin Airport'),
(849, N'ZM', N'LVI', N'Livingstone Airport'),
(850, N'US', N'LWB', N'Lewisburg Greenbrier Valley Airport'),
(851, N'GB', N'LWK', N'Tingwall Airport'),
(852, N'UA', N'LWO', N'Lviv Airport'),
(853, N'US', N'LWS', N'Lewiston Airport'),
(854, N'EG', N'LXR', N'Luxor Airport'),
(855, N'GR', N'LXS', N'Lemnos Airport'),
(856, N'US', N'LYH', N'Lynchburg Airport'),
(857, N'FR', N'LYS', N'Lyon Airport'),
(858, N'MX', N'LZC', N'Lazaro Cardenas Airport'),
(859, N'BR', N'MAB', N'Maraba Airport'),
(860, N'ES', N'MAD', N'Madrid Airport'),
(861, N'US', N'MAF', N'Midland Odessa Airport'),
(862, N'ES', N'MAH', N'Menorca Airport'),
(863, N'MX', N'MAM', N'Matamoros Airport'),
(864, N'GB', N'MAN', N'Manchester Airport'),
(865, N'BR', N'MAO', N'Manaus Airport'),
(866, N'TH', N'MAQ', N'Mae Sot Airport'),
(867, N'PR', N'MAZ', N'Mayagüez Eugenio Maria De Hostos Airport '),
(868, N'KE', N'MBA', N'Mombasa Airport'),
(869, N'JM', N'MBJ', N'Montego Bay Airport'),
(870, N'US', N'MBS', N'Freeland Airport'),
(871, N'SI', N'MBX', N'Maribor Airport'),
(872, N'US', N'MCI', N'Kansas City Airport'),
(873, N'FR', N'MCN', N'Macon Lewis B. Wilson Airport '),
(874, N'US', N'MCO', N'Orlando Airport'),
(875, N'BR', N'MCP', N'Macapa Airport'),
(876, N'OM', N'MCT', N'Muscat Airport'),
(877, N'AU', N'MCY', N'Sunshine Coast Airport'),
(878, N'BR', N'MCZ', N'Maceio Airport'),
(879, N'CO', N'MDE', N'Medellin Airport'),
(880, N'AR', N'MDQ', N'Mar del Plata Airport'),
(881, N'US', N'MDT', N'Harrisburg Airport'),
(882, N'US', N'MDW', N'Chicago Midway Airport'),
(883, N'AR', N'MDZ', N'Mendoza Airport'),
(884, N'AU', N'MEB', N'Melbourne Essendon Airport'),
(885, N'EC', N'MEC', N'Manta Airport '),
(886, N'SA', N'MED', N'Medina Airport'),
(887, N'AU', N'MEL', N'Melbourne Airport'),
(888, N'US', N'MEM', N'Memphis Airport'),
(889, N'MX', N'MEX', N'Mexico City Airport'),
(890, N'US', N'MFE', N'McAllen Airport'),
(891, N'US', N'MFR', N'Medford Airport'),
(892, N'NI', N'MGA', N'Managua Airport'),
(893, N'AU', N'MGB', N'Mount Gambier Airport'),
(894, N'BR', N'MGF', N'Maringa Airport'),
(895, N'ZA', N'MGH', N'Margate Airport '),
(896, N'US', N'MGM', N'Montgomery Airport'),
(897, N'US', N'MGW', N'Morgantown Airport'),
(898, N'IR', N'MHD', N'Mashhad International Airport'),
(899, N'DE', N'MHG', N'Mannheim Airport'),
(900, N'US', N'MHK', N'Manhattan Airport');

INSERT INTO @Airports (SourceOrder, CountryCode, Iata, LocationName)
VALUES
(901, N'FI', N'MHQ', N'Mariehamn Airport'),
(902, N'US', N'MHT', N'Manchester Airport'),
(903, N'US', N'MIA', N'Miami Airport'),
(904, N'MX', N'MID', N'Merida Airport'),
(905, N'BR', N'MII', N'Marilia Airport'),
(906, N'AU', N'MIM', N'Merimbula Airport'),
(907, N'TN', N'MIR', N'Monastir Airport'),
(908, N'NO', N'MJF', N'Mosjoen Airport '),
(909, N'GR', N'MJT', N'Lesbos Mytilene Airport'),
(910, N'US', N'MKE', N'Milwaukee Airport'),
(911, N'US', N'MKK', N'Hoolehua Molokai Airport'),
(912, N'US', N'MKL', N'Jackson McKellar-Sipes Airport'),
(913, N'AU', N'MKY', N'Mackay Airport'),
(914, N'MY', N'MKZ', N'Melaka Airport'),
(915, N'MT', N'MLA', N'Malta Airport'),
(916, N'US', N'MLB', N'Melbourne Orlando Airport'),
(917, N'FR', N'MLH', N'Mulhouse Basel Airport'),
(918, N'US', N'MLI', N'Moline Airport'),
(919, N'MX', N'MLM', N'Morelia Airport'),
(920, N'ES', N'MLN', N'Melilla Airport'),
(921, N'GR', N'MLO', N'Milos Airport'),
(922, N'US', N'MLU', N'Monroe Airport'),
(923, N'JP', N'MMB', N'Ozora Memanbetsu Airport'),
(924, N'GB', N'MME', N'Teesside Airport'),
(925, N'US', N'MMH', N'Mammoth Lakes Yosemite Airport'),
(926, N'US', N'MMU', N'Morristown Airport'),
(927, N'SE', N'MMX', N'Malmo Airport'),
(928, N'JP', N'MMY', N'Miyako Airport'),
(929, N'PH', N'MNL', N'Manila Airport'),
(930, N'US', N'MOB', N'Mobile Airport'),
(931, N'BR', N'MOC', N'Montes Claros Airport'),
(932, N'US', N'MOD', N'Modesto Airport'),
(933, N'NO', N'MOL', N'Molde Airport'),
(934, N'US', N'MOT', N'Minot Airport'),
(935, N'AU', N'MOV', N'Moranbah Airport'),
(936, N'PF', N'MOZ', N'Moorea Airport'),
(937, N'FR', N'MPL', N'Montpellier Airport'),
(938, N'MZ', N'MPM', N'Maputo Airport'),
(939, N'AU', N'MQL', N'Mildura Airport'),
(940, N'TR', N'MQM', N'Mardin Havalimanı ( MQM )'),
(941, N'NO', N'MQN', N'Mo I Rana Airport '),
(942, N'ZA', N'MQP', N'Nelspruit Kruger Mpumalanga Airport'),
(943, N'US', N'MQT', N'Marquette Sawyer Airport'),
(944, N'FR', N'MRS', N'Marseille Airport'),
(945, N'MU', N'MRU', N'Plaine Magnien Airport'),
(946, N'US', N'MRY', N'Monterey Airport'),
(947, N'AU', N'MRZ', N'Moree Airport'),
(948, N'JP', N'MSJ', N'Aomori Misawa Airport'),
(949, N'US', N'MSN', N'Madison Airport'),
(950, N'US', N'MSO', N'Missoula Airport'),
(951, N'US', N'MSP', N'Minneapolis Airport'),
(952, N'BY', N'MSQ', N'Minsk Airport'),
(953, N'NL', N'MST', N'Maastricht Airport'),
(954, N'LS', N'MSU', N'Maseru Moshoeshoe Airport'),
(955, N'US', N'MSY', N'New Orleans Airport'),
(956, N'US', N'MTH', N'Marathon Airport'),
(957, N'US', N'MTJ', N'Montrose Airport'),
(958, N'CO', N'MTR', N'Monteria Airport'),
(959, N'SZ', N'MTS', N'Matsapha Airport'),
(960, N'MX', N'MTT', N'Minatitlan Coatzacoalcos Airport'),
(961, N'US', N'MTW', N'Manitowoc Airport'),
(962, N'MX', N'MTY', N'Monterrey Airport'),
(963, N'BW', N'MUB', N'Maun Airport'),
(964, N'DE', N'MUC', N'Munich Airport'),
(965, N'VE', N'MUN', N'Maturin Airport'),
(966, N'UY', N'MVD', N'Montevideo Airport'),
(967, N'US', N'MVY', N'Martha''s Vineyard Airport'),
(968, N'US', N'MWA', N'Marion Airport'),
(969, N'MX', N'MXL', N'Mexicali Airport'),
(970, N'IT', N'MXP', N'Milan Malpensa Airport'),
(971, N'AU', N'MYA', N'Moruya Airport'),
(972, N'JP', N'MYJ', N'Matsuyama Airport'),
(973, N'US', N'MYR', N'Myrtle Beach Airport'),
(974, N'MY', N'MYY', N'Miri Airport'),
(975, N'MX', N'MZT', N'Mazatlan Airport'),
(976, N'AU', N'NAA', N'Narrabri Airport'),
(977, N'FJ', N'NAN', N'Nadi Airport'),
(978, N'IT', N'NAP', N'Naples Airport'),
(979, N'BS', N'NAS', N'Nassau Airport'),
(980, N'BR', N'NAT', N'Natal Airport'),
(981, N'TR', N'NAV', N'Nevşehir Havalimanı ( NAV )'),
(982, N'TN', N'NBE', N'Enfidha Airport'),
(983, N'KE', N'NBO', N'Nairobi Airport'),
(984, N'FR', N'NCE', N'Nice Airport'),
(985, N'GB', N'NCL', N'Newcastle Airport'),
(986, N'FR', N'NCY', N'Annecy Airport'),
(987, N'TD', N'NDJ', N'N´djamena Airport '),
(988, N'MA', N'NDR', N'Nador Airport'),
(989, N'JP', N'NGO', N'Tokoname Centrair Chubu Airport'),
(990, N'JP', N'NGS', N'Nagasaki Airport'),
(991, N'NE', N'NIM', N'Niamey Airport '),
(992, N'MR', N'NKC', N'Nouakchott Airport'),
(993, N'CN', N'NKG', N'Nanjing Lukou International Airport'),
(994, N'ZM', N'NLA', N'Ndola Airport'),
(995, N'MX', N'NLD', N'Nuevo Laredo Airport'),
(996, N'ZA', N'NLP', N'Nelspruit Airport '),
(997, N'TH', N'NNT', N'Nan Nakhon Airport'),
(998, N'IE', N'NOC', N'Knock Airport'),
(999, N'NZ', N'NPE', N'Napier Airport'),
(1000, N'NZ', N'NPL', N'New Plymouth Airport'),
(1001, N'AR', N'NQN', N'Neuquen Airport'),
(1002, N'GB', N'NQY', N'Newquay Airport'),
(1003, N'SE', N'NRK', N'Norrkoping Airport'),
(1004, N'DE', N'NRN', N'Düsseldorf Weeze Airport'),
(1005, N'PR', N'NRR', N'José Aponte De la Torre Airport'),
(1006, N'JP', N'NRT', N'Tokyo Narita Airport'),
(1007, N'NZ', N'NSN', N'Nelson Airport'),
(1008, N'TH', N'NST', N'Nakhon Si Thammarat Airport'),
(1009, N'FR', N'NTE', N'Nantes Airport'),
(1010, N'AU', N'NTL', N'Newcastle Airport'),
(1011, N'DE', N'NUE', N'Nuremberg Airport'),
(1012, N'CO', N'NVA', N'Neiva Airport'),
(1013, N'BR', N'NVT', N'Navegantes Airport'),
(1014, N'GB', N'NWI', N'Norwich Airport'),
(1015, N'SE', N'NYO', N'Nykoping Stockholm Skavsta Airport'),
(1016, N'AU', N'OAG', N'Orange Airport'),
(1017, N'US', N'OAJ', N'Richlands Jacksonville Albert Ellis Airport'),
(1018, N'US', N'OAK', N'Oakland Airport'),
(1019, N'BR', N'OAL', N'Cacoal Airport'),
(1020, N'MX', N'OAX', N'Oaxaca Airport'),
(1021, N'JP', N'OBO', N'Obihiro Airport'),
(1022, N'US', N'OCF', N'Ocala Airport'),
(1023, N'ES', N'ODB', N'Cordoba Airport'),
(1024, N'DK', N'ODE', N'Odense Airport '),
(1025, N'UA', N'ODS', N'Odessa Airport'),
(1026, N'SE', N'OER', N'Ornskoldsvik Airport'),
(1027, N'US', N'OGG', N'Kahului Airport'),
(1028, N'GY', N'OGL', N'Georgetown Ogle Airport'),
(1029, N'TR', N'OGU', N'Ordu - Giresun Havalimanı ( OGU )'),
(1030, N'MK', N'OHD', N'Ohrid Airport'),
(1031, N'JP', N'OIT', N'Oita Airport'),
(1032, N'JP', N'OKA', N'Naha Airport'),
(1033, N'US', N'OKC', N'Oklahoma City Airport'),
(1034, N'JP', N'OKJ', N'Okayama Airport'),
(1035, N'IT', N'OLB', N'Olbia Airport'),
(1036, N'AU', N'OLP', N'Olympic Dam Airport'),
(1037, N'US', N'OMA', N'Omaha Airport'),
(1038, N'BA', N'OMO', N'Mostar Airport'),
(1039, N'RO', N'OMR', N'Oradea Airport'),
(1040, N'NA', N'OND', N'Ondangwa Airport'),
(1041, N'US', N'ONP', N'Newport Airport'),
(1042, N'US', N'ONT', N'Ontario Airport'),
(1043, N'PA', N'ONX', N'Colon City Colon International Airport Airport '),
(1044, N'AU', N'OOL', N'Gold Coast Airport'),
(1045, N'AU', N'OOM', N'Cooma Airport'),
(1046, N'PT', N'OPO', N'Porto Airport'),
(1047, N'BR', N'OPS', N'Sinop Airport'),
(1048, N'SE', N'ORB', N'Orebro Airport'),
(1049, N'US', N'ORD', N'Chicago O''Hare Airport'),
(1050, N'US', N'ORF', N'Norfolk Airport'),
(1051, N'SR', N'ORG', N'Paramaribo Zorg en Hoop Airport'),
(1052, N'US', N'ORH', N'Worcester Airport'),
(1053, N'IE', N'ORK', N'Cork Airport'),
(1054, N'DZ', N'ORN', N'Oran Airport '),
(1055, N'BO', N'ORU', N'Oruro Airport'),
(1056, N'FR', N'ORY', N'Paris Orly Airport'),
(1057, N'SE', N'OSD', N'Ostersund Airport'),
(1058, N'HR', N'OSI', N'Osijek Airport'),
(1059, N'NO', N'OSL', N'Oslo Gardermoen Airport'),
(1060, N'CZ', N'OSR', N'Ostrava Airport'),
(1061, N'NO', N'OSY', N'Namsos Airport '),
(1062, N'US', N'OTH', N'North Bend Airport'),
(1063, N'RO', N'OTP', N'Bucharest Otopeni Airport'),
(1064, N'BF', N'OUA', N'Ouagadougou Airport '),
(1065, N'MA', N'OUD', N'Oujda Airport'),
(1066, N'FI', N'OUL', N'Oulu Airport'),
(1067, N'MR', N'OUZ', N'Zouerate Airport'),
(1068, N'ES', N'OVD', N'Oviedo Asturias Airport'),
(1069, N'US', N'OXC', N'Oxford Airport'),
(1070, N'US', N'OXR', N'Oxnard Airport'),
(1071, N'UA', N'OZH', N'Zaporizhia Airport'),
(1072, N'MA', N'OZZ', N'Ouarzazate Airport'),
(1073, N'PA', N'PAC', N'Panama City Marcos A Gelabert Airport'),
(1074, N'DE', N'PAD', N'Paderborn Lippstadt Airport'),
(1075, N'US', N'PAE', N'Everett Paine Field Airport'),
(1076, N'US', N'PAH', N'Paducah Barkley Airport'),
(1077, N'HT', N'PAP', N'Port-au-Prince Airport'),
(1078, N'GR', N'PAS', N'Paros Airport'),
(1079, N'MX', N'PAZ', N'Poza Rica International Airport'),
(1080, N'MX', N'PBC', N'Puebla Airport'),
(1081, N'US', N'PBG', N'Plattsburgh Airport'),
(1082, N'US', N'PBI', N'West Palm Beach Airport'),
(1083, N'SR', N'PBM', N'Paramaribo Airport'),
(1084, N'AU', N'PBO', N'Paraburdoo Airport'),
(1085, N'MX', N'PCM', N'Playa del Carmen Airport'),
(1086, N'PT', N'PDL', N'Ponta Delgada Airport'),
(1087, N'UY', N'PDP', N'Punta del Este Airport'),
(1088, N'MX', N'PDS', N'Piedras Negras Airport'),
(1089, N'BG', N'PDV', N'Plovdiv Airport'),
(1090, N'US', N'PDX', N'Portland Airport'),
(1091, N'CZ', N'PED', N'Pardubice Airport'),
(1092, N'IT', N'PEG', N'Perugia Airport'),
(1093, N'CO', N'PEI', N'Pereira Airport'),
(1094, N'CN', N'PEK', N'Beijing Capital Airport'),
(1095, N'MY', N'PEN', N'Penang Airport'),
(1096, N'US', N'PEO', N'Penn Yan Airport'),
(1097, N'AU', N'PER', N'Perth Airport'),
(1098, N'BR', N'PET', N'Pelotas Airport'),
(1099, N'HU', N'PEV', N'Pecs Pogany Airport '),
(1100, N'BR', N'PFB', N'Passo Fundo Airport'),
(1101, N'CY', N'PFO', N'Paphos Airport'),
(1102, N'US', N'PGD', N'Punta Gorda Airport'),
(1103, N'FR', N'PGF', N'Perpignan Airport'),
(1104, N'US', N'PGV', N'Pitt Greenville Airport'),
(1105, N'AU', N'PHE', N'Port Hedland Airport'),
(1106, N'US', N'PHF', N'Newport News Airport'),
(1107, N'US', N'PHL', N'Philadelphia Airport'),
(1108, N'TH', N'PHS', N'Phitsanulok Airport'),
(1109, N'ZA', N'PHW', N'Phalaborwa Airport '),
(1110, N'US', N'PHX', N'Phoenix Sky Harbor Airport'),
(1111, N'US', N'PIA', N'Peoria Airport'),
(1112, N'US', N'PIE', N'Clearwater Airport'),
(1113, N'FR', N'PIS', N'Poitiers Airport'),
(1114, N'US', N'PIT', N'Pittsburgh Airport'),
(1115, N'PE', N'PIU', N'Piura Airport'),
(1116, N'PT', N'PIX', N'Pico Airport'),
(1117, N'CR', N'PJM', N'Puerto Jimenez Airport'),
(1118, N'AU', N'PKE', N'Parkes Airport'),
(1119, N'US', N'PLN', N'Pellston Airport'),
(1120, N'AU', N'PLO', N'Port Lincoln Airport'),
(1121, N'LT', N'PLQ', N'Palanga Airport'),
(1122, N'TC', N'PLS', N'Providenciales Airport'),
(1123, N'BR', N'PLU', N'Belo Horizonte Pampulha Airport'),
(1124, N'ZA', N'PLZ', N'Port Elizabeth Airport'),
(1125, N'CL', N'PMC', N'Puerto Montt Airport'),
(1126, N'IT', N'PMF', N'Parma Airport'),
(1127, N'ES', N'PMI', N'Palma de Mallorca Airport'),
(1128, N'IT', N'PMO', N'Palermo Airport'),
(1129, N'NZ', N'PMR', N'Palmerston North Airport'),
(1130, N'VE', N'PMV', N'Margarita Island Santiago Marino Airport'),
(1131, N'BR', N'PMW', N'Palmas Airport'),
(1132, N'AR', N'PMY', N'Puerto Madryn El Tehuelche Airport '),
(1133, N'ES', N'PNA', N'Pamplona Airport'),
(1134, N'KH', N'PNH', N'Phnom Penh Airport'),
(1135, N'IT', N'PNL', N'Pantelleria Airport'),
(1136, N'US', N'PNS', N'Pensacola Airport'),
(1137, N'CL', N'PNT', N'Puerto Natales Airport'),
(1138, N'BR', N'PNZ', N'Petrolina Airport'),
(1139, N'BR', N'POA', N'Porto Alegre Airport'),
(1140, N'GA', N'POG', N'Port Gentil Airport '),
(1141, N'MZ', N'POL', N'Pemba Airport'),
(1142, N'DO', N'POP', N'Puerto Plata Airport'),
(1143, N'FI', N'POR', N'Pori Airport'),
(1144, N'TT', N'POS', N'Port of Spain Piarco Airport'),
(1145, N'SI', N'POW', N'Portoroz Airport'),
(1146, N'PL', N'POZ', N'Poznan Airport'),
(1147, N'BR', N'PPB', N'Presidente Prudente Airport'),
(1148, N'AU', N'PPP', N'Proserpine Airport'),
(1149, N'PH', N'PPS', N'Puerto Princesa City International Airport '),
(1150, N'PF', N'PPT', N'Papeete Airport'),
(1151, N'US', N'PQI', N'Presque Isle Airport'),
(1152, N'AU', N'PQQ', N'Port Macquarie Airport'),
(1153, N'AR', N'PRA', N'Parana Airport '),
(1154, N'CZ', N'PRG', N'Prague Airport'),
(1155, N'XK', N'PRN', N'Pristina Airport'),
(1156, N'ZA', N'PRY', N'Pretoria Wonderboom Airport'),
(1157, N'IT', N'PSA', N'Pisa Airport'),
(1158, N'US', N'PSC', N'Pasco Airport'),
(1159, N'PR', N'PSE', N'Ponce Mercedita Airport '),
(1160, N'US', N'PSP', N'Palm Springs Airport'),
(1161, N'IT', N'PSR', N'Pescara Airport'),
(1162, N'AR', N'PSS', N'Posadas Airport'),
(1163, N'ZA', N'PTG', N'Polokwane Airport'),
(1164, N'AU', N'PTJ', N'Portland Airport'),
(1165, N'US', N'PTK', N'Waterford Airport'),
(1166, N'GP', N'PTP', N'Pointe a Pitre Airport'),
(1167, N'PA', N'PTY', N'Panama City Tocumen Airport'),
(1168, N'FR', N'PUF', N'Pau Airport'),
(1169, N'AU', N'PUG', N'Port Augusta Airport'),
(1170, N'DO', N'PUJ', N'Punta Cana Airport'),
(1171, N'CL', N'PUQ', N'Punta Arenas Airport'),
(1172, N'KR', N'PUS', N'Busan Gimhae Airport'),
(1173, N'US', N'PUW', N'Pullman Airport'),
(1174, N'HR', N'PUY', N'Pula Airport'),
(1175, N'US', N'PVD', N'Providence Airport'),
(1176, N'BR', N'PVH', N'Porto Velho Airport'),
(1177, N'GR', N'PVK', N'Preveza Aktion Airport'),
(1178, N'MX', N'PVR', N'Puerto Vallarta Airport'),
(1179, N'US', N'PVU', N'Provo Airport'),
(1180, N'US', N'PWM', N'Portland International Jetport'),
(1181, N'MX', N'PXM', N'Puerto Escondido Airport'),
(1182, N'ZA', N'PZB', N'Pietermaritzburg Airport'),
(1183, N'VE', N'PZO', N'Guayana Manuel Carlos Piar Airport'),
(1184, N'MX', N'QRO', N'Queretaro Airport'),
(1185, N'SA', N'RAE', N'Arar Domestic Airport'),
(1186, N'CV', N'RAI', N'Praia Airport '),
(1187, N'MA', N'RAK', N'Marrakech Airport'),
(1188, N'BR', N'RAO', N'Ribeirao Preto Airport'),
(1189, N'US', N'RAP', N'Rapid City Airport'),
(1190, N'IR', N'RAS', N'Rasht Airport'),
(1191, N'MA', N'RBA', N'Rabat Airport'),
(1192, N'BR', N'RBR', N'Rio Branco Airport'),
(1193, N'ZA', N'RCB', N'Richards Bay Airport'),
(1194, N'US', N'RDD', N'Redding Municipal Airport'),
(1195, N'US', N'RDG', N'Reading Airport'),
(1196, N'US', N'RDM', N'Redmond Airport'),
(1197, N'PL', N'RDO', N'Radom Airport'),
(1198, N'US', N'RDU', N'Raleigh Airport'),
(1199, N'FR', N'RDZ', N'Rodez Airport'),
(1200, N'BR', N'REC', N'Recife Airport'),
(1201, N'IT', N'REG', N'Reggio Calabria Airport'),
(1202, N'AR', N'REL', N'Trelew Airport'),
(1203, N'KH', N'REP', N'Siem Reap Airport'),
(1204, N'AR', N'RES', N'Resistencia Airport '),
(1205, N'ES', N'REU', N'Reus Airport'),
(1206, N'MX', N'REX', N'Reynosa Airport'),
(1207, N'US', N'RFD', N'Rockford Airport'),
(1208, N'AR', N'RGA', N'Rio Grande Airport'),
(1209, N'AR', N'RGL', N'Rio Gallegos Airport'),
(1210, N'US', N'RHI', N'Rhinelander Airport'),
(1211, N'GR', N'RHO', N'Rhodes Airport'),
(1212, N'BR', N'RIA', N'Santa Maria Airport'),
(1213, N'US', N'RIC', N'Richmond Airport'),
(1214, N'US', N'RIW', N'Riverton Airport'),
(1215, N'LV', N'RIX', N'Riga Airport'),
(1216, N'HR', N'RJK', N'Rijeka Airport'),
(1217, N'DK', N'RKE', N'Roskilde Airport'),
(1218, N'IS', N'RKV', N'Reykjavik Domestic Airport'),
(1219, N'DE', N'RLG', N'Rostock Airport '),
(1220, N'AU', N'RMA', N'Roma Airport'),
(1221, N'EG', N'RMF', N'Marsa Alam Airport'),
(1222, N'IT', N'RMI', N'Rimini Airport'),
(1223, N'MD', N'RMO', N'Chisinau Airport'),
(1224, N'TW', N'RMQ', N'Taichung Airport'),
(1225, N'ES', N'RMU', N'Murcia Airport'),
(1226, N'SE', N'RNB', N'Ronneby Airport'),
(1227, N'DK', N'RNN', N'Ronne Bornholm Airport'),
(1228, N'US', N'RNO', N'Reno Airport'),
(1229, N'FR', N'RNS', N'Rennes Airport'),
(1230, N'US', N'ROA', N'Roanoke Airport'),
(1231, N'US', N'ROC', N'Rochester Airport'),
(1232, N'AU', N'ROK', N'Rockhampton Airport'),
(1233, N'BR', N'ROO', N'Rondonopolis Airport'),
(1234, N'PW', N'ROR', N'Airai Palau Airport'),
(1235, N'AR', N'ROS', N'Rosario Airport'),
(1236, N'NZ', N'ROT', N'Rotorua Airport'),
(1237, N'RU', N'ROV', N'Rostov On Don Platov Airport '),
(1238, N'US', N'ROW', N'Roswell Airport'),
(1239, N'US', N'RST', N'Rochester Airport'),
(1240, N'KR', N'RSU', N'Yeosu Airport'),
(1241, N'US', N'RSW', N'Fort Myers Southwest Florida International Airport'),
(1242, N'HN', N'RTB', N'Roatan Island Airport'),
(1243, N'NL', N'RTM', N'Rotterdam'),
(1244, N'SA', N'RUH', N'Riyadh King Khalid Airport'),
(1245, N'RE', N'RUN', N'Saint Denis Airport'),
(1246, N'BR', N'RVD', N'Rio Verde Airport'),
(1247, N'NO', N'RVK', N'Roervik Airport'),
(1248, N'FI', N'RVN', N'Rovaniemi Airport'),
(1249, N'PL', N'RZE', N'Rzeszow Airport'),
(1250, N'TR', N'RZV', N'Rize Havalimanı ( RZV )'),
(1251, N'US', N'SAF', N'Santa Fe Airport'),
(1252, N'YE', N'SAH', N'Sana''a International Airport '),
(1253, N'SV', N'SAL', N'El Salvador Airport'),
(1254, N'US', N'SAN', N'San Diego Airport'),
(1255, N'HN', N'SAP', N'San Pedro Sula Airport'),
(1256, N'US', N'SAT', N'San Antonio Airport'),
(1257, N'US', N'SAV', N'Savannah Airport'),
(1258, N'TR', N'SAW', N'İstanbul Sabiha Gökçen Havalimanı ( SAW )'),
(1259, N'US', N'SBA', N'Santa Barbara Airport'),
(1260, N'US', N'SBD', N'San Bernardino Airport'),
(1261, N'BL', N'SBH', N'Saint Barthelemy Airport'),
(1262, N'US', N'SBN', N'South Bend Airport'),
(1263, N'US', N'SBP', N'San Luis Obispo County Airport'),
(1264, N'US', N'SBY', N'Salisbury Airport'),
(1265, N'RO', N'SBZ', N'Sibiu Airport'),
(1266, N'US', N'SCE', N'State College Airport'),
(1267, N'US', N'SCK', N'Stockton Airport'),
(1268, N'CL', N'SCL', N'Santiago Airport'),
(1269, N'DE', N'SCN', N'Saarbrücken Airport'),
(1270, N'ES', N'SCQ', N'Santiago de Compostela Airport'),
(1271, N'SE', N'SCR', N'Salen Airport'),
(1272, N'GB', N'SCS', N'Shetland Islands Scatsa Airport'),
(1273, N'RO', N'SCV', N'Suceava Airport'),
(1274, N'AR', N'SDE', N'Santiago Del Estero Airport '),
(1275, N'US', N'SDF', N'Louisville Airport'),
(1276, N'JP', N'SDJ', N'Sendai Airport'),
(1277, N'MY', N'SDK', N'Sandakan Airport'),
(1278, N'SE', N'SDL', N'Sundsvall Airport'),
(1279, N'NO', N'SDN', N'Sandane Airport '),
(1280, N'DO', N'SDQ', N'Santo Domingo Las Americas Airport'),
(1281, N'ES', N'SDR', N'Santander Airport'),
(1282, N'BR', N'SDU', N'Rio de Janeiro Santos Dumont Airport'),
(1283, N'US', N'SEA', N'Seattle Tacoma Airport'),
(1284, N'GB', N'SEN', N'Southend Airport'),
(1285, N'SC', N'SEZ', N'Seychelles Airport'),
(1286, N'US', N'SFB', N'Orlando Sanford Airport'),
(1287, N'MF', N'SFG', N'Grand Case Airport'),
(1288, N'US', N'SFO', N'San Francisco Airport'),
(1289, N'SE', N'SFT', N'Skelleftea Airport'),
(1290, N'DK', N'SGD', N'Sonderborg Airport'),
(1291, N'US', N'SGF', N'Springfield Airport'),
(1292, N'US', N'SGR', N'Sugar Land Airport'),
(1293, N'US', N'SGU', N'Saint George Airport'),
(1294, N'JP', N'SHB', N'Nakashibetsu Airport'),
(1295, N'AE', N'SHJ', N'Sharjah Airport'),
(1296, N'JP', N'SHM', N'Shirahama Airport'),
(1297, N'US', N'SHV', N'Shreveport Airport'),
(1298, N'SG', N'SIN', N'Singapore Changi Airport'),
(1299, N'CH', N'SIR', N'Sion Airport'),
(1300, N'US', N'SJC', N'San Jose Airport'),
(1301, N'MX', N'SJD', N'Los Cabos Airport'),
(1302, N'BA', N'SJJ', N'Sarajevo Airport'),
(1303, N'BR', N'SJK', N'Sao Jose dos Campos Airport'),
(1304, N'CR', N'SJO', N'San Jose Airport'),
(1305, N'BR', N'SJP', N'Sao Jose do Rio Preto Airport'),
(1306, N'US', N'SJT', N'San Angelo Airport'),
(1307, N'PR', N'SJU', N'San Juan Airport'),
(1308, N'PT', N'SJZ', N'Sao Jorge Airport'),
(1309, N'GR', N'SKG', N'Thessaloniki Airport'),
(1310, N'NO', N'SKN', N'Stokmarknes Skagen Airport '),
(1311, N'MK', N'SKP', N'Skopje Airport'),
(1312, N'AR', N'SLA', N'Salta Airport'),
(1313, N'US', N'SLC', N'Salt Lake City Airport'),
(1314, N'ZM', N'SLI', N'Solwezi Airport'),
(1315, N'OM', N'SLL', N'Salalah Airport'),
(1316, N'US', N'SLN', N'Salina Airport'),
(1317, N'MX', N'SLP', N'San Luis Potosi Airport'),
(1318, N'LC', N'SLU', N'Saint Lucia George F. L. Charles Airport'),
(1319, N'MX', N'SLW', N'Saltillo Airport'),
(1320, N'BR', N'SLZ', N'Sao Luis Airport'),
(1321, N'PT', N'SMA', N'Santa Maria Airport'),
(1322, N'US', N'SMF', N'Sacramento Airport'),
(1323, N'GR', N'SMI', N'Samos Airport'),
(1324, N'CO', N'SMR', N'Santa Marta Airport'),
(1325, N'US', N'SMX', N'Santa Maria Airport'),
(1326, N'US', N'SNA', N'Santa Ana John Wayne Airport'),
(1327, N'IE', N'SNN', N'Shannon Airport'),
(1328, N'FR', N'SNR', N'Saint Nazaire Montoir Airport '),
(1329, N'HU', N'SOB', N'Sarmellék Balaton Airport '),
(1330, N'BG', N'SOF', N'Sofia Airport'),
(1331, N'NO', N'SOG', N'Sogndal Airport'),
(1332, N'US', N'SOP', N'Pinehurst Airport'),
(1333, N'GB', N'SOU', N'Southampton Airport'),
(1334, N'ES', N'SPC', N'La Palma Airport'),
(1335, N'US', N'SPI', N'Springfield Airport'),
(1336, N'MP', N'SPN', N'Saipan Airport'),
(1337, N'US', N'SPS', N'Wichita Falls Airport'),
(1338, N'HR', N'SPU', N'Split Airport'),
(1339, N'EG', N'SPX', N'Sphinx International Airport'),
(1340, N'LT', N'SQQ', N'Siauliai Airport'),
(1341, N'BO', N'SRE', N'Sucre Alcantari Airport'),
(1342, N'US', N'SRQ', N'Sarasota Airport'),
(1343, N'BO', N'SRZ', N'Santa Cruz de la Sierra El Trompillo Airport'),
(1344, N'BR', N'SSA', N'Salvador International Airport'),
(1345, N'NO', N'SSJ', N'Sandnessjoen Airport'),
(1346, N'DO', N'STI', N'Santiago Airport'),
(1347, N'US', N'STL', N'Saint Louis International Airport'),
(1348, N'BR', N'STM', N'Santarem Airport'),
(1349, N'GB', N'STN', N'London Stansted Airport'),
(1350, N'DE', N'STR', N'Stuttgart Airport'),
(1351, N'US', N'STS', N'Santa Rosa Sonoma County Airport'),
(1352, N'IT', N'SUF', N'Lamezia Terme Airport'),
(1353, N'RO', N'SUJ', N'Satu Mare Airport'),
(1354, N'US', N'SUN', N'Hailey Airport'),
(1355, N'US', N'SUX', N'Sioux City Airport'),
(1356, N'VC', N'SVD', N'Argyle International Airport'),
(1357, N'NO', N'SVG', N'Stavanger Airport'),
(1358, N'NO', N'SVJ', N'Svolvaer Airport'),
(1359, N'FI', N'SVL', N'Savonlinna Airport '),
(1360, N'RU', N'SVO', N'Moscow Sheremetyevo Airport'),
(1361, N'ES', N'SVQ', N'Seville Airport'),
(1362, N'RU', N'SVX', N'Yekaterinburg Kolzowo Airport '),
(1363, N'US', N'SWF', N'New Windsor Airport'),
(1364, N'FR', N'SXB', N'Strasbourg Airport'),
(1365, N'DE', N'SXF', N'Berlin Schönefeld Airport'),
(1366, N'SX', N'SXM', N'Simpson Bay Princess Juliana Airport'),
(1367, N'AU', N'SYD', N'Sydney Airport'),
(1368, N'JP', N'SYO', N'Sakata Airport '),
(1369, N'CR', N'SYQ', N'San Jose Tobías Bolaños Airport '),
(1370, N'US', N'SYR', N'Syracuse Airport'),
(1371, N'CN', N'SYX', N'Sanya Phoenix International Airport'),
(1372, N'IR', N'SYZ', N'Shiraz International Airport'),
(1373, N'MY', N'SZB', N'Kuala Lumpur Subang Airport'),
(1374, N'TR', N'SZF', N'Samsun Çarşamba Havalimanı ( SZF )'),
(1375, N'AT', N'SZG', N'Salzburg Airport'),
(1376, N'ZA', N'SZK', N'Skukuza Airport '),
(1377, N'PL', N'SZY', N'Olsztyn Airport'),
(1378, N'PL', N'SZZ', N'Szczecin Goleniow Airport'),
(1379, N'TT', N'TAB', N'Crown Point Robinson Airport'),
(1380, N'JP', N'TAK', N'Takamatsu Airport'),
(1381, N'MX', N'TAM', N'Tampico Airport'),
(1382, N'CN', N'TAO', N'Qingdao Liuting International Airport'),
(1383, N'MX', N'TAP', N'Tapachula Airport'),
(1384, N'SK', N'TAT', N'Poprad Airport'),
(1385, N'EE', N'TAY', N'Tartu Airport'),
(1386, N'GE', N'TBS', N'Tbilisi Airport'),
(1387, N'IR', N'TBZ', N'Tabriz Airport'),
(1388, N'MZ', N'TCV', N'Tete Airport'),
(1389, N'PT', N'TER', N'Terceira Airport'),
(1390, N'MZ', N'TET', N'Tete Airport '),
(1391, N'US', N'TEX', N'Telluride Airport'),
(1392, N'ES', N'TFN', N'Tenerife Airport North'),
(1393, N'ES', N'TFS', N'Tenerife Airport South'),
(1394, N'ME', N'TGD', N'Podgorica Airport'),
(1395, N'MY', N'TGG', N'Kuala Terengganu Airport'),
(1396, N'RO', N'TGM', N'Targu Mures Airport'),
(1397, N'HN', N'TGU', N'Tegucigalpa Airport'),
(1398, N'MX', N'TGZ', N'Tuxtla Gutierrez Airport'),
(1399, N'BR', N'THE', N'Teresina Airport'),
(1400, N'SE', N'THN', N'Trollhattan Airport'),
(1401, N'IR', N'THR', N'Tehran Mehrabad Airport'),
(1402, N'AL', N'TIA', N'Tirana Airport'),
(1403, N'SA', N'TIF', N'Taif Airport'),
(1404, N'MX', N'TIJ', N'Tijuana Airport'),
(1405, N'MP', N'TIQ', N'Tinian Airport'),
(1406, N'NZ', N'TIU', N'Timaru Airport '),
(1407, N'ME', N'TIV', N'Tivat Airport'),
(1408, N'BO', N'TJA', N'Tarija Airport'),
(1409, N'BR', N'TJL', N'Tres Lagoas Airport'),
(1410, N'JP', N'TKN', N'Tokunoshima Airport'),
(1411, N'JP', N'TKS', N'Tokushima Awaodori Airport'),
(1412, N'FI', N'TKU', N'Turku Airport'),
(1413, N'MX', N'TLC', N'Toluca Airport'),
(1414, N'US', N'TLH', N'Tallahassee Airport'),
(1415, N'EE', N'TLL', N'Tallinn Airport'),
(1416, N'FR', N'TLN', N'Toulon Airport'),
(1417, N'FR', N'TLS', N'Toulouse Blagnac Airport'),
(1418, N'IL', N'TLV', N'Tel Aviv Ben Gurion Airport'),
(1419, N'FI', N'TMP', N'Tampere Airport'),
(1420, N'CR', N'TMU', N'Tambor Airport '),
(1421, N'AU', N'TMW', N'Tamworth Airport'),
(1422, N'MA', N'TNG', N'Tangier Airport'),
(1423, N'CR', N'TNO', N'Tamarindo Airport '),
(1424, N'MG', N'TNR', N'Antananarivo Airport '),
(1425, N'US', N'TOL', N'Toledo Express Airport'),
(1426, N'NO', N'TOS', N'Tromsoe Airport'),
(1427, N'BR', N'TOW', N'Toledo Airport'),
(1428, N'JP', N'TOY', N'Toyama Airport '),
(1429, N'US', N'TPA', N'Tampa Airport'),
(1430, N'PE', N'TPP', N'Tarapoto Airport'),
(1431, N'MX', N'TPQ', N'Tepic Airport '),
(1432, N'IT', N'TPS', N'Trapani Airport'),
(1433, N'MX', N'TRC', N'Torreon Airport'),
(1434, N'NO', N'TRD', N'Trondheim Airport'),
(1435, N'NO', N'TRF', N'Sandefjord Airport'),
(1436, N'NZ', N'TRG', N'Tauranga Airport'),
(1437, N'US', N'TRI', N'Blountville Tri-Cities Airport'),
(1438, N'IT', N'TRN', N'Turin Airport'),
(1439, N'AU', N'TRO', N'Taree Airport'),
(1440, N'IT', N'TRS', N'Trieste Airport'),
(1441, N'PE', N'TRU', N'Trujillo Airport'),
(1442, N'TW', N'TSA', N'Taipei Songshan Airport'),
(1443, N'IT', N'TSF', N'Treviso Airport'),
(1444, N'RO', N'TSR', N'Timisoara Airport'),
(1445, N'AU', N'TSV', N'Townsville Airport'),
(1446, N'JP', N'TTJ', N'Tottori Airport'),
(1447, N'US', N'TTN', N'Trenton Mercer Airport'),
(1448, N'MA', N'TTU', N'Tetouan Airport'),
(1449, N'AR', N'TUC', N'San Miguel de Tucuman Airport'),
(1450, N'FR', N'TUF', N'Tours Airport'),
(1451, N'US', N'TUL', N'Tulsa Airport'),
(1452, N'TN', N'TUN', N'Tunis Airport'),
(1453, N'NZ', N'TUO', N'Taupo Airport'),
(1454, N'US', N'TUP', N'Tupelo Airport'),
(1455, N'US', N'TUS', N'Tucson Airport'),
(1456, N'US', N'TVC', N'Traverse City Airport'),
(1457, N'US', N'TVL', N'South Lake Tahoe Airport'),
(1458, N'AU', N'TWB', N'Toowoomba Airport '),
(1459, N'US', N'TWF', N'Twin Falls Airport'),
(1460, N'BR', N'TXF', N'Teixeira de Freitas Airport'),
(1461, N'US', N'TXK', N'Texarkana Airport'),
(1462, N'PE', N'TYL', N'Talara Airport'),
(1463, N'US', N'TYR', N'Tyler Airport'),
(1464, N'US', N'TYS', N'Knoxville Airport'),
(1465, N'BA', N'TZL', N'Tuzla Airport'),
(1466, N'TR', N'TZX', N'Trabzon Havalimanı ( TZX )'),
(1467, N'AR', N'UAQ', N'San Juan Airport'),
(1468, N'BR', N'UBA', N'Uberaba Airport'),
(1469, N'JP', N'UBJ', N'Ube Airport'),
(1470, N'TH', N'UBP', N'Ubon Ratchathani Airport'),
(1471, N'BR', N'UDI', N'Uberlandia Airport'),
(1472, N'MZ', N'UEL', N'Quelimane Airport'),
(1473, N'RU', N'UFA', N'Ufa Airport '),
(1474, N'EC', N'UIO', N'Quito Airport'),
(1475, N'FR', N'UIP', N'Quimper Airport'),
(1476, N'JP', N'UKB', N'Kobe Airport'),
(1477, N'ZA', N'ULD', N'Ulundi  Prince Mangosuthu Buthelezi  Airport '),
(1478, N'SA', N'ULH', N'Al Ula Domestic Airport'),
(1479, N'SE', N'UME', N'Umea Airport'),
(1480, N'EE', N'URE', N'Kuressaare Airport'),
(1481, N'BR', N'URG', N'Uruguaiana Airport'),
(1482, N'TH', N'URT', N'Surat Thani Airport'),
(1483, N'US', N'USA', N'Concord Regional Airport'),
(1484, N'AR', N'USH', N'Ushuaia Airport'),
(1485, N'TH', N'USM', N'Samui Airport'),
(1486, N'KR', N'USN', N'Ulsan Airport'),
(1487, N'TH', N'UTH', N'Udon Thani Airport'),
(1488, N'ZA', N'UTN', N'Upington Airport'),
(1489, N'ZA', N'UTT', N'Mthatha Airport'),
(1490, N'LC', N'UVF', N'Saint Lucia Hewanorra International Airport'),
(1491, N'FI', N'VAA', N'Vaasa Airport'),
(1492, N'BR', N'VAG', N'Varginha Airport'),
(1493, N'BR', N'VAL', N'Valenca Airport'),
(1494, N'BG', N'VAR', N'Varna Airport'),
(1495, N'TR', N'VAS', N'Sivas Nuri Demirağ Havalimanı ( VAS )'),
(1496, N'IT', N'VBS', N'Brescia Montichiari Airport'),
(1497, N'SE', N'VBY', N'Visby Airport'),
(1498, N'US', N'VCB', N'Vacaville Airport'),
(1499, N'IT', N'VCE', N'Venice Marco Polo Airport'),
(1500, N'BR', N'VCP', N'Campinas Airport'),
(1501, N'BR', N'VDC', N'Vitoria da Conquista Airport'),
(1502, N'ES', N'VDE', N'El Hierro Airport'),
(1503, N'AR', N'VDM', N'Viedma Airport '),
(1504, N'NO', N'VDS', N'Vadsoe Airport '),
(1505, N'US', N'VEL', N'Vernal Airport'),
(1506, N'MX', N'VER', N'Veracruz Airport'),
(1507, N'IS', N'VEY', N'Vestmannaeyjar Airport'),
(1508, N'ZW', N'VFA', N'Victoria Falls Airport'),
(1509, N'ES', N'VGO', N'Vigo Airport'),
(1510, N'US', N'VGT', N'Las Vegas North Airport '),
(1511, N'AT', N'VIE', N'Vienna Airport'),
(1512, N'MA', N'VIL', N'Dakhla Airport'),
(1513, N'UA', N'VIN', N'Vinnytsia Havryshivka Airport '),
(1514, N'BR', N'VIX', N'Vitoria Airport'),
(1515, N'RU', N'VKO', N'Moscow Vnukovo Airport'),
(1516, N'ES', N'VLC', N'Valencia Airport'),
(1517, N'US', N'VLD', N'Valdosta Airport'),
(1518, N'VU', N'VLI', N'Port Vila Airport'),
(1519, N'ES', N'VLL', N'Valladolid Airport'),
(1520, N'VE', N'VLN', N'Valencia Arturo Michelana Airport'),
(1521, N'AL', N'VLO', N'Vlora Airport'),
(1522, N'GB', N'VLY', N'Anglesey Airport '),
(1523, N'FR', N'VNE', N'Vannes Meucon Airport '),
(1524, N'LT', N'VNO', N'Vilnius Airport'),
(1525, N'MZ', N'VNX', N'Vilankulo Airport'),
(1526, N'GR', N'VOL', N'Volos Nea Anchialos Airport'),
(1527, N'US', N'VPS', N'Fort Walton Beach Airport'),
(1528, N'US', N'VRB', N'Vero Beach Airport'),
(1529, N'IT', N'VRN', N'Verona Airport'),
(1530, N'MX', N'VSA', N'Villahermosa Airport'),
(1531, N'SE', N'VST', N'Vasteras Airport'),
(1532, N'CO', N'VUP', N'Valledupar Airport'),
(1533, N'BO', N'VVI', N'Santa Cruz de la Sierra Viru Viru Airport'),
(1534, N'RU', N'VVO', N'Vladivostok Vladivostok International Airport Airport '),
(1535, N'SE', N'VXO', N'Vaxjo Airport'),
(1536, N'NZ', N'WAG', N'Wanganui Airport'),
(1537, N'PL', N'WAW', N'Warsaw Chopin Airport'),
(1538, N'NA', N'WDH', N'Windhoek International Airport'),
(1539, N'AU', N'WGA', N'Wagga Wagga Airport'),
(1540, N'NZ', N'WHK', N'Whakatane Airport'),
(1541, N'KE', N'WIL', N'Nairobi Wilson Airport'),
(1542, N'JP', N'WKJ', N'Wakkanai Airport'),
(1543, N'NZ', N'WLG', N'Wellington Airport'),
(1544, N'PL', N'WMI', N'Warsaw Modlin Airport'),
(1545, N'NZ', N'WRE', N'Whangarei Airport'),
(1546, N'PL', N'WRO', N'Wroclaw Airport'),
(1547, N'NZ', N'WSZ', N'Westport Airport'),
(1548, N'AU', N'WTB', N'Brisbane West Wellcamp Airport'),
(1549, N'NA', N'WVB', N'Walvis Bay Airport'),
(1550, N'US', N'WVI', N'Watsonville Airport'),
(1551, N'AU', N'WYA', N'Whyalla Airport'),
(1552, N'BR', N'XAP', N'Chapeco Airport'),
(1553, N'FR', N'XCW', N'Chaumont Airport '),
(1554, N'FR', N'XLG', N'Lognes Airport'),
(1555, N'US', N'XNA', N'Bentonville Northwest Arkansas Airport'),
(1556, N'CN', N'XNN', N'Xining Caojiabao Airport'),
(1557, N'CR', N'XQP', N'Quepos Airport '),
(1558, N'ES', N'XRY', N'Jerez Airport'),
(1559, N'CA', N'YAM', N'Sault Sainte Marie Airport'),
(1560, N'CA', N'YAZ', N'Tofino Airport '),
(1561, N'CA', N'YBC', N'Baie Comeau Airport'),
(1562, N'CA', N'YBG', N'Bagotville Airport'),
(1563, N'CA', N'YBL', N'Campbell River Airport'),
(1564, N'CA', N'YCC', N'Cornwall Airport'),
(1565, N'CA', N'YCD', N'Nanaimo Airport'),
(1566, N'CA', N'YCW', N'Chilliwack Airport'),
(1567, N'CA', N'YDF', N'Deer Lake Airport'),
(1568, N'CA', N'YDQ', N'Dawson Creek Airport'),
(1569, N'CA', N'YEG', N'Edmonton Airport'),
(1570, N'CA', N'YEY', N'Amos Airport'),
(1571, N'CA', N'YFC', N'Fredericton Airport'),
(1572, N'JP', N'YGJ', N'Sakaiminato Yonago Airport'),
(1573, N'CA', N'YGK', N'Kingston Airport'),
(1574, N'CA', N'YGP', N'Gaspe Airport'),
(1575, N'CA', N'YGV', N'Havre St Pierre Airport '),
(1576, N'CA', N'YHD', N'Dryden Airport'),
(1577, N'CA', N'YHM', N'Hamilton Airport'),
(1578, N'CA', N'YHY', N'Hay River Airport '),
(1579, N'CA', N'YHZ', N'Halifax Airport'),
(1580, N'CA', N'YKA', N'Kamloops Airport'),
(1581, N'CA', N'YKF', N'Kitchener Waterloo Airport '),
(1582, N'US', N'YKM', N'Yakima Airport'),
(1583, N'CA', N'YKZ', N'Toronto Buttonville Municipal Airport '),
(1584, N'CA', N'YLW', N'Kelowna Airport'),
(1585, N'CA', N'YMM', N'Fort McMurray Airport'),
(1586, N'CA', N'YMT', N'Chibougamau Airport'),
(1587, N'CA', N'YNA', N'Natashquan Airport '),
(1588, N'SA', N'YNB', N'Yanbu Airport'),
(1589, N'US', N'YNG', N'Vienna Youngstown-Warren Airport'),
(1590, N'CA', N'YOJ', N'High Level Airport'),
(1591, N'CA', N'YOP', N'Rainbow Lake Airport '),
(1592, N'CA', N'YOW', N'Ottawa Airport'),
(1593, N'CA', N'YPA', N'Prince Albert Airport '),
(1594, N'CA', N'YPE', N'Peace River Airport'),
(1595, N'CA', N'YPR', N'Prince Rupert Airport'),
(1596, N'CA', N'YQB', N'Quebec City Airport'),
(1597, N'CA', N'YQG', N'Windsor Airport'),
(1598, N'CA', N'YQL', N'Lethbridge Airport'),
(1599, N'CA', N'YQM', N'Moncton Airport'),
(1600, N'CA', N'YQQ', N'Comox Airport'),
(1601, N'CA', N'YQR', N'Regina Airport'),
(1602, N'CA', N'YQT', N'Thunder Bay Airport'),
(1603, N'CA', N'YQU', N'Grande Prairie Airport'),
(1604, N'CA', N'YQX', N'Gander Airport'),
(1605, N'CA', N'YQY', N'Sydney Airport'),
(1606, N'CA', N'YRJ', N'Roberval Airport'),
(1607, N'CA', N'YRL', N'Red Lake Airport '),
(1608, N'CA', N'YSB', N'Sudbury Airport'),
(1609, N'CA', N'YSJ', N'Saint John Airport'),
(1610, N'CA', N'YSP', N'Marathon Flight Strip Airport '),
(1611, N'CA', N'YTH', N'Thompson Airport'),
(1612, N'CA', N'YTR', N'Trenton Airport'),
(1613, N'CA', N'YTS', N'Timmins Airport'),
(1614, N'CA', N'YTZ', N'Toronto Billy Bishop Airport'),
(1615, N'CA', N'YUL', N'Montreal Airport'),
(1616, N'US', N'YUM', N'Yuma Airport'),
(1617, N'CA', N'YUY', N'Rouyn Noranda Airport'),
(1618, N'CA', N'YVO', N'Val-d''Or Airport'),
(1619, N'CA', N'YVR', N'Vancouver Airport'),
(1620, N'CA', N'YWG', N'Winnipeg Airport'),
(1621, N'CA', N'YWK', N'Wabush Airport'),
(1622, N'CA', N'YWL', N'Williams Lake Airport'),
(1623, N'CA', N'YXC', N'Cranbrook Airport'),
(1624, N'CA', N'YXE', N'Saskatoon Airport'),
(1625, N'CA', N'YXJ', N'Fort Saint John Airport'),
(1626, N'CA', N'YXK', N'Rimouski Airport'),
(1627, N'CA', N'YXS', N'Prince George Airport'),
(1628, N'CA', N'YXT', N'Terrace Airport'),
(1629, N'CA', N'YXU', N'London Airport'),
(1630, N'CA', N'YXX', N'Abbotsford Airport'),
(1631, N'CA', N'YXY', N'Whitehorse International Airport '),
(1632, N'CA', N'YYB', N'North Bay Airport'),
(1633, N'CA', N'YYC', N'Calgary Airport'),
(1634, N'CA', N'YYD', N'Smithers Airport'),
(1635, N'CA', N'YYE', N'Fort Nelson Airport'),
(1636, N'CA', N'YYF', N'Penticton Airport'),
(1637, N'CA', N'YYG', N'Charlottetown Airport'),
(1638, N'CA', N'YYJ', N'Victoria Airport'),
(1639, N'CA', N'YYR', N'Happy Valley-Goose Bay Airport'),
(1640, N'CA', N'YYT', N'Saint Johns Airport'),
(1641, N'CA', N'YYY', N'Mont Joli Airport'),
(1642, N'CA', N'YYZ', N'Toronto Pearson Airport'),
(1643, N'CA', N'YZF', N'Yellowknife Airport'),
(1644, N'CA', N'YZR', N'Sarnia Airport '),
(1645, N'CA', N'YZT', N'Port Hardy Airport'),
(1646, N'CA', N'YZU', N'Whitecourt Airport'),
(1647, N'CA', N'YZV', N'Sept-Iles Airport'),
(1648, N'HR', N'ZAD', N'Zadar Airport'),
(1649, N'HR', N'ZAG', N'Zagreb Airport'),
(1650, N'CL', N'ZAL', N'Valdivia Airport'),
(1651, N'ES', N'ZAZ', N'Zaragoza Airport'),
(1652, N'AU', N'ZBF', N'Bathurst Airport '),
(1653, N'AU', N'ZBL', N'Biloela Airport '),
(1654, N'MX', N'ZCL', N'Zacatecas Airport'),
(1655, N'CL', N'ZCO', N'Temuco Airport'),
(1656, N'MX', N'ZIH', N'Ixtapa Airport'),
(1657, N'MX', N'ZLO', N'Manzanillo Playa de Oro International Airport'),
(1658, N'AU', N'ZNE', N'Newman Airport'),
(1659, N'TZ', N'ZNZ', N'Zanzibar International Airport'),
(1660, N'NZ', N'ZQN', N'Queenstown Airport'),
(1661, N'CH', N'ZRH', N'Zürich Airport'),
(1662, N'RE', N'ZSE', N'Saint Pierre Pierrefonds Airport'),
(1663, N'GR', N'ZTH', N'Zakynthos Airport');

DECLARE @Resolved TABLE (
    SourceOrder int NOT NULL,
    LangId int NOT NULL,
    CountryCode nvarchar(2) NOT NULL,
    Iata nvarchar(10) NOT NULL,
    LocationName nvarchar(200) NOT NULL,
    DuplicateRank int NOT NULL,
    LocalCountryId int NULL,
    CityId int NOT NULL,
    MatchedCityName nvarchar(100) NULL,
    CityMatchSource nvarchar(20) NOT NULL,
    ExistingLocationId int NULL,
    ExistingAnyLanguageLocationId int NULL
);

;WITH RankedAirports AS (
    SELECT
        a.SourceOrder,
        COALESCE(co.CountryCode, a.CountryCode) AS CountryCode,
        UPPER(LTRIM(RTRIM(a.Iata))) AS Iata,
        a.LocationName,
        ROW_NUMBER() OVER (
            PARTITION BY UPPER(LTRIM(RTRIM(a.Iata)))
            ORDER BY
                CASE WHEN co.Iata IS NOT NULL AND co.CountryCode = a.CountryCode THEN 0 ELSE 1 END,
                a.SourceOrder
        ) AS DuplicateRank
    FROM @Airports a
    LEFT JOIN @CountryOverrides co ON co.Iata = UPPER(LTRIM(RTRIM(a.Iata)))
)
INSERT INTO @Resolved (
    SourceOrder,
    LangId,
    CountryCode,
    Iata,
    LocationName,
    DuplicateRank,
    LocalCountryId,
    CityId,
    MatchedCityName,
    CityMatchSource,
    ExistingLocationId,
    ExistingAnyLanguageLocationId
)
SELECT
    a.SourceOrder,
    langs.LangId,
    a.CountryCode,
    a.Iata,
    a.LocationName,
    a.DuplicateRank,
    c.COUNTRYID AS LocalCountryId,
    COALESCE(cityOverride.CityId, matchedCity.CityId, @FallbackCityId) AS CityId,
    matchedCity.CityName AS MatchedCityName,
    CASE
        WHEN cityOverride.CityId IS NOT NULL THEN N'Override'
        WHEN matchedCity.CityId IS NOT NULL THEN N'CityName'
        ELSE N'Fallback'
    END AS CityMatchSource,
    existing.ID AS ExistingLocationId,
    existingAny.ID AS ExistingAnyLanguageLocationId
FROM RankedAirports a
CROSS JOIN @LangIds langs
LEFT JOIN COUNTRY c ON c.COUNTRYCODE2 = a.CountryCode
LEFT JOIN @CityOverrides cityOverride ON cityOverride.Iata = a.Iata
OUTER APPLY (
    SELECT TOP (1)
        ci.CITYID AS CityId,
        ci.CITYNAME AS CityName
    FROM CITY ci
    WHERE ci.COUNTRYID = c.COUNTRYID
        AND ci.CITYNAME IS NOT NULL
        AND LEN(LTRIM(RTRIM(ci.CITYNAME))) >= 3
        AND (
            a.LocationName COLLATE Latin1_General_CI_AI LIKE LTRIM(RTRIM(ci.CITYNAME)) COLLATE Latin1_General_CI_AI + N'%'
            OR a.LocationName COLLATE Latin1_General_CI_AI LIKE N'% ' + LTRIM(RTRIM(ci.CITYNAME)) COLLATE Latin1_General_CI_AI + N' %'
            OR a.LocationName COLLATE Latin1_General_CI_AI LIKE N'% ' + LTRIM(RTRIM(ci.CITYNAME)) COLLATE Latin1_General_CI_AI
        )
    ORDER BY
        CASE
            WHEN a.LocationName COLLATE Latin1_General_CI_AI LIKE LTRIM(RTRIM(ci.CITYNAME)) COLLATE Latin1_General_CI_AI + N'%' THEN 0
            ELSE 1
        END,
        LEN(LTRIM(RTRIM(ci.CITYNAME))) DESC,
        ci.CITYID
) matchedCity
LEFT JOIN LOCATION existing
    ON existing.LANGID = langs.LangId
    AND UPPER(LTRIM(RTRIM(existing.IATA))) = a.Iata
    AND ISNULL(existing.ISDELETED, 0) = 0
OUTER APPLY (
    SELECT TOP (1)
        locationInAnyLanguage.ID
    FROM LOCATION locationInAnyLanguage
    WHERE UPPER(LTRIM(RTRIM(locationInAnyLanguage.IATA))) = a.Iata
        AND ISNULL(locationInAnyLanguage.ISDELETED, 0) = 0
    ORDER BY locationInAnyLanguage.ID
) existingAny;

SELECT
    N'DuplicateIata' AS ReportType,
    Iata,
    COUNT(*) AS DuplicateCount,
    STRING_AGG(CONCAT(CountryCode, N': ', LocationName), N' | ') AS Candidates
FROM @Resolved
WHERE LangId = (SELECT MIN(LangId) FROM @LangIds)
GROUP BY Iata
HAVING COUNT(*) > 1
ORDER BY Iata;

SELECT
    N'MissingCountry' AS ReportType,
    CountryCode,
    COUNT(*) AS AirportCount
FROM @Resolved
WHERE LangId = (SELECT MIN(LangId) FROM @LangIds)
    AND DuplicateRank = 1
    AND LocalCountryId IS NULL
GROUP BY CountryCode
ORDER BY CountryCode;

SELECT
    N'AlreadyExists' AS ReportType,
    LangId,
    Iata,
    ExistingLocationId,
    ExistingAnyLanguageLocationId,
    LocationName,
    CountryCode,
    LocalCountryId
FROM @Resolved
WHERE DuplicateRank = 1 AND ExistingLocationId IS NOT NULL
ORDER BY Iata;

SELECT
    N'CityFallback' AS ReportType,
    LangId,
    Iata,
    LocationName,
    CountryCode,
    LocalCountryId,
    CityId
FROM @Resolved
WHERE DuplicateRank = 1
    AND LocalCountryId IS NOT NULL
    AND CityMatchSource = N'Fallback'
ORDER BY Iata;

SELECT
    N'WillInsert' AS ReportType,
    LangId,
    Iata,
    LocationName,
    CountryCode,
    LocalCountryId,
    CityId,
    CityMatchSource,
    MatchedCityName
FROM @Resolved
WHERE DuplicateRank = 1
    AND ExistingLocationId IS NULL
    AND LocalCountryId IS NOT NULL
ORDER BY Iata;

IF @DoInsert = 1
BEGIN
    BEGIN TRANSACTION;

    DECLARE @StartId int = (
        SELECT ISNULL(MAX(ID), 0)
        FROM LOCATION WITH (UPDLOCK, HOLDLOCK)
    );

    ;WITH InsertCandidates AS (
        SELECT
            r.*
        FROM @Resolved r
        WHERE r.DuplicateRank = 1
            AND r.ExistingLocationId IS NULL
            AND r.LocalCountryId IS NOT NULL
    ),
    NewLocationGroups AS (
        SELECT
            newGroups.Iata,
            newGroups.SourceOrder,
            @StartId + ROW_NUMBER() OVER (ORDER BY newGroups.Iata, newGroups.SourceOrder) AS NewLocationId
        FROM (
            SELECT DISTINCT
                Iata,
                SourceOrder
            FROM InsertCandidates
            WHERE ExistingAnyLanguageLocationId IS NULL
        ) newGroups
    ),
    Insertable AS (
        SELECT
            candidates.*,
            COALESCE(candidates.ExistingAnyLanguageLocationId, groups.NewLocationId) AS LocationIdToInsert
        FROM InsertCandidates candidates
        LEFT JOIN NewLocationGroups groups
            ON groups.Iata = candidates.Iata
            AND groups.SourceOrder = candidates.SourceOrder
    )
    INSERT INTO LOCATION (
        ID,
        ACTIVE,
        LANGID,
        COUNTRYID,
        CITYID,
        LOCATIONNAME,
        IATA,
        AIRPORT,
        ISPICKUP,
        MAILADDRESS,
        ADDRESS,
        PHONENUMBER,
        COORDINATELATITUDE,
        COORDINATELONGITUDE,
        ISPOPULAR,
        IMAGEPATH,
        LOCATIONORDER,
        ISDEFAULT,
        ISCITYDEFAULTLOCATION,
        GOOGLEPLACEID,
        STATEID,
        ISDELETED
    )
    SELECT
        LocationIdToInsert,
        1,
        LangId,
        LocalCountryId,
        CityId,
        LEFT(LocationName, 200),
        Iata,
        1,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        0,
        NULL,
        NULL,
        NULL,
        0
    FROM Insertable
    ORDER BY Iata, SourceOrder, LangId;

    SELECT @@ROWCOUNT AS InsertedCount;

    COMMIT TRANSACTION;
END
ELSE
BEGIN
    SELECT N'PreviewOnly' AS Status, COUNT(*) AS InsertCandidateCount
    FROM @Resolved
    WHERE DuplicateRank = 1
        AND ExistingLocationId IS NULL
        AND LocalCountryId IS NOT NULL;
END
