// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AdditionsEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Additions",
                typeof(Additions),
                baseEntityType,
                propertyCount: 14,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Additions).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "ID");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var additionname = runtimeEntityType.AddProperty(
                "Additionname",
                typeof(string),
                propertyInfo: typeof(Additions).GetProperty("Additionname", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Additionname>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            additionname.AddAnnotation("Relational:ColumnName", "ADDITIONNAME");
            additionname.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var additionstatustype = runtimeEntityType.AddProperty(
                "Additionstatustype",
                typeof(int),
                propertyInfo: typeof(Additions).GetProperty("Additionstatustype", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Additionstatustype>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            additionstatustype.AddAnnotation("Relational:ColumnName", "ADDITIONSTATUSTYPE");
            additionstatustype.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var additiontypeid = runtimeEntityType.AddProperty(
                "Additiontypeid",
                typeof(int),
                propertyInfo: typeof(Additions).GetProperty("Additiontypeid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Additiontypeid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            additiontypeid.AddAnnotation("Relational:ColumnName", "ADDITIONTYPEID");
            additiontypeid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var agencyamount = runtimeEntityType.AddProperty(
                "Agencyamount",
                typeof(decimal?),
                propertyInfo: typeof(Additions).GetProperty("Agencyamount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Agencyamount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            agencyamount.AddAnnotation("Relational:ColumnName", "AGENCYAMOUNT");
            agencyamount.AddAnnotation("Relational:ColumnType", "decimal(18, 2)");
            agencyamount.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var agencycurrencyid = runtimeEntityType.AddProperty(
                "Agencycurrencyid",
                typeof(int?),
                propertyInfo: typeof(Additions).GetProperty("Agencycurrencyid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Agencycurrencyid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            agencycurrencyid.AddAnnotation("Relational:ColumnName", "AGENCYCURRENCYID");
            agencycurrencyid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var createdate = runtimeEntityType.AddProperty(
                "Createdate",
                typeof(DateTime?),
                propertyInfo: typeof(Additions).GetProperty("Createdate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Createdate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            createdate.AddAnnotation("Relational:ColumnName", "CREATEDATE");
            createdate.AddAnnotation("Relational:ColumnType", "datetime");
            createdate.AddAnnotation("Relational:DefaultValueSql", "(getdate())");
            createdate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(Additions).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            description.AddAnnotation("Relational:ColumnName", "DESCRIPTION");
            description.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var laststatuschangedate = runtimeEntityType.AddProperty(
                "Laststatuschangedate",
                typeof(DateTime?),
                propertyInfo: typeof(Additions).GetProperty("Laststatuschangedate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Laststatuschangedate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            laststatuschangedate.AddAnnotation("Relational:ColumnName", "LASTSTATUSCHANGEDATE");
            laststatuschangedate.AddAnnotation("Relational:ColumnType", "datetime");
            laststatuschangedate.AddAnnotation("Relational:DefaultValueSql", "(getdate())");
            laststatuschangedate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var laststatuschangeuserid = runtimeEntityType.AddProperty(
                "Laststatuschangeuserid",
                typeof(int?),
                propertyInfo: typeof(Additions).GetProperty("Laststatuschangeuserid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Laststatuschangeuserid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            laststatuschangeuserid.AddAnnotation("Relational:ColumnName", "LASTSTATUSCHANGEUSERID");
            laststatuschangeuserid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationnumber = runtimeEntityType.AddProperty(
                "Reservationnumber",
                typeof(string),
                propertyInfo: typeof(Additions).GetProperty("Reservationnumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Reservationnumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            reservationnumber.AddAnnotation("Relational:ColumnName", "RESERVATIONNUMBER");
            reservationnumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var userid = runtimeEntityType.AddProperty(
                "Userid",
                typeof(int),
                propertyInfo: typeof(Additions).GetProperty("Userid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Userid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            userid.AddAnnotation("Relational:ColumnName", "USERID");
            userid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendoramount = runtimeEntityType.AddProperty(
                "Vendoramount",
                typeof(decimal?),
                propertyInfo: typeof(Additions).GetProperty("Vendoramount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Vendoramount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vendoramount.AddAnnotation("Relational:ColumnName", "VENDORAMOUNT");
            vendoramount.AddAnnotation("Relational:ColumnType", "decimal(18, 2)");
            vendoramount.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorcurrencyid = runtimeEntityType.AddProperty(
                "Vendorcurrencyid",
                typeof(int?),
                propertyInfo: typeof(Additions).GetProperty("Vendorcurrencyid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additions).GetField("<Vendorcurrencyid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vendorcurrencyid.AddAnnotation("Relational:ColumnName", "VENDORCURRENCYID");
            vendorcurrencyid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ADDITIONS");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
