// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AdditionalproductpriceEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Additionalproductprice",
                typeof(Additionalproductprice),
                baseEntityType,
                propertyCount: 7,
                keyCount: 1);

            var additionalproductvendorid = runtimeEntityType.AddProperty(
                "Additionalproductvendorid",
                typeof(int),
                propertyInfo: typeof(Additionalproductprice).GetProperty("Additionalproductvendorid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additionalproductprice).GetField("<Additionalproductvendorid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            additionalproductvendorid.AddAnnotation("Relational:ColumnName", "ADDITIONALPRODUCTVENDORID");
            additionalproductvendorid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var productid = runtimeEntityType.AddProperty(
                "Productid",
                typeof(int),
                propertyInfo: typeof(Additionalproductprice).GetProperty("Productid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additionalproductprice).GetField("<Productid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            productid.AddAnnotation("Relational:ColumnName", "PRODUCTID");
            productid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorid = runtimeEntityType.AddProperty(
                "Vendorid",
                typeof(int),
                propertyInfo: typeof(Additionalproductprice).GetProperty("Vendorid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additionalproductprice).GetField("<Vendorid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            vendorid.AddAnnotation("Relational:ColumnName", "VENDORID");
            vendorid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var startday = runtimeEntityType.AddProperty(
                "Startday",
                typeof(int),
                propertyInfo: typeof(Additionalproductprice).GetProperty("Startday", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additionalproductprice).GetField("<Startday>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            startday.AddAnnotation("Relational:ColumnName", "STARTDAY");
            startday.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var endday = runtimeEntityType.AddProperty(
                "Endday",
                typeof(int),
                propertyInfo: typeof(Additionalproductprice).GetProperty("Endday", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additionalproductprice).GetField("<Endday>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            endday.AddAnnotation("Relational:ColumnName", "ENDDAY");
            endday.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var currencyid = runtimeEntityType.AddProperty(
                "Currencyid",
                typeof(int),
                propertyInfo: typeof(Additionalproductprice).GetProperty("Currencyid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additionalproductprice).GetField("<Currencyid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            currencyid.AddAnnotation("Relational:ColumnName", "CURRENCYID");
            currencyid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var price = runtimeEntityType.AddProperty(
                "Price",
                typeof(decimal?),
                propertyInfo: typeof(Additionalproductprice).GetProperty("Price", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Additionalproductprice).GetField("<Price>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            price.AddAnnotation("Relational:ColumnName", "PRICE");
            price.AddAnnotation("Relational:ColumnType", "decimal(18, 2)");
            price.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { additionalproductvendorid, productid, vendorid, startday, endday });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ADDITIONALPRODUCTPRICE");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
