// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AgencyvendorpaymentoptionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Agencyvendorpaymentoption",
                typeof(Agencyvendorpaymentoption),
                baseEntityType,
                propertyCount: 11,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "ID");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var additionalproductamountdeliverypayment = runtimeEntityType.AddProperty(
                "Additionalproductamountdeliverypayment",
                typeof(bool?),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Additionalproductamountdeliverypayment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Additionalproductamountdeliverypayment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            additionalproductamountdeliverypayment.AddAnnotation("Relational:ColumnName", "ADDITIONALPRODUCTAMOUNTDELIVERYPAYMENT");
            additionalproductamountdeliverypayment.AddAnnotation("Relational:DefaultValueSql", "((0))");
            additionalproductamountdeliverypayment.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var advancepaymentactive = runtimeEntityType.AddProperty(
                "Advancepaymentactive",
                typeof(bool),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Advancepaymentactive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Advancepaymentactive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            advancepaymentactive.AddAnnotation("Relational:ColumnName", "ADVANCEPAYMENTACTIVE");
            advancepaymentactive.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var agencyid = runtimeEntityType.AddProperty(
                "Agencyid",
                typeof(int),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Agencyid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Agencyid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            agencyid.AddAnnotation("Relational:ColumnName", "AGENCYID");
            agencyid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var commissionfreepaymentactive = runtimeEntityType.AddProperty(
                "Commissionfreepaymentactive",
                typeof(bool),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Commissionfreepaymentactive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Commissionfreepaymentactive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            commissionfreepaymentactive.AddAnnotation("Relational:ColumnName", "COMMISSIONFREEPAYMENTACTIVE");
            commissionfreepaymentactive.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var creditcardpaymentactive = runtimeEntityType.AddProperty(
                "Creditcardpaymentactive",
                typeof(bool),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Creditcardpaymentactive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Creditcardpaymentactive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            creditcardpaymentactive.AddAnnotation("Relational:ColumnName", "CREDITCARDPAYMENTACTIVE");
            creditcardpaymentactive.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var onewayamountdeliverypayment = runtimeEntityType.AddProperty(
                "Onewayamountdeliverypayment",
                typeof(bool?),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Onewayamountdeliverypayment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Onewayamountdeliverypayment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            onewayamountdeliverypayment.AddAnnotation("Relational:ColumnName", "ONEWAYAMOUNTDELIVERYPAYMENT");
            onewayamountdeliverypayment.AddAnnotation("Relational:DefaultValueSql", "((0))");
            onewayamountdeliverypayment.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var payagencyactive = runtimeEntityType.AddProperty(
                "Payagencyactive",
                typeof(bool),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Payagencyactive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Payagencyactive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            payagencyactive.AddAnnotation("Relational:ColumnName", "PAYAGENCYACTIVE");
            payagencyactive.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var payallactive = runtimeEntityType.AddProperty(
                "Payallactive",
                typeof(bool),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Payallactive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Payallactive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            payallactive.AddAnnotation("Relational:ColumnName", "PAYALLACTIVE");
            payallactive.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var paydeliveryactive = runtimeEntityType.AddProperty(
                "Paydeliveryactive",
                typeof(bool),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Paydeliveryactive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Paydeliveryactive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            paydeliveryactive.AddAnnotation("Relational:ColumnName", "PAYDELIVERYACTIVE");
            paydeliveryactive.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorid = runtimeEntityType.AddProperty(
                "Vendorid",
                typeof(int),
                propertyInfo: typeof(Agencyvendorpaymentoption).GetProperty("Vendorid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agencyvendorpaymentoption).GetField("<Vendorid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            vendorid.AddAnnotation("Relational:ColumnName", "VENDORID");
            vendorid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AGENCYVENDORPAYMENTOPTION");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
