// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AyarEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Ayar",
                typeof(Ayar),
                baseEntityType,
                propertyCount: 14,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Ayar).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "ID");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var autorateactive = runtimeEntityType.AddProperty(
                "Autorateactive",
                typeof(bool),
                propertyInfo: typeof(Ayar).GetProperty("Autorateactive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Autorateactive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            autorateactive.AddAnnotation("Relational:ColumnName", "AUTORATEACTIVE");
            autorateactive.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var googleanalytics = runtimeEntityType.AddProperty(
                "Googleanalytics",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Googleanalytics", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Googleanalytics>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            googleanalytics.AddAnnotation("Relational:ColumnName", "GOOGLEANALYTICS");
            googleanalytics.AddAnnotation("Relational:ColumnType", "ntext");
            googleanalytics.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var googleconversion = runtimeEntityType.AddProperty(
                "Googleconversion",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Googleconversion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Googleconversion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            googleconversion.AddAnnotation("Relational:ColumnName", "GOOGLECONVERSION");
            googleconversion.AddAnnotation("Relational:ColumnType", "ntext");
            googleconversion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var googlediger = runtimeEntityType.AddProperty(
                "Googlediger",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Googlediger", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Googlediger>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            googlediger.AddAnnotation("Relational:ColumnName", "GOOGLEDIGER");
            googlediger.AddAnnotation("Relational:ColumnType", "ntext");
            googlediger.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var googledogrulama = runtimeEntityType.AddProperty(
                "Googledogrulama",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Googledogrulama", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Googledogrulama>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            googledogrulama.AddAnnotation("Relational:ColumnName", "GOOGLEDOGRULAMA");
            googledogrulama.AddAnnotation("Relational:ColumnType", "ntext");
            googledogrulama.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var googleremarketing = runtimeEntityType.AddProperty(
                "Googleremarketing",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Googleremarketing", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Googleremarketing>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            googleremarketing.AddAnnotation("Relational:ColumnName", "GOOGLEREMARKETING");
            googleremarketing.AddAnnotation("Relational:ColumnType", "ntext");
            googleremarketing.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var smtpmail = runtimeEntityType.AddProperty(
                "Smtpmail",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Smtpmail", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Smtpmail>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            smtpmail.AddAnnotation("Relational:ColumnName", "SMTPMAIL");
            smtpmail.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var smtpmailalici = runtimeEntityType.AddProperty(
                "Smtpmailalici",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Smtpmailalici", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Smtpmailalici>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            smtpmailalici.AddAnnotation("Relational:ColumnName", "SMTPMAILALICI");
            smtpmailalici.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var smtpport = runtimeEntityType.AddProperty(
                "Smtpport",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Smtpport", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Smtpport>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            smtpport.AddAnnotation("Relational:ColumnName", "SMTPPORT");
            smtpport.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var smtppwd = runtimeEntityType.AddProperty(
                "Smtppwd",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Smtppwd", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Smtppwd>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            smtppwd.AddAnnotation("Relational:ColumnName", "SMTPPWD");
            smtppwd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var smtpssl = runtimeEntityType.AddProperty(
                "Smtpssl",
                typeof(bool?),
                propertyInfo: typeof(Ayar).GetProperty("Smtpssl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Smtpssl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            smtpssl.AddAnnotation("Relational:ColumnName", "SMTPSSL");
            smtpssl.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var smtpsunucu = runtimeEntityType.AddProperty(
                "Smtpsunucu",
                typeof(string),
                propertyInfo: typeof(Ayar).GetProperty("Smtpsunucu", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Smtpsunucu>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            smtpsunucu.AddAnnotation("Relational:ColumnName", "SMTPSUNUCU");
            smtpsunucu.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sslaktif = runtimeEntityType.AddProperty(
                "Sslaktif",
                typeof(bool?),
                propertyInfo: typeof(Ayar).GetProperty("Sslaktif", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Ayar).GetField("<Sslaktif>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            sslaktif.AddAnnotation("Relational:ColumnName", "SSLAKTIF");
            sslaktif.AddAnnotation("Relational:DefaultValueSql", "((0))");
            sslaktif.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AYAR");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
