// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class BasvuruEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Basvuru",
                typeof(Basvuru),
                baseEntityType,
                propertyCount: 19,
                keyCount: 1);

            var basvuruid = runtimeEntityType.AddProperty(
                "Basvuruid",
                typeof(int),
                propertyInfo: typeof(Basvuru).GetProperty("Basvuruid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Basvuruid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            basvuruid.AddAnnotation("Relational:ColumnName", "BASVURUID");
            basvuruid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var aciklama = runtimeEntityType.AddProperty(
                "Aciklama",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Aciklama", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Aciklama>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            aciklama.AddAnnotation("Relational:ColumnName", "ACIKLAMA");
            aciklama.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var adres = runtimeEntityType.AddProperty(
                "Adres",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Adres", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Adres>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            adres.AddAnnotation("Relational:ColumnName", "ADRES");
            adres.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var aracsayisi = runtimeEntityType.AddProperty(
                "Aracsayisi",
                typeof(int?),
                propertyInfo: typeof(Basvuru).GetProperty("Aracsayisi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Aracsayisi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            aracsayisi.AddAnnotation("Relational:ColumnName", "ARACSAYISI");
            aracsayisi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var benzinmanuel = runtimeEntityType.AddProperty(
                "Benzinmanuel",
                typeof(int?),
                propertyInfo: typeof(Basvuru).GetProperty("Benzinmanuel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Benzinmanuel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            benzinmanuel.AddAnnotation("Relational:ColumnName", "BENZINMANUEL");
            benzinmanuel.AddAnnotation("Relational:DefaultValueSql", "((0))");
            benzinmanuel.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var benzinotomatik = runtimeEntityType.AddProperty(
                "Benzinotomatik",
                typeof(int?),
                propertyInfo: typeof(Basvuru).GetProperty("Benzinotomatik", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Benzinotomatik>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            benzinotomatik.AddAnnotation("Relational:ColumnName", "BENZINOTOMATIK");
            benzinotomatik.AddAnnotation("Relational:DefaultValueSql", "((0))");
            benzinotomatik.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dizelmanuel = runtimeEntityType.AddProperty(
                "Dizelmanuel",
                typeof(int?),
                propertyInfo: typeof(Basvuru).GetProperty("Dizelmanuel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Dizelmanuel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            dizelmanuel.AddAnnotation("Relational:ColumnName", "DIZELMANUEL");
            dizelmanuel.AddAnnotation("Relational:DefaultValueSql", "((0))");
            dizelmanuel.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dizelotomatik = runtimeEntityType.AddProperty(
                "Dizelotomatik",
                typeof(int?),
                propertyInfo: typeof(Basvuru).GetProperty("Dizelotomatik", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Dizelotomatik>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            dizelotomatik.AddAnnotation("Relational:ColumnName", "DIZELOTOMATIK");
            dizelotomatik.AddAnnotation("Relational:DefaultValueSql", "((0))");
            dizelotomatik.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var email = runtimeEntityType.AddProperty(
                "Email",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Email", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Email>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            email.AddAnnotation("Relational:ColumnName", "EMAIL");
            email.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var firmaadi = runtimeEntityType.AddProperty(
                "Firmaadi",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Firmaadi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Firmaadi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            firmaadi.AddAnnotation("Relational:ColumnName", "FIRMAADI");
            firmaadi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var firmasahibiadi = runtimeEntityType.AddProperty(
                "Firmasahibiadi",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Firmasahibiadi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Firmasahibiadi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            firmasahibiadi.AddAnnotation("Relational:ColumnName", "FIRMASAHIBIADI");
            firmasahibiadi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var firmasahibisoyadi = runtimeEntityType.AddProperty(
                "Firmasahibisoyadi",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Firmasahibisoyadi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Firmasahibisoyadi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            firmasahibisoyadi.AddAnnotation("Relational:ColumnName", "FIRMASAHIBISOYADI");
            firmasahibisoyadi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var goruldu = runtimeEntityType.AddProperty(
                "Goruldu",
                typeof(bool?),
                propertyInfo: typeof(Basvuru).GetProperty("Goruldu", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Goruldu>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            goruldu.AddAnnotation("Relational:ColumnName", "GORULDU");
            goruldu.AddAnnotation("Relational:DefaultValueSql", "((0))");
            goruldu.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ip = runtimeEntityType.AddProperty(
                "Ip",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Ip", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Ip>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            ip.AddAnnotation("Relational:ColumnName", "IP");
            ip.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sehir = runtimeEntityType.AddProperty(
                "Sehir",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Sehir", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Sehir>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            sehir.AddAnnotation("Relational:ColumnName", "SEHIR");
            sehir.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tarih = runtimeEntityType.AddProperty(
                "Tarih",
                typeof(DateTime?),
                propertyInfo: typeof(Basvuru).GetProperty("Tarih", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Tarih>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            tarih.AddAnnotation("Relational:ColumnName", "TARIH");
            tarih.AddAnnotation("Relational:ColumnType", "datetime");
            tarih.AddAnnotation("Relational:DefaultValueSql", "(getdate())");
            tarih.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var telefon = runtimeEntityType.AddProperty(
                "Telefon",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Telefon", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Telefon>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            telefon.AddAnnotation("Relational:ColumnName", "TELEFON");
            telefon.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vergidairesi = runtimeEntityType.AddProperty(
                "Vergidairesi",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Vergidairesi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Vergidairesi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vergidairesi.AddAnnotation("Relational:ColumnName", "VERGIDAIRESI");
            vergidairesi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var verginumarasi = runtimeEntityType.AddProperty(
                "Verginumarasi",
                typeof(string),
                propertyInfo: typeof(Basvuru).GetProperty("Verginumarasi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Basvuru).GetField("<Verginumarasi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            verginumarasi.AddAnnotation("Relational:ColumnName", "VERGINUMARASI");
            verginumarasi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { basvuruid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "BASVURU");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
