// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class DilEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Dil",
                typeof(Dil),
                baseEntityType,
                propertyCount: 8,
                keyCount: 1);

            var dilid = runtimeEntityType.AddProperty(
                "Dilid",
                typeof(int),
                propertyInfo: typeof(Dil).GetProperty("Dilid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Dil).GetField("<Dilid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            dilid.AddAnnotation("Relational:ColumnName", "DILID");
            dilid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dilkod = runtimeEntityType.AddProperty(
                "Dilkod",
                typeof(string),
                propertyInfo: typeof(Dil).GetProperty("Dilkod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Dil).GetField("<Dilkod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 2);
            dilkod.AddAnnotation("Relational:ColumnName", "DILKOD");
            dilkod.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var aktif = runtimeEntityType.AddProperty(
                "Aktif",
                typeof(bool?),
                propertyInfo: typeof(Dil).GetProperty("Aktif", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Dil).GetField("<Aktif>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            aktif.AddAnnotation("Relational:ColumnName", "AKTIF");
            aktif.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var bayrak = runtimeEntityType.AddProperty(
                "Bayrak",
                typeof(string),
                propertyInfo: typeof(Dil).GetProperty("Bayrak", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Dil).GetField("<Bayrak>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            bayrak.AddAnnotation("Relational:ColumnName", "BAYRAK");
            bayrak.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var culture = runtimeEntityType.AddProperty(
                "Culture",
                typeof(string),
                propertyInfo: typeof(Dil).GetProperty("Culture", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Dil).GetField("<Culture>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            culture.AddAnnotation("Relational:ColumnName", "KULTUR");
            culture.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dilad = runtimeEntityType.AddProperty(
                "Dilad",
                typeof(string),
                propertyInfo: typeof(Dil).GetProperty("Dilad", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Dil).GetField("<Dilad>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            dilad.AddAnnotation("Relational:ColumnName", "DILAD");
            dilad.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var gorunurad = runtimeEntityType.AddProperty(
                "Gorunurad",
                typeof(string),
                propertyInfo: typeof(Dil).GetProperty("Gorunurad", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Dil).GetField("<Gorunurad>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            gorunurad.AddAnnotation("Relational:ColumnName", "GORUNURAD");
            gorunurad.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var isLtr = runtimeEntityType.AddProperty(
                "IsLtr",
                typeof(bool?),
                propertyInfo: typeof(Dil).GetProperty("IsLtr", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Dil).GetField("<IsLtr>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            isLtr.AddAnnotation("Relational:ColumnName", "LTR");
            isLtr.AddAnnotation("Relational:DefaultValue", false);
            isLtr.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { dilid, dilkod });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "DIL");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
