// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IcerikdilEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Icerikdil",
                typeof(Icerikdil),
                baseEntityType,
                propertyCount: 17,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var icerikid = runtimeEntityType.AddProperty(
                "Icerikid",
                typeof(int),
                propertyInfo: typeof(Icerikdil).GetProperty("Icerikid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Icerikid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            icerikid.AddAnnotation("Relational:ColumnName", "ICERIKID");
            icerikid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dilid = runtimeEntityType.AddProperty(
                "Dilid",
                typeof(int),
                propertyInfo: typeof(Icerikdil).GetProperty("Dilid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Dilid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            dilid.AddAnnotation("Relational:ColumnName", "DILID");
            dilid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var aktifmi = runtimeEntityType.AddProperty(
                "Aktifmi",
                typeof(bool?),
                propertyInfo: typeof(Icerikdil).GetProperty("Aktifmi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Aktifmi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            aktifmi.AddAnnotation("Relational:ColumnName", "AKTIFMI");
            aktifmi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var baslangicTarihi = runtimeEntityType.AddProperty(
                "BaslangicTarihi",
                typeof(DateTime?),
                propertyInfo: typeof(Icerikdil).GetProperty("BaslangicTarihi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<BaslangicTarihi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            baslangicTarihi.AddAnnotation("Relational:ColumnName", "BASLANGICTARIHI");
            baslangicTarihi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var baslik = runtimeEntityType.AddProperty(
                "Baslik",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Baslik", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Baslik>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 250);
            baslik.AddAnnotation("Relational:ColumnName", "BASLIK");
            baslik.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var bitisTarihi = runtimeEntityType.AddProperty(
                "BitisTarihi",
                typeof(DateTime?),
                propertyInfo: typeof(Icerikdil).GetProperty("BitisTarihi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<BitisTarihi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            bitisTarihi.AddAnnotation("Relational:ColumnName", "BITISTARIHI");
            bitisTarihi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var canonical = runtimeEntityType.AddProperty(
                "Canonical",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Canonical", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Canonical>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            canonical.AddAnnotation("Relational:ColumnName", "CANONICAL");
            canonical.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var contenturl = runtimeEntityType.AddProperty(
                "Contenturl",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Contenturl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Contenturl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            contenturl.AddAnnotation("Relational:ColumnName", "CONTENTURL");
            contenturl.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            description.AddAnnotation("Relational:ColumnName", "DESCRIPTION");
            description.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var editor = runtimeEntityType.AddProperty(
                "Editor",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Editor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Editor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            editor.AddAnnotation("Relational:ColumnName", "EDITOR");
            editor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var keyword = runtimeEntityType.AddProperty(
                "Keyword",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Keyword", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Keyword>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            keyword.AddAnnotation("Relational:ColumnName", "KEYWORD");
            keyword.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var link = runtimeEntityType.AddProperty(
                "Link",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Link", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Link>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            link.AddAnnotation("Relational:ColumnName", "LINK");
            link.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ozet = runtimeEntityType.AddProperty(
                "Ozet",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Ozet", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Ozet>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            ozet.AddAnnotation("Relational:ColumnName", "OZET");
            ozet.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resim = runtimeEntityType.AddProperty(
                "Resim",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Resim", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Resim>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            resim.AddAnnotation("Relational:ColumnName", "RESIM");
            resim.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resimalt = runtimeEntityType.AddProperty(
                "Resimalt",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Resimalt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Resimalt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            resimalt.AddAnnotation("Relational:ColumnName", "RESIMALT");
            resimalt.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var syncicerikid = runtimeEntityType.AddProperty(
                "Syncicerikid",
                typeof(int?),
                propertyInfo: typeof(Icerikdil).GetProperty("Syncicerikid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Syncicerikid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            syncicerikid.AddAnnotation("Relational:ColumnName", "SYNCICERIKID");
            syncicerikid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var title = runtimeEntityType.AddProperty(
                "Title",
                typeof(string),
                propertyInfo: typeof(Icerikdil).GetProperty("Title", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Title>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 250);
            title.AddAnnotation("Relational:ColumnName", "TITLE");
            title.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { icerikid, dilid });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { dilid, contenturl },
                unique: true);
            index.AddAnnotation("Relational:Filter", "[CONTENTURL] IS NOT NULL");
            index.AddAnnotation("Relational:Name", "UI_ICERIKDIL_CONTENTURL");

            var index0 = runtimeEntityType.AddIndex(
                new[] { dilid, baslik, icerikid });
            index0.AddAnnotation("Relational:Name", "missing_index_211");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("Icerikid") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Icerikid") }),
                principalEntityType,
                required: true);

            var icerik = declaringEntityType.AddNavigation("Icerik",
                runtimeForeignKey,
                onDependent: true,
                typeof(Icerik),
                propertyInfo: typeof(Icerikdil).GetProperty("Icerik", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerikdil).GetField("<Icerik>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var icerikDiller = principalEntityType.AddNavigation("IcerikDiller",
                runtimeForeignKey,
                onDependent: false,
                typeof(IEnumerable<Icerikdil>),
                propertyInfo: typeof(Icerik).GetProperty("IcerikDiller", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Icerik).GetField("<IcerikDiller>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ICERIKDIL");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
