// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class LabelEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Label",
                typeof(Label),
                baseEntityType,
                propertyCount: 4,
                keyCount: 1);

            var labelid = runtimeEntityType.AddProperty(
                "Labelid",
                typeof(int),
                propertyInfo: typeof(Label).GetProperty("Labelid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Label).GetField("<Labelid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            labelid.AddAnnotation("Relational:ColumnName", "LABELID");
            labelid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dilid = runtimeEntityType.AddProperty(
                "Dilid",
                typeof(int),
                propertyInfo: typeof(Label).GetProperty("Dilid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Label).GetField("<Dilid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            dilid.AddAnnotation("Relational:ColumnName", "DILID");
            dilid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var labelKodu = runtimeEntityType.AddProperty(
                "LabelKodu",
                typeof(string),
                propertyInfo: typeof(Label).GetProperty("LabelKodu", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Label).GetField("<LabelKodu>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            labelKodu.AddAnnotation("Relational:ColumnName", "LABELKODU");
            labelKodu.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var labeladi = runtimeEntityType.AddProperty(
                "Labeladi",
                typeof(string),
                propertyInfo: typeof(Label).GetProperty("Labeladi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Label).GetField("<Labeladi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            labeladi.AddAnnotation("Relational:ColumnName", "LABELADI");
            labeladi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { labelid, dilid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "LABEL");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
