// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class LocationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Location",
                typeof(Location),
                baseEntityType,
                propertyCount: 16,
                navigationCount: 1,
                unnamedIndexCount: 2,
                keyCount: 2);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Location).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "ID");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var langid = runtimeEntityType.AddProperty(
                "Langid",
                typeof(int),
                propertyInfo: typeof(Location).GetProperty("Langid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Langid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            langid.AddAnnotation("Relational:ColumnName", "LANGID");
            langid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var active = runtimeEntityType.AddProperty(
                "Active",
                typeof(bool?),
                propertyInfo: typeof(Location).GetProperty("Active", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Active>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            active.AddAnnotation("Relational:ColumnName", "ACTIVE");
            active.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var address = runtimeEntityType.AddProperty(
                "Address",
                typeof(string),
                propertyInfo: typeof(Location).GetProperty("Address", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Address>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            address.AddAnnotation("Relational:ColumnName", "ADDRESS");
            address.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var airport = runtimeEntityType.AddProperty(
                "Airport",
                typeof(bool?),
                propertyInfo: typeof(Location).GetProperty("Airport", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Airport>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            airport.AddAnnotation("Relational:ColumnName", "AIRPORT");
            airport.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var cityid = runtimeEntityType.AddProperty(
                "Cityid",
                typeof(int),
                propertyInfo: typeof(Location).GetProperty("Cityid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Cityid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            cityid.AddAnnotation("Relational:ColumnName", "CITYID");
            cityid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var coordinatelatitude = runtimeEntityType.AddProperty(
                "Coordinatelatitude",
                typeof(string),
                propertyInfo: typeof(Location).GetProperty("Coordinatelatitude", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Coordinatelatitude>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            coordinatelatitude.AddAnnotation("Relational:ColumnName", "COORDINATELATITUDE");
            coordinatelatitude.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var coordinatelongitude = runtimeEntityType.AddProperty(
                "Coordinatelongitude",
                typeof(string),
                propertyInfo: typeof(Location).GetProperty("Coordinatelongitude", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Coordinatelongitude>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            coordinatelongitude.AddAnnotation("Relational:ColumnName", "COORDINATELONGITUDE");
            coordinatelongitude.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var countryid = runtimeEntityType.AddProperty(
                "Countryid",
                typeof(int),
                propertyInfo: typeof(Location).GetProperty("Countryid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Countryid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            countryid.AddAnnotation("Relational:ColumnName", "COUNTRYID");
            countryid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var iata = runtimeEntityType.AddProperty(
                "Iata",
                typeof(string),
                propertyInfo: typeof(Location).GetProperty("Iata", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Iata>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            iata.AddAnnotation("Relational:ColumnName", "IATA");
            iata.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var imagepath = runtimeEntityType.AddProperty(
                "Imagepath",
                typeof(string),
                propertyInfo: typeof(Location).GetProperty("Imagepath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Imagepath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            imagepath.AddAnnotation("Relational:ColumnName", "IMAGEPATH");
            imagepath.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ispickup = runtimeEntityType.AddProperty(
                "Ispickup",
                typeof(bool?),
                propertyInfo: typeof(Location).GetProperty("Ispickup", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Ispickup>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            ispickup.AddAnnotation("Relational:ColumnName", "ISPICKUP");
            ispickup.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ispopular = runtimeEntityType.AddProperty(
                "Ispopular",
                typeof(bool?),
                propertyInfo: typeof(Location).GetProperty("Ispopular", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Ispopular>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            ispopular.AddAnnotation("Relational:ColumnName", "ISPOPULAR");
            ispopular.AddAnnotation("Relational:DefaultValueSql", "((0))");
            ispopular.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var locationname = runtimeEntityType.AddProperty(
                "Locationname",
                typeof(string),
                propertyInfo: typeof(Location).GetProperty("Locationname", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Locationname>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            locationname.AddAnnotation("Relational:ColumnName", "LOCATIONNAME");
            locationname.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var mailaddress = runtimeEntityType.AddProperty(
                "Mailaddress",
                typeof(string),
                propertyInfo: typeof(Location).GetProperty("Mailaddress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Mailaddress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            mailaddress.AddAnnotation("Relational:ColumnName", "MAILADDRESS");
            mailaddress.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var phonenumber = runtimeEntityType.AddProperty(
                "Phonenumber",
                typeof(string),
                propertyInfo: typeof(Location).GetProperty("Phonenumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Location).GetField("<Phonenumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            phonenumber.AddAnnotation("Relational:ColumnName", "PHONENUMBER");
            phonenumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });

            var key0 = runtimeEntityType.AddKey(
                new[] { id, langid });
            runtimeEntityType.SetPrimaryKey(key0);

            var index = runtimeEntityType.AddIndex(
                new[] { active, locationname, langid });
            index.AddAnnotation("Relational:Name", "missing_index_46");

            var index0 = runtimeEntityType.AddIndex(
                new[] { locationname, active, langid });
            index0.AddAnnotation("Relational:Name", "missing_index_44");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "LOCATION");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
