// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models.MobileAppModels;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MobileFindeksUrlEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.MobileAppModels.MobileFindeksUrl",
                typeof(MobileFindeksUrl),
                baseEntityType,
                propertyCount: 7,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(MobileFindeksUrl).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MobileFindeksUrl).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "ID");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var birthDate = runtimeEntityType.AddProperty(
                "BirthDate",
                typeof(DateTime),
                propertyInfo: typeof(MobileFindeksUrl).GetProperty("BirthDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MobileFindeksUrl).GetField("<BirthDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            birthDate.AddAnnotation("Relational:ColumnName", "BIRTHDATE");
            birthDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var driverLicenseDate = runtimeEntityType.AddProperty(
                "DriverLicenseDate",
                typeof(DateTime),
                propertyInfo: typeof(MobileFindeksUrl).GetProperty("DriverLicenseDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MobileFindeksUrl).GetField("<DriverLicenseDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            driverLicenseDate.AddAnnotation("Relational:ColumnName", "DRIVERLICENSEDATE");
            driverLicenseDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationToken = runtimeEntityType.AddProperty(
                "ReservationToken",
                typeof(string),
                propertyInfo: typeof(MobileFindeksUrl).GetProperty("ReservationToken", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MobileFindeksUrl).GetField("<ReservationToken>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            reservationToken.AddAnnotation("Relational:ColumnName", "RESERVATIONTOKEN");
            reservationToken.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tckn = runtimeEntityType.AddProperty(
                "Tckn",
                typeof(string),
                propertyInfo: typeof(MobileFindeksUrl).GetProperty("Tckn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MobileFindeksUrl).GetField("<Tckn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            tckn.AddAnnotation("Relational:ColumnName", "TCKN");
            tckn.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var uniqueId = runtimeEntityType.AddProperty(
                "UniqueId",
                typeof(string),
                propertyInfo: typeof(MobileFindeksUrl).GetProperty("UniqueId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MobileFindeksUrl).GetField("<UniqueId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            uniqueId.AddAnnotation("Relational:ColumnName", "UNIQUEID");
            uniqueId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorId = runtimeEntityType.AddProperty(
                "VendorId",
                typeof(int),
                propertyInfo: typeof(MobileFindeksUrl).GetProperty("VendorId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MobileFindeksUrl).GetField("<VendorId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            vendorId.AddAnnotation("Relational:ColumnName", "VENDORID");
            vendorId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "MOBILEFINDEKSURL");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
