// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ProfitMarkupEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.ProfitMarkup",
                typeof(ProfitMarkup),
                baseEntityType,
                propertyCount: 18,
                navigationCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(ProfitMarkup).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "ID");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var amountCurrencyId = runtimeEntityType.AddProperty(
                "AmountCurrencyId",
                typeof(int?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("AmountCurrencyId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<AmountCurrencyId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            amountCurrencyId.AddAnnotation("Relational:ColumnName", "AMOUNTCURRENCYID");
            amountCurrencyId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var currencyId = runtimeEntityType.AddProperty(
                "CurrencyId",
                typeof(int?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("CurrencyId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<CurrencyId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            currencyId.AddAnnotation("Relational:ColumnName", "CURRENCYID");
            currencyId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var editDate = runtimeEntityType.AddProperty(
                "EditDate",
                typeof(DateTime?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("EditDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<EditDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            editDate.AddAnnotation("Relational:ColumnName", "EDITDATE");
            editDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var lastByUpdateUserId = runtimeEntityType.AddProperty(
                "LastByUpdateUserId",
                typeof(int?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("LastByUpdateUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<LastByUpdateUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastByUpdateUserId.AddAnnotation("Relational:ColumnName", "LASTUPDATEBYUSER");
            lastByUpdateUserId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var markupType = runtimeEntityType.AddProperty(
                "MarkupType",
                typeof(int?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("MarkupType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<MarkupType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            markupType.AddAnnotation("Relational:ColumnName", "MARKUPTYPE");
            markupType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var markupValue = runtimeEntityType.AddProperty(
                "MarkupValue",
                typeof(decimal?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("MarkupValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<MarkupValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            markupValue.AddAnnotation("Relational:ColumnName", "MARKUPVALUE");
            markupValue.AddAnnotation("Relational:ColumnType", "DECIMAL(10,2)");
            markupValue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var maximumAmount = runtimeEntityType.AddProperty(
                "MaximumAmount",
                typeof(decimal?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("MaximumAmount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<MaximumAmount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            maximumAmount.AddAnnotation("Relational:ColumnName", "MAXIMUMAMOUNT");
            maximumAmount.AddAnnotation("Relational:ColumnType", "DECIMAL(10,2)");
            maximumAmount.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var maximumDay = runtimeEntityType.AddProperty(
                "MaximumDay",
                typeof(int?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("MaximumDay", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<MaximumDay>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            maximumDay.AddAnnotation("Relational:ColumnName", "MAXIMUMDAY");
            maximumDay.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var minimumAmount = runtimeEntityType.AddProperty(
                "MinimumAmount",
                typeof(decimal?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("MinimumAmount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<MinimumAmount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            minimumAmount.AddAnnotation("Relational:ColumnName", "MINIMUMAMOUNT");
            minimumAmount.AddAnnotation("Relational:ColumnType", "DECIMAL(10,2)");
            minimumAmount.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var minimumDay = runtimeEntityType.AddProperty(
                "MinimumDay",
                typeof(int?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("MinimumDay", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<MinimumDay>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            minimumDay.AddAnnotation("Relational:ColumnName", "MINIMUMDAY");
            minimumDay.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(ProfitMarkup).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            name.AddAnnotation("Relational:ColumnName", "NAME");
            name.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pickupEndDate = runtimeEntityType.AddProperty(
                "PickupEndDate",
                typeof(DateTime?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("PickupEndDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<PickupEndDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            pickupEndDate.AddAnnotation("Relational:ColumnName", "PICKUPENDDATE");
            pickupEndDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pickupStartDate = runtimeEntityType.AddProperty(
                "PickupStartDate",
                typeof(DateTime?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("PickupStartDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<PickupStartDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            pickupStartDate.AddAnnotation("Relational:ColumnName", "PICKUPSTARTDATE");
            pickupStartDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var priority = runtimeEntityType.AddProperty(
                "Priority",
                typeof(int?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("Priority", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<Priority>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            priority.AddAnnotation("Relational:ColumnName", "PRIORITY");
            priority.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationEndDate = runtimeEntityType.AddProperty(
                "ReservationEndDate",
                typeof(DateTime?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("ReservationEndDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<ReservationEndDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            reservationEndDate.AddAnnotation("Relational:ColumnName", "RESERVATIONENDDATE");
            reservationEndDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationStartDate = runtimeEntityType.AddProperty(
                "ReservationStartDate",
                typeof(DateTime?),
                propertyInfo: typeof(ProfitMarkup).GetProperty("ReservationStartDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<ReservationStartDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            reservationStartDate.AddAnnotation("Relational:ColumnName", "RESERVATIONSTARTDATE");
            reservationStartDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var type = runtimeEntityType.AddProperty(
                "Type",
                typeof(int),
                propertyInfo: typeof(ProfitMarkup).GetProperty("Type", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProfitMarkup).GetField("<Type>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            type.AddAnnotation("Relational:ColumnName", "TYPE");
            type.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "PROFITMARKUPS");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
