// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ReservationVehicleInfoEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.ReservationVehicleInfo",
                typeof(ReservationVehicleInfo),
                baseEntityType,
                propertyCount: 25,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "Id");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var categoryName = runtimeEntityType.AddProperty(
                "CategoryName",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("CategoryName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<CategoryName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            categoryName.AddAnnotation("Relational:ColumnName", "CategoryName");
            categoryName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dailyPrice = runtimeEntityType.AddProperty(
                "DailyPrice",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("DailyPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<DailyPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            dailyPrice.AddAnnotation("Relational:ColumnName", "DailyPrice");
            dailyPrice.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var deliveryType = runtimeEntityType.AddProperty(
                "DeliveryType",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("DeliveryType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<DeliveryType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deliveryType.AddAnnotation("Relational:ColumnName", "DeliveryType");
            deliveryType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var deposit = runtimeEntityType.AddProperty(
                "Deposit",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("Deposit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<Deposit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            deposit.AddAnnotation("Relational:ColumnName", "Deposit");
            deposit.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var extraAmount = runtimeEntityType.AddProperty(
                "ExtraAmount",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("ExtraAmount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<ExtraAmount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            extraAmount.AddAnnotation("Relational:ColumnName", "ExtraAmount");
            extraAmount.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var extraJson = runtimeEntityType.AddProperty(
                "ExtraJson",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("ExtraJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<ExtraJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            extraJson.AddAnnotation("Relational:ColumnName", "ExtraJson");
            extraJson.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var extraNames = runtimeEntityType.AddProperty(
                "ExtraNames",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("ExtraNames", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<ExtraNames>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            extraNames.AddAnnotation("Relational:ColumnName", "ExtraNames");
            extraNames.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fuelName = runtimeEntityType.AddProperty(
                "FuelName",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("FuelName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<FuelName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            fuelName.AddAnnotation("Relational:ColumnName", "FuelName");
            fuelName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var kmLimit = runtimeEntityType.AddProperty(
                "KmLimit",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("KmLimit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<KmLimit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            kmLimit.AddAnnotation("Relational:ColumnName", "KmLimit");
            kmLimit.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var minimumAge = runtimeEntityType.AddProperty(
                "MinimumAge",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("MinimumAge", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<MinimumAge>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            minimumAge.AddAnnotation("Relational:ColumnName", "MinimumAge");
            minimumAge.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var minimumLicenseAge = runtimeEntityType.AddProperty(
                "MinimumLicenseAge",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("MinimumLicenseAge", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<MinimumLicenseAge>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            minimumLicenseAge.AddAnnotation("Relational:ColumnName", "MinimumLicenseAge");
            minimumLicenseAge.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var officeServicePrice = runtimeEntityType.AddProperty(
                "OfficeServicePrice",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("OfficeServicePrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<OfficeServicePrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            officeServicePrice.AddAnnotation("Relational:ColumnName", "OfficeServicePrice");
            officeServicePrice.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var oneWayFee = runtimeEntityType.AddProperty(
                "OneWayFee",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("OneWayFee", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<OneWayFee>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            oneWayFee.AddAnnotation("Relational:ColumnName", "OneWayFee");
            oneWayFee.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var personName = runtimeEntityType.AddProperty(
                "PersonName",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("PersonName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<PersonName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            personName.AddAnnotation("Relational:ColumnName", "PersonName");
            personName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var rentalDuration = runtimeEntityType.AddProperty(
                "RentalDuration",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("RentalDuration", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<RentalDuration>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            rentalDuration.AddAnnotation("Relational:ColumnName", "RentalDuration");
            rentalDuration.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationDetailId = runtimeEntityType.AddProperty(
                "ReservationDetailId",
                typeof(int),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("ReservationDetailId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<ReservationDetailId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            reservationDetailId.AddAnnotation("Relational:ColumnName", "ReservationDetailId");
            reservationDetailId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var specialDailyPrice = runtimeEntityType.AddProperty(
                "SpecialDailyPrice",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("SpecialDailyPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<SpecialDailyPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            specialDailyPrice.AddAnnotation("Relational:ColumnName", "SpecialDailyPrice");
            specialDailyPrice.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var specialOneWayFee = runtimeEntityType.AddProperty(
                "SpecialOneWayFee",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("SpecialOneWayFee", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<SpecialOneWayFee>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            specialOneWayFee.AddAnnotation("Relational:ColumnName", "SpecialOneWayFee");
            specialOneWayFee.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var transmissionName = runtimeEntityType.AddProperty(
                "TransmissionName",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("TransmissionName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<TransmissionName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            transmissionName.AddAnnotation("Relational:ColumnName", "TransmissionName");
            transmissionName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var typeName = runtimeEntityType.AddProperty(
                "TypeName",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("TypeName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<TypeName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            typeName.AddAnnotation("Relational:ColumnName", "TypeName");
            typeName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vehicleBrandName = runtimeEntityType.AddProperty(
                "VehicleBrandName",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("VehicleBrandName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<VehicleBrandName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            vehicleBrandName.AddAnnotation("Relational:ColumnName", "VehicleBrandName");
            vehicleBrandName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vehicleModelName = runtimeEntityType.AddProperty(
                "VehicleModelName",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("VehicleModelName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<VehicleModelName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            vehicleModelName.AddAnnotation("Relational:ColumnName", "VehicleModelName");
            vehicleModelName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vehicleName = runtimeEntityType.AddProperty(
                "VehicleName",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("VehicleName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<VehicleName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            vehicleName.AddAnnotation("Relational:ColumnName", "VehicleName");
            vehicleName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorProfitMarkup = runtimeEntityType.AddProperty(
                "VendorProfitMarkup",
                typeof(string),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("VendorProfitMarkup", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<VendorProfitMarkup>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vendorProfitMarkup.AddAnnotation("Relational:ColumnName", "VendorProfitMarkup");
            vendorProfitMarkup.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { reservationDetailId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ReservationDetailId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction,
                required: true);

            var reservationDetail = declaringEntityType.AddNavigation("ReservationDetail",
                runtimeForeignKey,
                onDependent: true,
                typeof(ReservationDetail),
                propertyInfo: typeof(ReservationVehicleInfo).GetProperty("ReservationDetail", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationVehicleInfo).GetField("<ReservationDetail>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var reservationVehicleInfos = principalEntityType.AddNavigation("ReservationVehicleInfos",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<ReservationVehicleInfo>),
                propertyInfo: typeof(ReservationDetail).GetProperty("ReservationVehicleInfos", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationDetail).GetField("<ReservationVehicleInfos>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "dbo");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RESERVATIONVEHICLEINFOS");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
