// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ReservationupdateEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Reservationupdate",
                typeof(Reservationupdate),
                baseEntityType,
                propertyCount: 11,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Reservationupdate).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "ID");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var additionalproductid = runtimeEntityType.AddProperty(
                "Additionalproductid",
                typeof(int?),
                propertyInfo: typeof(Reservationupdate).GetProperty("Additionalproductid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Additionalproductid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            additionalproductid.AddAnnotation("Relational:ColumnName", "ADDITIONALPRODUCTID");
            additionalproductid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var newvalue = runtimeEntityType.AddProperty(
                "Newvalue",
                typeof(string),
                propertyInfo: typeof(Reservationupdate).GetProperty("Newvalue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Newvalue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            newvalue.AddAnnotation("Relational:ColumnName", "NEWVALUE");
            newvalue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var oldvalue = runtimeEntityType.AddProperty(
                "Oldvalue",
                typeof(string),
                propertyInfo: typeof(Reservationupdate).GetProperty("Oldvalue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Oldvalue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            oldvalue.AddAnnotation("Relational:ColumnName", "OLDVALUE");
            oldvalue.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var propertyid = runtimeEntityType.AddProperty(
                "Propertyid",
                typeof(int),
                propertyInfo: typeof(Reservationupdate).GetProperty("Propertyid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Propertyid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            propertyid.AddAnnotation("Relational:ColumnName", "PROPERTYID");
            propertyid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservatinonumber = runtimeEntityType.AddProperty(
                "Reservatinonumber",
                typeof(string),
                propertyInfo: typeof(Reservationupdate).GetProperty("Reservatinonumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Reservatinonumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            reservatinonumber.AddAnnotation("Relational:ColumnName", "RESERVATINONUMBER");
            reservatinonumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationid = runtimeEntityType.AddProperty(
                "Reservationid",
                typeof(long),
                propertyInfo: typeof(Reservationupdate).GetProperty("Reservationid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Reservationid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            reservationid.AddAnnotation("Relational:ColumnName", "RESERVATIONID");
            reservationid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var uniqueid = runtimeEntityType.AddProperty(
                "Uniqueid",
                typeof(Guid),
                propertyInfo: typeof(Reservationupdate).GetProperty("Uniqueid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Uniqueid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            uniqueid.AddAnnotation("Relational:ColumnName", "UNIQUEID");
            uniqueid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var updatedate = runtimeEntityType.AddProperty(
                "Updatedate",
                typeof(DateTime),
                propertyInfo: typeof(Reservationupdate).GetProperty("Updatedate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Updatedate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            updatedate.AddAnnotation("Relational:ColumnName", "UPDATEDATE");
            updatedate.AddAnnotation("Relational:ColumnType", "datetime");
            updatedate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var userid = runtimeEntityType.AddProperty(
                "Userid",
                typeof(int),
                propertyInfo: typeof(Reservationupdate).GetProperty("Userid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Userid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            userid.AddAnnotation("Relational:ColumnName", "USERID");
            userid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var usernamesurname = runtimeEntityType.AddProperty(
                "Usernamesurname",
                typeof(string),
                propertyInfo: typeof(Reservationupdate).GetProperty("Usernamesurname", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Reservationupdate).GetField("<Usernamesurname>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            usernamesurname.AddAnnotation("Relational:ColumnName", "USERNAMESURNAME");
            usernamesurname.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RESERVATIONUPDATE");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
