// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.Domain.Models.StoredPorcedureModels;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ReservationReportModelEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.Domain.Models.StoredPorcedureModels.ReservationReportModel",
                typeof(ReservationReportModel),
                baseEntityType,
                propertyCount: 15);

            var agencyInvoiceNumber = runtimeEntityType.AddProperty(
                "AgencyInvoiceNumber",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("AgencyInvoiceNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<AgencyInvoiceNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            agencyInvoiceNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var apiReservationNumber = runtimeEntityType.AddProperty(
                "ApiReservationNumber",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("ApiReservationNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<ApiReservationNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            apiReservationNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var brokerProgressPayment = runtimeEntityType.AddProperty(
                "BrokerProgressPayment",
                typeof(decimal),
                propertyInfo: typeof(ReservationReportModel).GetProperty("BrokerProgressPayment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<BrokerProgressPayment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            brokerProgressPayment.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var customerName = runtimeEntityType.AddProperty(
                "CustomerName",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("CustomerName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<CustomerName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            customerName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pickupDate = runtimeEntityType.AddProperty(
                "PickupDate",
                typeof(DateTime),
                propertyInfo: typeof(ReservationReportModel).GetProperty("PickupDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<PickupDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            pickupDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pickupLocation = runtimeEntityType.AddProperty(
                "PickupLocation",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("PickupLocation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<PickupLocation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            pickupLocation.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationDate = runtimeEntityType.AddProperty(
                "ReservationDate",
                typeof(DateTime),
                propertyInfo: typeof(ReservationReportModel).GetProperty("ReservationDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<ReservationDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            reservationDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationNumber = runtimeEntityType.AddProperty(
                "ReservationNumber",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("ReservationNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<ReservationNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            reservationNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationPrice = runtimeEntityType.AddProperty(
                "ReservationPrice",
                typeof(decimal),
                propertyInfo: typeof(ReservationReportModel).GetProperty("ReservationPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<ReservationPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            reservationPrice.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var reservationStatus = runtimeEntityType.AddProperty(
                "ReservationStatus",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("ReservationStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<ReservationStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            reservationStatus.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var returnDate = runtimeEntityType.AddProperty(
                "ReturnDate",
                typeof(DateTime),
                propertyInfo: typeof(ReservationReportModel).GetProperty("ReturnDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<ReturnDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            returnDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var returnLocation = runtimeEntityType.AddProperty(
                "ReturnLocation",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("ReturnLocation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<ReturnLocation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            returnLocation.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorInvoiceNumber = runtimeEntityType.AddProperty(
                "VendorInvoiceNumber",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("VendorInvoiceNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<VendorInvoiceNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vendorInvoiceNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorName = runtimeEntityType.AddProperty(
                "VendorName",
                typeof(string),
                propertyInfo: typeof(ReservationReportModel).GetProperty("VendorName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<VendorName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vendorName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorProgressPayment = runtimeEntityType.AddProperty(
                "VendorProgressPayment",
                typeof(decimal),
                propertyInfo: typeof(ReservationReportModel).GetProperty("VendorProgressPayment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ReservationReportModel).GetField("<VendorProgressPayment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            vendorProgressPayment.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewDefinitionSql", null);
            runtimeEntityType.AddAnnotation("Relational:ViewName", "ReservationReportModel");
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
