// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ResstatushistoryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Resstatushistory",
                typeof(Resstatushistory),
                baseEntityType,
                propertyCount: 11,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(Resstatushistory).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.AddAnnotation("Relational:ColumnName", "ID");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var resno = runtimeEntityType.AddProperty(
                "Resno",
                typeof(string),
                propertyInfo: typeof(Resstatushistory).GetProperty("Resno", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Resno>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 50);
            resno.AddAnnotation("Relational:ColumnName", "RESNO");
            resno.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var agencyid = runtimeEntityType.AddProperty(
                "Agencyid",
                typeof(int?),
                propertyInfo: typeof(Resstatushistory).GetProperty("Agencyid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Agencyid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            agencyid.AddAnnotation("Relational:ColumnName", "AGENCYID");
            agencyid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var agencyname = runtimeEntityType.AddProperty(
                "Agencyname",
                typeof(string),
                propertyInfo: typeof(Resstatushistory).GetProperty("Agencyname", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Agencyname>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 150);
            agencyname.AddAnnotation("Relational:ColumnName", "AGENCYNAME");
            agencyname.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var inserteddate = runtimeEntityType.AddProperty(
                "Inserteddate",
                typeof(DateTime?),
                propertyInfo: typeof(Resstatushistory).GetProperty("Inserteddate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Inserteddate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            inserteddate.AddAnnotation("Relational:ColumnName", "INSERTEDDATE");
            inserteddate.AddAnnotation("Relational:ColumnType", "datetime");
            inserteddate.AddAnnotation("Relational:DefaultValueSql", "(getdate())");
            inserteddate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resid = runtimeEntityType.AddProperty(
                "Resid",
                typeof(long?),
                propertyInfo: typeof(Resstatushistory).GetProperty("Resid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Resid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            resid.AddAnnotation("Relational:ColumnName", "RESID");
            resid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resstatusid = runtimeEntityType.AddProperty(
                "Resstatusid",
                typeof(int?),
                propertyInfo: typeof(Resstatushistory).GetProperty("Resstatusid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Resstatusid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            resstatusid.AddAnnotation("Relational:ColumnName", "RESSTATUSID");
            resstatusid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resstatusname = runtimeEntityType.AddProperty(
                "Resstatusname",
                typeof(string),
                propertyInfo: typeof(Resstatushistory).GetProperty("Resstatusname", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Resstatusname>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            resstatusname.AddAnnotation("Relational:ColumnName", "RESSTATUSNAME");
            resstatusname.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resstatusnote = runtimeEntityType.AddProperty(
                "Resstatusnote",
                typeof(string),
                propertyInfo: typeof(Resstatushistory).GetProperty("Resstatusnote", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Resstatusnote>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            resstatusnote.AddAnnotation("Relational:ColumnName", "RESSTATUSNOTE");
            resstatusnote.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var userid = runtimeEntityType.AddProperty(
                "Userid",
                typeof(int?),
                propertyInfo: typeof(Resstatushistory).GetProperty("Userid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Userid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            userid.AddAnnotation("Relational:ColumnName", "USERID");
            userid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vendorid = runtimeEntityType.AddProperty(
                "Vendorid",
                typeof(int?),
                propertyInfo: typeof(Resstatushistory).GetProperty("Vendorid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Vendorid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            vendorid.AddAnnotation("Relational:ColumnName", "VENDORID");
            vendorid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id, resno });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { resid });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("Resid") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Rezid") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            var rez = declaringEntityType.AddNavigation("Rez",
                runtimeForeignKey,
                onDependent: true,
                typeof(Rez),
                propertyInfo: typeof(Resstatushistory).GetProperty("Rez", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Resstatushistory).GetField("<Rez>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var rezStatusHistories = principalEntityType.AddNavigation("RezStatusHistories",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Resstatushistory>),
                propertyInfo: typeof(Rez).GetProperty("RezStatusHistories", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Rez).GetField("<RezStatusHistories>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "RESSTATUSHISTORY");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
