// <auto-generated />
using System;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class UyeEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Uye",
                typeof(Uye),
                baseEntityType,
                propertyCount: 21,
                keyCount: 1);

            var uyeid = runtimeEntityType.AddProperty(
                "Uyeid",
                typeof(int),
                propertyInfo: typeof(Uye).GetProperty("Uyeid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Uyeid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            uyeid.AddAnnotation("Relational:ColumnName", "UYEID");
            uyeid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ad = runtimeEntityType.AddProperty(
                "Ad",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Ad", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Ad>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 250);
            ad.AddAnnotation("Relational:ColumnName", "AD");
            ad.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var adres = runtimeEntityType.AddProperty(
                "Adres",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Adres", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Adres>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 500);
            adres.AddAnnotation("Relational:ColumnName", "ADRES");
            adres.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var agencyid = runtimeEntityType.AddProperty(
                "Agencyid",
                typeof(int?),
                propertyInfo: typeof(Uye).GetProperty("Agencyid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Agencyid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            agencyid.AddAnnotation("Relational:ColumnName", "AGENCYID");
            agencyid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var aktif = runtimeEntityType.AddProperty(
                "Aktif",
                typeof(bool?),
                propertyInfo: typeof(Uye).GetProperty("Aktif", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Aktif>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            aktif.AddAnnotation("Relational:ColumnName", "AKTIF");
            aktif.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var birthday = runtimeEntityType.AddProperty(
                "Birthday",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Birthday", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Birthday>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            birthday.AddAnnotation("Relational:ColumnName", "BIRTHDAY");
            birthday.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var commercialallowance = runtimeEntityType.AddProperty(
                "Commercialallowance",
                typeof(bool?),
                propertyInfo: typeof(Uye).GetProperty("Commercialallowance", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Commercialallowance>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            commercialallowance.AddAnnotation("Relational:ColumnName", "COMMERCIALALLOWANCE");
            commercialallowance.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var defaultmember = runtimeEntityType.AddProperty(
                "Defaultmember",
                typeof(bool?),
                propertyInfo: typeof(Uye).GetProperty("Defaultmember", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Defaultmember>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            defaultmember.AddAnnotation("Relational:ColumnName", "DEFAULTMEMBER");
            defaultmember.AddAnnotation("Relational:DefaultValueSql", "((0))");
            defaultmember.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var eposta = runtimeEntityType.AddProperty(
                "Eposta",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Eposta", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Eposta>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 250);
            eposta.AddAnnotation("Relational:ColumnName", "EPOSTA");
            eposta.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ip = runtimeEntityType.AddProperty(
                "Ip",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Ip", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Ip>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100,
                unicode: false);
            ip.AddAnnotation("Relational:ColumnName", "IP");
            ip.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var membertype = runtimeEntityType.AddProperty(
                "Membertype",
                typeof(byte?),
                propertyInfo: typeof(Uye).GetProperty("Membertype", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Membertype>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            membertype.AddAnnotation("Relational:ColumnName", "MEMBERTYPE");
            membertype.AddAnnotation("Relational:DefaultValueSql", "((0))");
            membertype.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pwd = runtimeEntityType.AddProperty(
                "Pwd",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Pwd", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Pwd>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 250);
            pwd.AddAnnotation("Relational:ColumnName", "PWD");
            pwd.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var soyad = runtimeEntityType.AddProperty(
                "Soyad",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Soyad", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Soyad>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 250);
            soyad.AddAnnotation("Relational:ColumnName", "SOYAD");
            soyad.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var subagencyuser = runtimeEntityType.AddProperty(
                "Subagencyuser",
                typeof(bool?),
                propertyInfo: typeof(Uye).GetProperty("Subagencyuser", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Subagencyuser>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAdd);
            subagencyuser.AddAnnotation("Relational:ColumnName", "SUBAGENCYUSER");
            subagencyuser.AddAnnotation("Relational:DefaultValueSql", "((0))");
            subagencyuser.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tcpasaport = runtimeEntityType.AddProperty(
                "Tcpasaport",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Tcpasaport", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Tcpasaport>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            tcpasaport.AddAnnotation("Relational:ColumnName", "TCPASAPORT");
            tcpasaport.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var telefon = runtimeEntityType.AddProperty(
                "Telefon",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Telefon", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Telefon>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 250);
            telefon.AddAnnotation("Relational:ColumnName", "TELEFON");
            telefon.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var unvan = runtimeEntityType.AddProperty(
                "Unvan",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Unvan", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Unvan>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 250);
            unvan.AddAnnotation("Relational:ColumnName", "UNVAN");
            unvan.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var uyetip = runtimeEntityType.AddProperty(
                "Uyetip",
                typeof(byte?),
                propertyInfo: typeof(Uye).GetProperty("Uyetip", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Uyetip>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            uyetip.AddAnnotation("Relational:ColumnName", "UYETIP");
            uyetip.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var uyetipmembertype = runtimeEntityType.AddProperty(
                "Uyetipmembertype",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Uyetipmembertype", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Uyetipmembertype>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1,
                unicode: false);
            uyetipmembertype.AddAnnotation("Relational:ColumnName", "UYETIPMEMBERTYPE");
            uyetipmembertype.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vergidaire = runtimeEntityType.AddProperty(
                "Vergidaire",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Vergidaire", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Vergidaire>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            vergidaire.AddAnnotation("Relational:ColumnName", "VERGIDAIRE");
            vergidaire.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var vergino = runtimeEntityType.AddProperty(
                "Vergino",
                typeof(string),
                propertyInfo: typeof(Uye).GetProperty("Vergino", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Uye).GetField("<Vergino>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            vergino.AddAnnotation("Relational:ColumnName", "VERGINO");
            vergino.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { uyeid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "UYE");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
