// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using KolayCAR.Broker.API.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KolayCAR.Broker.API.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class VehiclebaggagelangEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "KolayCAR.Broker.API.Models.Vehiclebaggagelang",
                typeof(Vehiclebaggagelang),
                baseEntityType,
                propertyCount: 3,
                navigationCount: 1,
                foreignKeyCount: 1,
                keyCount: 1);

            var baggageid = runtimeEntityType.AddProperty(
                "Baggageid",
                typeof(int),
                propertyInfo: typeof(Vehiclebaggagelang).GetProperty("Baggageid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Vehiclebaggagelang).GetField("<Baggageid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            baggageid.AddAnnotation("Relational:ColumnName", "BAGGAGEID");
            baggageid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var langid = runtimeEntityType.AddProperty(
                "Langid",
                typeof(int),
                propertyInfo: typeof(Vehiclebaggagelang).GetProperty("Langid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Vehiclebaggagelang).GetField("<Langid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            langid.AddAnnotation("Relational:ColumnName", "LANGID");
            langid.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var baggagename = runtimeEntityType.AddProperty(
                "Baggagename",
                typeof(string),
                propertyInfo: typeof(Vehiclebaggagelang).GetProperty("Baggagename", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Vehiclebaggagelang).GetField("<Baggagename>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            baggagename.AddAnnotation("Relational:ColumnName", "BAGGAGENAME");
            baggagename.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { baggageid, langid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("Baggageid") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Baggageid") }),
                principalEntityType,
                required: true);

            var baggage = declaringEntityType.AddNavigation("Baggage",
                runtimeForeignKey,
                onDependent: true,
                typeof(Vehiclebaggage),
                propertyInfo: typeof(Vehiclebaggagelang).GetProperty("Baggage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Vehiclebaggagelang).GetField("<Baggage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var vehiclebaggagelang = principalEntityType.AddNavigation("Vehiclebaggagelang",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Vehiclebaggagelang>),
                propertyInfo: typeof(Vehiclebaggage).GetProperty("Vehiclebaggagelang", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Vehiclebaggage).GetField("<Vehiclebaggagelang>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_ARACBAGAJDIL_ARACBAGAJ");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "VEHICLEBAGGAGELANG");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
