using KolayCAR.Broker.Domain.Models.Requests;
using System;
using System.Collections.Generic;

namespace KolayCAR.Broker.API.Models
{
    public partial class Rez
    {
        public long Rezid { get; set; }
        public string Rezno { get; set; }
        public string Apireservationnumber { get; set; }
        public string Agencyreservationreference { get; set; }
        public bool Servisegonderildi { get; set; }
        public int? Uyeid { get; set; }
        public int? Kaynak { get; set; }
        public int? Tedarikciid { get; set; }
        public int Aracid { get; set; }
        public DateTime Tarih { get; set; }
        public DateTime Alistarihi { get; set; }
        public DateTime Birakistarihi { get; set; }
        public int Alisyerid { get; set; }
        public int Birakisyerid { get; set; }
        public int Dovizid { get; set; }
        public int Dilid { get; set; }
        public int Kiralamasuresi { get; set; }
        public decimal Gunlukfiyat { get; set; }
        public decimal Extratutar { get; set; }
        public decimal Tekyontutar { get; set; }
        public decimal Toplamtutar { get; set; }
        public decimal Odenentutar { get; set; }
        public bool Odemebasarili { get; set; }
        public string Odemehatamesaji { get; set; }
        public string Odemekartsahibi { get; set; }
        public string Odemekartno { get; set; }
        public string Extralar { get; set; }
        public byte? Musteritip { get; set; }
        public string Musteriad { get; set; }
        public string Musterisoyad { get; set; }
        public string Musteritelefon { get; set; }
        public string Musterieposta { get; set; }
        public string Musteritcpasaport { get; set; }
        public string Musteriadres { get; set; }
        public string Musteriunvan { get; set; }
        public string Musterivergidaire { get; set; }
        public string Musterivergino { get; set; }
        public string Musterigelisucusno { get; set; }
        public string Musteridonusucusno { get; set; }
        public string Musterinot { get; set; }
        public string Musteriaciklama { get; set; }
        public bool? Musteriebulten { get; set; }
        public string Aracadi { get; set; }
        public string Alisyeri { get; set; }
        public string Birakisyeri { get; set; }
        public string Parakod { get; set; }
        public string Extraidlist { get; set; }
        public string Provizyonno { get; set; }
        public string Ip { get; set; }
        public string Sifreliveri { get; set; }
        public string Kuponkod { get; set; }
        public bool Pesinataktif { get; set; }
        public string Skyscannerredirectid { get; set; }
        public int Vendorid { get; set; }
        public int? Agencyid { get; set; }
        public int? Resstatusid { get; set; }
        public string Resstatusnote { get; set; }
        public string Pdf { get; set; }
        public int Vendortype { get; set; }
        public int? Entegrasyonid { get; set; }
        public int? Acenteid { get; set; }
        public bool? Iscancelable { get; set; }
        public decimal Apidailyprice { get; set; }
        public decimal Apiextraamount { get; set; }
        public decimal Apionewayfee { get; set; }
        public decimal Apitotalamount { get; set; }
        public bool Reservationemailsendtocustomerfromsourceapi { get; set; }
        public bool Reservationemailsendtoadminfromsourceapi { get; set; }
        public bool Reservationsmssendtocustomerfromsourceapi { get; set; }
        public int Paymenttype { get; set; }
        public bool Apireservationsuccessfully { get; set; }
        public string Vendorphone { get; set; }
        public string Vendoremail { get; set; }
        public string Vendorname { get; set; }
        public string Apivendorname { get; set; }
        public decimal? Agencycommission { get; set; }
        public decimal? Profitmarkup { get; set; }
        public string Statusname { get; set; }
        public string Agencyname { get; set; }
        public bool? Apireservationcancel { get; set; }
        public decimal? Servicecharge { get; set; }
        public int? Servicechargecurrencyid { get; set; }
        public string Apivendoraddress { get; set; }
        public string Apivendorphone { get; set; }
        public decimal? Exchangerate { get; set; }
        public string Apivendorreturnaddress { get; set; }
        public string Apivendorreturnphone { get; set; }
        public decimal? Depositprice { get; set; }
        public int? Vendormindriverage { get; set; }
        public int? Vendormindrivinglicenseage { get; set; }
        public bool? Sendreservationmail { get; set; }
        public string Apimessage { get; set; }
        public DateTime? Customerbirthday { get; set; }
        public string Departureinfo { get; set; }
        public string Vehicleimageurl { get; set; }
        public bool? Isoffice { get; set; }
        public int? Fueltype { get; set; }
        public int? Transmissiontype { get; set; }
        public string Vendorlogo { get; set; }
        public string Apireferencecode { get; set; }
        public int? Apicurrencyid { get; set; }
        public string Agencycode { get; set; }
        public decimal? Apiexchangerate { get; set; }
        public decimal? Profitmarkupadditionalproducts { get; set; }
        public decimal? Profitmarkuponewayfee { get; set; }
        public bool? Depositcreditcardrequired { get; set; }
        public bool? Apiphoneactive { get; set; }
        public string Paymentresultmessage { get; set; }
        public string Paymentresultcode { get; set; }
        public int? Bankid { get; set; }
        public string Provisionnumber { get; set; }
        public decimal? Paymentamount { get; set; }
        public string Alerterrorcode { get; set; }
        public string Logresultnumber { get; set; }
        public string Logerrorcode { get; set; }
        public int? Creditcarddiscountpercent { get; set; }
        public int? Moneyforreservationscore { get; set; }
        public decimal? Reservationscoreformoney { get; set; }
        public int? Score { get; set; }
        public string Apireferencecode2 { get; set; }
        public string Apireferencecode3 { get; set; }
        public int? Couponid { get; set; }
        public string Couponcode { get; set; }
        public decimal? Coupondiscountamount { get; set; }
        public decimal? Coupondiscountvalue { get; set; }
        public int? Coupondiscounttype { get; set; }
        public int? Couponcurrencyid { get; set; }
        public decimal? Apipaidamount { get; set; }
        public decimal? Specialdailyprice { get; set; }
        public decimal? Specialonewayfee { get; set; }
        public int? Baserequestcurrencyid { get; set; }
        public string Sippcode { get; set; }
        public string Vehiclecode { get; set; }
        public bool? Useonlydefaultcurrency { get; set; }
        public bool? Extrapricepaytodelivery { get; set; }
        public bool? Onewayfeepaytodelivery { get; set; }
        public bool? Isspecialwebsiteagency { get; set; }
        public string Membername { get; set; }
        public DateTime? Updatedate { get; set; }
        public string Reservationtoken { get; set; }
        public int? Vehicletype { get; set; }
        public int? Vehiclecategorytype { get; set; }
        public int? Passangerquantitytype { get; set; }
        public int? Baggagequantitytype { get; set; }
        public bool? Commercialallowance { get; set; }
        public int? Sourceid { get; set; }
        public int? Installmentcount { get; set; }
        public int? Totalkmlimit { get; set; }
        public string Defaultcustomermailaddress { get; set; }
        public decimal? Agencyrentalprofitmarkup { get; set; }
        public int? Rentalworkingtype { get; set; }
        public int? Additionalproductworkingtype { get; set; }
        public int? Onewayfeeworkingtype { get; set; }
        public int? Cancellationpenaltyrate { get; set; }
        public decimal? Cancellationrefundedamount { get; set; }
        public int? Cancellationpenaltyhour { get; set; }
        public bool? Paymentrefundsuccess { get; set; }
        public string Reservationtokentext { get; set; }
        public bool? Advancedpaymentwithoutpayment { get; set; }
        public decimal? Penaltyamount { get; set; }
        public _penaltyStatus? PenaltyStatus { get; set; }
        //public string SurveyComment { get; set; }
        public decimal? RefundAmount { get; set; }
        public string INVOICENUMBER { get; set; }
        public string AGENCYINVOICENUMBER { get; set; }
        public string FriendlyReservationNumber { get; set; }
        public string Bank { get; set; }
        public string CreditCardBank { get; set; }
        public decimal? VendorDiscountValue { get; set; }
        public string Canceller { get; set; }
        public string ReturnInvoiceNumber { get; set; }
        public string AgencyReturnInvoiceNumber { get; set; }
        public string CreditCardNumber { get; set; }
        public decimal? InstallmentCommissionAmount { get; set; }
        public bool? IsFullCredit { get; set; }

        public string CouponName { get; set; }
        public decimal? PremiumExtraAmount { get; set; }
        public string PaymentCode { get; set; }
        public bool? VendorFlightPassRequired { get; set; }
        public string ExternalCreditCardInfo { get; set; }
        public string PickupOfficeWorkingHours { get; set; }
        public string ReturnOfficeWorkingHours { get; set; }
        public int? ApiDeliveryTypeId { get; set; }
        public virtual ICollection<Resstatushistory> RezStatusHistories { get; set; }
    }
}
